### ISSUE TITLE
Converting wav2vec2-base-960h to ONNX report an error while converting

### ISSUE THREAD

**Issue by Denovitz** [huggingface/transformers#10004]
First of all, I want to say thanks to @patrickvonplaten for the work done in adding the model. Great job!

I tried to convert the model to ONNX but got an error, do you have any ideas how to fix it?

What I did:
`python -m transformers.convert_graph_to_onnx --framework pt  --model facebook/wav2vec2-base-960h wav2vec2-base-960h.onnx`

But got an error:
```====== Converting model to ONNX ======
ONNX opset version set to: 11
Loading pipeline (model: facebook/wav2vec2-base-960h, tokenizer: facebook/wav2vec2-base-960h)
Using framework PyTorch: 1.7.0
Error while converting the model: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.
```

**Comment by mironnn** [comment]
Also interested in this question!

**Comment by patrickvonplaten** [comment]
Hmm, Wav2Vec2 is still a very recent addition and I don't have a good idea on an ETA for full ONNX support. However, I think your error above is due to the input that's passed to `Wav2Vec2Tokenizer` being a string instead of a speech input. So in order to make the conversion work, you will have to tweak the script `convert_graph_to_onnx` yourself a bit for Wav2Vec2 - I think the only different should be that instead of passing it `"This is a sample output"` you should pass it a 1D float array.

**Comment by OthmaneJ** [comment]
Hi!
very interested in this question! did anyone managed to make it work ?

**Comment by patrickvonplaten** [comment]
Hey @OthmaneJ,

Think @ccoreilly managed to get it to work here: https://github.com/ccoreilly/wav2vec2-service/blob/master/convert_torch_to_onnx.py

**Comment by OthmaneJ** [comment]
@patrickvonplaten thanks! 👌

**Comment by marziye-A** [comment]
hi @patrickvonplaten 
 is there any way to transform mms asr model to onnx?
if yes, how?
thank you very much!

**Comment by abdouaziz** [comment]
> hi @patrickvonplaten is there any way to transform mms asr model to onnx? if yes, how? thank you very much!

You can this : https://github.com/ccoreilly/wav2vec2-service/blob/master/convert_torch_to_onnx.py
