### ISSUE TITLE
different behavior for get_input_embeddings()  between 4.2.x  and 4.3.x in Tensorflow

### ISSUE THREAD

**Issue by AndyTheFactory** [huggingface/transformers#10208]
## Environment info

- `transformers` version: 4.2.x vs 4.3.x
- Platform: Colab
- Python version: 3.6
- Tensorflow version (GPU?): 2.4.1

@jplu 

## Information

Model I am using (Bert, XLNet ...): Bert

## To reproduce

In version 4.3.x the following code 
```
model = TFBertForSequenceClassification.from_pretrained('bert-base-uncased')
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
input = tokenizer.batch_encode_plus(['this is a test'])

embeddings = model.get_input_embeddings()
embeddings(input_ids=np.array(input['input_ids']), token_type_ids=np.array(input['token_type_ids']))

```

Throws an error:

> TypeError: call() got an unexpected keyword argument 'token_type_ids'

## Expected behavior

In version 4.2.x the code returned a tensor:

> <tf.Tensor: shape=(1, 6, 768), dtype=float32, [...]

Test also as [colab](https://colab.research.google.com/drive/1z5rboqdz8y8IM90FX8fDzixez9K_Efdy?usp=sharing)

**Comment by jplu** [comment]
Hello!

This is because in the 4.3 version the implementation of the embedding have changed and `get_input_embeddings()` returns only the word embeddings layer, hence only `input_ids` can be passed.

This was an unexpected behavior and will be fixed for the next release (the fix is already in master if you want). Sorry for the inconvenience.

**Comment by AndyTheFactory** [comment]
thank you for the quick reply!

Ok, i was unaware it was already fixed in master

Thank you!
