### ISSUE TITLE
Tensorflow not found but i can import it

### ISSUE THREAD

**Issue by fedor360139** [huggingface/transformers#10302]
## Environment info

- `transformers` version: 4.4.0.dev0
- Platform: macOS-11.2.1-arm64-arm-64bit
- Python version: 3.8.6
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

@jplu, @patrickvonplaten, @LysandreJik 

## Description
When i import transformers i get message bellow.

## To reproduce

1. install tf for mac m1(https://github.com/apple/tensorflow_macos)
2. install transformers
3. import transformers

Message when i import transformers:
```
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
```

## Expected behavior
I'd like to make transformers find tensorflow.

**Comment by cronoik** [comment]
What is the output of:
```
import tensorflow
print(tensorflow.__version__)
```
?

**Comment by fedor360139** [comment]
> What is the output of:
> 
> ```
> import tensorflow
> print(tensorflow.__version__)
> ```
> 
> ?

'2.4.0-rc0'

**Comment by jplu** [comment]
Hello!

We currently don't support other implementations than the Google's pypi versions. The reason is because we don't tests on other versions and then we cannot guarantee it will works on those "extra" versions.

To make `transformers` works on Mac I suggest you to use the official version of TensorFlow as proposed in their documentation https://www.tensorflow.org/install/pip
