### ISSUE TITLE
Question answering: a couple of things after fine-tuning a model

### ISSUE THREAD

**Issue by LivingDeadCloud** [huggingface/transformers#10684]
Hello everybody

First of all, I'm kinda new to HF and transformers library, so I apologize if my questions may be be trivial.

I followed the very well explained guide provided [here](https://github.com/huggingface/notebooks/blob/master/examples/question_answering.ipynbl) to fine-tune a pre-trained model (for the moment, I used the standard SQuaD dataset). The model has been fine-tuned correctly, saved and evaluated, giving as expected the following results: `{'exact_match': 76.80227057710502, 'f1': 84.96565168555021}`

That said, here are my questions:

1. Now that I have this model, how can I use it to answer to a "custom" question on a specific context? I am assuming that I will need to preprocess the question+context in a way similar to the preprocessing of training dataset, but how can I exactly do that? I will have to use this model in another script, so having the possibility to have a function that gets as input (model, context, question) and gives me as output the predicted answer (possibly with its probability) would be great, is there some piece of code that does this?
2. As final goal I will have to fine-tune an italian language model. I'm assuming that this depends on the value of `model_checkpoint`, so here I would have to select an italian pre-trained model (for example [dbmdz/bert-base-italian-cased](https://huggingface.co/dbmdz/bert-base-italian-cased)), is that correct? And if I want to use a multilanguage model, how do I specify the language I want to use?
3. (this may be a very dumb question) Can I fine-tune an already fine-tuned model (for example [this model](https://huggingface.co/mrm8488/bert-italian-finedtuned-squadv1-it-alfa))? Would it make sense? I'm asking this because in the future I will likely be able to expand my training set, so I want to know if I have to restart from a pre-trained model or if I can fine-tune an already tuned model several times.

Thanks a lot for your patience.

Claudio

**Comment by NielsRogge** [comment]
Here's an answer to your questions:

> 1. Now that I have this model, how can I use it to answer to a "custom" question on a specific context? I am assuming that I will need to preprocess the question+context in a way similar to the preprocessing of training dataset, but how can I exactly do that?

Yes, I've created a small Colab notebook to illustrate inference for question answering models: https://colab.research.google.com/drive/1F-4rWIDythF4B8hS6SdNx9x3h3ffg2zw?usp=sharing

> 2\. As final goal I will have to fine-tune an italian language model. I'm assuming that this depends on the value of `model_checkpoint`, so here I would have to select an italian pre-trained model (for example [dbmdz/bert-base-italian-cased](https://huggingface.co/dbmdz/bert-base-italian-cased)), is that correct? And if I want to use a multilanguage model, how do I specify the language I want to use?

If you want to fine-tune on an Italian dataset, then it's indeed best to start from a pre-trained Italian model. If you want to use a multilanguage model, you don't need to specify any language you want to use, because it's a general-purpose model. Just make sure that Italian is one of the languages on which the multi-lingual model was pre-trained.

> 3\. (this may be a very dumb question) Can I fine-tune an already fine-tuned model (for example [this model](https://huggingface.co/mrm8488/bert-italian-finedtuned-squadv1-it-alfa))? Would it make sense?

Yes you can, and it's maybe the best thing to do, because as this model is already fine-tuned on Italian questions, then it will already have reasonable performance out-of-the-box. You can just improve it a little more on your specific dataset by fine-tuning a bit more.

Btw, it's advised to ask such questions on the [forum](https://discuss.huggingface.co/) rather than here, as the authors of HuggingFace like to keep Github issues for bugs and feature requests.

Cheers!

**Comment by LivingDeadCloud** [comment]
Many thanks @NielsRogge , I discovered the existence of the forum 20 minutes after posting this, my bad :(

I will use the forum now to ask some more things.

Thansk a lot!
