### ISSUE TITLE
`resize_token_embeddings` not taken into account in `save_pretrained` for `EncoderDecoderModel`

### ISSUE THREAD

**Issue by rahular** [huggingface/transformers#11285]
## Environment info
- `transformers` version: 4.5.0
- Platform: Darwin-17.7.0-x86_64-i386-64bit
- Python version: 3.7.2
- PyTorch version (GPU?): 1.4.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help
@patrickvonplaten, @patil-suraj

## Information
I am extending the embeddings of the decoder of an `EncoderDecoderModel` model. When I save it, the config does not reflect the new size. However, it works fine when I try doing the same for non `EncoderDecoderModel` models.

## To reproduce
```
In [1]: model = t.EncoderDecoderModel.from_encoder_decoder_pretrained('bert-base-uncased', 'bert-base-uncased')

In [2]: model.decoder.bert.embeddings.word_embeddings
Out[2]: Embedding(30522, 768, padding_idx=0)

In [3]: model.decoder.resize_token_embeddings(30522+100)
Out[3]: Embedding(30622, 768)

In [4]: model.save_pretrained('test-bert')
```

## Expected behavior
The updated embedding size should be saved in `config.json`

**Comment by cronoik** [comment]
This is caused by the EncoderDecoderConfig which initializes independent objects ([link](https://github.com/huggingface/transformers/blob/d9c62047a8d75e18d2849d345ab3394875a712ef/src/transformers/models/encoder_decoder/configuration_encoder_decoder.py#L84)) instead of utilizing the already existing ones.

You can fix that for the moment by calling:
```
model.config.decoder = model.decoder.config
model.config.encoder = model.encoder.config
```
PR will follow.
