### ISSUE TITLE
Can this `@slow` annotation be removed at barthez tokenizer test=

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/transformers#11457]
Here is a `@slow` annotation that can be removed IMO.
Otherwise maybe write a comment why it is tagged as slow?

https://github.com/huggingface/transformers/blob/bc2571e61c985ec82819cf01ad038342771c94d0/tests/test_tokenization_barthez.py#L27

I can provide a PR.

**Comment by sgugger** [comment]
No it is intended as slow. The Barthez tokenizer fast tokenizer takes forever to load from the slow one sadly, which is why we marked those tests are slow. To be able to remove that, we must first create a small sentencepiece model that is compatible with Barthez (it is using the real tokenizer checkpoint right now) and then the tests can be marked as unslow.

**Comment by PhilipMay** [comment]
Ok thanks. Slosing this then.

**Comment by PhilipMay** [comment]
@sgugger When do you execute the slow tests? Do you do it manually before you do a release?

**Comment by LysandreJik** [comment]
They run once every day!

**Comment by PhilipMay** [comment]
Ahh ok thanks.
