### ISSUE TITLE
Number of BART layers is confusing in the Pretrained models page

### ISSUE THREAD

**Issue by mnskim** [huggingface/transformers#11574]
In the [Pretrained models](https://huggingface.co/transformers/pretrained_models.html) page, facebook/bart-large is described as 24-layer, 1024-hidden, 16-heads, 406M parameters, and facebook/bart-base as 12-layer, 768-hidden, 16-heads, 139M parameters.

I think this is a little confusing because bart-base consists of 6 encoder layers and 6 decoder layers, and bart-large consists of 12 layers each. (You can check in [the fairseq repo](https://github.com/pytorch/fairseq/tree/master/examples/bart)) 

I think specifying the layers as: "N encoder layers, N decoder layers" would be a lot clearer

**Comment by patil-suraj** [comment]
Hi @mnskim 

Usually, we specify the total number of layers in a model instead of an individual components layer (i.e encoder or decoder). And seq2seq models like BART, T5 usually use the same number of layers in both encoder-decoder i.e 6-6 or 12-12. We could specify the encoder layer and decoder layer if they are different.

But yeah, if you think specifying encoder and decoder layer is clearer then feel free to open a PR :) We could write 12 layer (6 encoder and 6 decoder layers). Thanks.

**Comment by ayaka14732** [comment]
There is another issue with this page. facebook/bart-base actually contains 12 heads, not 16 heads. Unfortunately, the file for this page has been removed, so it cannot be updated anymore. The wrong page is still available on Google, though.

![](https://user-images.githubusercontent.com/68557794/160236798-5fb25524-5851-48a1-b6c6-605b9afb197d.png)

![](https://user-images.githubusercontent.com/68557794/160236815-40cd6335-cc5b-40f4-93a5-59a2f7d6788f.png)
