### ISSUE TITLE
Roberta for NER task

### ISSUE THREAD

**Issue by sl-victormazzeo** [huggingface/transformers#1166]
## ❓ Questions & Help

Hello, is there a way to use Roberta model for NER task? Is there a script somewhere? 

Thank you.

**Comment by thomwolf** [comment]
Hi @militu you should take a look at this long thread discussing NER for BERT (should be the same for RoBERTa): https://github.com/huggingface/pytorch-transformers/issues/64

**Comment by byzhang** [comment]
But there is not RobertaForTokenClassification and TFRobertaForTokenClassification like BertForTokenClassification and TFBertForTokenClassification.

**Comment by FacingBugs** [comment]
Using BPE tokenizer, all the text tokens are encoded to some binary-unicoded strings. The first ten tokens in the RoberTa Vocab file are listed below:  
 
```
{"<s>": 0, "<pad>": 1, "</s>": 2, "<unk>": 3, ".": 4, "Ġthe": 5, ",": 6, "Ġto": 7, "Ġand": 8, "Ġof": 9, "Ġa": 10}
```

BERT uses the Wordpiece tokenizer where the original token can be linked to the tokenized tokens (e.g., for Dima, the tokenized tokens are dim and ##a). Therefore, we can re-annotated the tokenized tokens using the methods mentioned in the #64. 

However, I did not see an easy way to link the original token to the BPE tokenized tokens. There is no clear indicator of the token boundaries. Without resolving this issue, it is almost impossible to perform NER since all the annotations are at the token-level.

**Comment by thomwolf** [comment]
Not yet indeed, do you want to submit a PR copying these models from Bert?

**Comment by dataframing** [comment]
@thomwolf is this something the team is open to reviewing? I can open a PR that (ambitiously?) adds both `RobertaForTokenClassification` and `TFRobertaForTokenClassification` in the next few days/week.

**Comment by thomwolf** [comment]
Yes, sure (though I won't commit to a specific delay for reviewing hahaha).

Adding `RobertaForTokenClassification` and `TFRobertaForTokenClassification` should be very simple and basically kept as a copy-past from Bert similar models.

The most important here is actually to finish the PR adding token-to-string-character mappings (#1274 by @michaelrglass) so we can translate NER labels to token labels for training. Though I think there may also be a simpler way to do that by modifying RoBERTa/GPT-2 tokenizers to accept tokenized word but this require some knowledge of the internal functioning of GPT-2 tokenizer.

**Comment by mmaybeno** [comment]
Created a PR and looking for feedback. Hoping to jump on the `run_ner.py` script as well tonight/tomorrow.

**Comment by mmaybeno** [comment]
This was done and probably should be closed.
