### ISSUE TITLE
KeyError: 'bigbird_pegasus'

### ISSUE THREAD

**Issue by loretoparisi** [huggingface/transformers#11668]
## Environment info

- `transformers` version: 4.6.0.dev0
- Platform: Linux-5.10.25-linuxkit-x86_64-with-debian-10.1
- Python version: 3.7.4
- PyTorch version (GPU?): 1.8.1+cu102 (False)
- Tensorflow version (GPU?): 2.4.1 (False)
- Using GPU in script?: (False)
- Using distributed or parallel set-up in script?: none

### Who can help
@patrickvonplaten 

## Information

Model I am using (Bert, XLNet ...): `google/bigbird-pegasus-large-arxiv`

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [X] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce
```python
mport os
import torch
from datasets import load_dataset
from transformers import pipeline
from transformers import AutoTokenizer, AutoModel

dataset = load_dataset("patrickvonplaten/scientific_papers_dummy", "arxiv",
    cache_dir=os.getenv("cache_dir", "../../models"))
paper = dataset["validation"]["article"][1]

tokenizer = AutoTokenizer.from_pretrained(
    'google/bigbird-pegasus-large-arxiv',
    cache_dir=os.getenv("cache_dir", "../../models"))
model = AutoModel.from_pretrained(
    'google/bigbird-pegasus-large-arxiv',
    cache_dir=os.getenv("cache_dir", "../../models"))

summarizer = pipeline(
    'summarization',
    model=model,
    tokenizer=tokenizer)
```

1. Run the provided script
2. output:

```
2021-05-10 17:11:53.523744: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-10 17:11:53.523858: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Reusing dataset scientific_papers (models/scientific_papers/arxiv/1.1.1/051d70b9811c81480cbf2a238b499f7713ba4e19acdaeeb92320007d68b6d098)
Traceback (most recent call last):
  File "src/bigbird/run.py", line 17, in <module>
    cache_dir=os.getenv("cache_dir", "../../models"))
  File "/usr/local/lib/python3.7/site-packages/transformers/models/auto/tokenization_auto.py", line 398, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/transformers/models/auto/configuration_auto.py", line 421, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
KeyError: 'bigbird_pegasus'
```

I have also tried this import

```python
from transformers import BigBirdPegasusForConditionalGeneration, BigBirdPegasusTokenizer
```

as described in the docs [here](https://huggingface.co/google/bigbird-pegasus-large-arxiv), but in this case I get another error:

```
    from transformers import BigBirdPegasusForConditionalGeneration, BigBirdPegasusTokenizer
ImportError: cannot import name 'BigBirdPegasusForConditionalGeneration' from 'transformers' (unknown location)
```

## Expected behavior

no error

**Comment by loretoparisi** [comment]
@vasudevgupta7 thank you it worked, they was `pip3 uninstall transformers`.

**Comment by loretoparisi** [comment]
@vasudevgupta7 sorry, a bit confused with the masked model:

```python
# by default its in `block_sparse` mode with num_random_blocks=3, block_size=64
model = BigBirdModel.from_pretrained("google/bigbird-roberta-large", 
    block_size=64, 
    num_random_blocks=3,
    cache_dir=os.getenv("cache_dir", "../../models"))
tokenizer = AutoTokenizer.from_pretrained("google/bigbird-pegasus-large-arxiv",
    cache_dir=os.getenv("cache_dir", "../../models"))

text = "Paris is the [MASK] of France."
encoded_input = tokenizer(text, return_tensors='pt')
output = model(**encoded_input)
print(output)
decoded = tokenizer.decode(tokenizer.convert_tokens_to_ids(output))
print(decoded)
```

right way to decode model's output?

**Comment by patrickvonplaten** [comment]
@loretoparisi, you are using a `BigBird Roberta` model as the model and `BigBird Pegagus` as the tokenizer -> those are two different checkpoints.

Also, it would be very nice if you could use the [forum](https://discuss.huggingface.co/) for "How to do ...." questions as we try to keep the github issues for actual issues with the models. Thank you :-)

**Comment by loretoparisi** [comment]
@patrickvonplaten typo in the code thanks

**Comment by JiXiang-Zhou** [comment]
I have the same problem
I tried the code 
`pip3 uninstall transformers
pip3 install git+https://github.com/huggingface/transformers@master`
and then get
`Collecting git+https://github.com/huggingface/transformers@master
  Cloning https://github.com/huggingface/transformers (to revision master) to /private/var/folders/td/7w3k7h8939l86zcjhwk056th0000gn/T/pip-req-build-y_nmf265
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers /private/var/folders/td/7w3k7h8939l86zcjhwk056th0000gn/T/pip-req-build-y_nmf265
  WARNING: Did not find branch or tag 'master', assuming revision or ref.
  Running command git checkout -q master
  error: pathspec 'master' did not match any file(s) known to git
  error: subprocess-exited-with-error
  
  × git checkout -q master did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git checkout -q master did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

After running the code, the problem is still there

**Comment by JiXiang-Zhou** [comment]
I have the same problem
I tried the code
pip3 uninstall transformers pip3 install git+https://github.com/huggingface/transformers@master
and then get
"
WARNING: Did not find branch or tag 'master', assuming revision or ref.
Running command git checkout -q master
error: pathspec 'master' did not match any file(s) known to git
error: subprocess-exited-with-error

× git checkout -q master did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git checkout -q master did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip."

After running the code, the problem is still there

**Comment by JiXiang-Zhou** [comment]
I have the same problem
I tried the code
'pip3 uninstall transformers pip3 install git+https://github.com/huggingface/transformers@master'
and then get

```
WARNING: Did not find branch or tag 'master', assuming revision or ref.
Running command git checkout -q master
error: pathspec 'master' did not match any file(s) known to git
error: subprocess-exited-with-error

× git checkout -q master did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git checkout -q master did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

After running the code, the problem is still there

**Comment by JiXiang-Zhou** [comment]
> Hey @loretoparisi,
> 
> It's working perfectly for me when running this:
> 
> ```shell
> pip3 uninstall transformers
> pip3 install git+https://github.com/huggingface/transformers@master
> ```
> 
> ```python
> from transformers import BigBirdPegasusForConditionalGeneration, AutoTokenizer, AutoModelForSeq2SeqLM
> model = AutoModelForSeq2SeqLM.from_pretrained("google/bigbird-pegasus-large-arxiv")
> # or
> model = BigBirdPegasusForConditionalGeneration.from_pretrained("google/bigbird-pegasus-large-arxiv")
> 
> tokenizer = AutoTokenizer.from_pretrained("google/bigbird-pegasus-large-arxiv")
> ```
> 
> BigBird pegasus is not having `BigBirdPegasusTokenizer` so use `AutoTokenizer` only.


I have the same problem
I tried the code
`pip3 uninstall transformers pip3 install git+https://github.com/huggingface/transformers@master`
and then get

```
WARNING: Did not find branch or tag 'master', assuming revision or ref.
Running command git checkout -q master
error: pathspec 'master' did not match any file(s) known to git
error: subprocess-exited-with-error

× git checkout -q master did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git checkout -q master did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
After running the code, the problem is still there

**Comment by JiXiang-Zhou** [comment]
Relaunch my notebook, problem solved 😐
