### ISSUE TITLE
Hugging Face model Bio_ClinicalBERT producing 404 error

### ISSUE THREAD

**Issue by NicoleJaneway** [huggingface/transformers#11823]
I'm building a Named Entity Recognition (NER) model using the Hugging Face implementation of emilyalsentzer/Bio_ClinicalBERT. Up to today, I've had no issues with the model. Today it's not working as expected.

Question 1 - today, trying to train using:

MODEL_NAME = 'emilyalsentzer/Bio_ClinicalBERT'
model = text.sequence_tagger('bilstm-bert', preproc, bert_model=MODEL_NAME)
results in this error: 404 Client Error: Not Found for url: https://huggingface.co/emilyalsentzer/Bio_ClinicalBERT/resolve/main/tf_model.h5

Does Hugging Face offer any kind of health check to ascertain the status of their models?

Question 2 - working with files (model.h5, model.json, and preproc.sav) I'd saved from earlier training iterations, I'm getting the same 404 error shown above. I don't understand wherein these files the call to Hugging Face is occurring. It doesn't seem to be in the .json, and the .h5 and .sav file formats are hard to inspect. Read more about what these files are: https://medium.com/analytics-vidhya/how-to-deploy-your-neural-network-model-using-ktrain-ae255b134c77

Back in February, I'd used these exact model.h5, model.json, and preproc.sav files to run the NER app using Streamlit, no problem. Not sure if this is temporary issue with Bio_ClinicalBERT or if I need to retool my original approach due to potentially permanent problems with this transformer model.

**Comment by stefan-it** [comment]
Hi @NicoleJaneway ,

I think this issue is similar to the following one in `ktrain` repo:

https://github.com/amaiya/ktrain/issues/367

"Problem" is, that there's no TensorFlow compatible model found on the hub (more precisely the `tf_model.h5` one). One good "workaround" would be if the model owner (pinging @EmilyAlsentzer here) would upload such a model to avoid these message :hugs:

**Comment by NicoleJaneway** [comment]
Thanks, @stefan-it!  Unfortunately, with the 404 error, my app is no longer working.  I posted a new [ktrain issue](https://github.com/amaiya/ktrain/issues/369) about it.  In my experience, the creator has been amazingly responsive, so let's see what comes of the question.

**Comment by LysandreJik** [comment]
Hello @NicoleJaneway, looking at the repository and its commit history, I don't think there ever was a `.h5` file uploaded.

Could you share the code you're using when using local files so that we can see what's going on? If using local files, `transformers` should look locally before looking on the server, so you shouldn't get a 404 error

**Comment by NicoleJaneway** [comment]
Hey @LysandreJik, thanks for trying to help - I don't have this project up on a public github yet.  I'll let you know when I do.
