### ISSUE TITLE
Module torch has no attribute minimum for modeling_big_bird.py

### ISSUE THREAD

**Issue by robinsongh381** [huggingface/transformers#11837]
Hello

I came across `module 'torch' has no attribute minimum` from the following two lines 

1.https://github.com/huggingface/transformers/blob/73fde1defe9be259a47b9024525882f3ec420994/src/transformers/models/big_bird/modeling_big_bird.py#L662

2.https://github.com/huggingface/transformers/blob/73fde1defe9be259a47b9024525882f3ec420994/src/transformers/models/big_bird/modeling_big_bird.py#L796

I think `torch.minimum` should be replaced with `torch.min`

**Comment by NielsRogge** [comment]
`torch.minimum` was only added in August 2020 to PyTorch, so `torch.minimum` is probably only part of torch 1.7+. To work for previous versions, it should indeed be replaced by `torch.min`.

The README of this repository states that: "This repository is tested on Python 3.6+, Flax 0.3.2+, PyTorch 1.3.1+ and TensorFlow 2.3+." 

cc @vasudevgupta

**Comment by vvalouch** [comment]
This bug is making it impossible to use BigBird in combination with AWS HuggingFace setup as that one is currently restricted to Pytorch 1.6. (https://huggingface.co/blog/the-partnership-amazon-sagemaker-and-hugging-face) Are there any plans to fix the modeling_big_bird.py so that it is backward compatible or agree with AWS on support of never version of Pytorch for HuggingFace containers?
