### ISSUE TITLE
Wrong subword aggregation when using aggregation_strategy

### ISSUE THREAD

**Issue by Guidofaassen** [huggingface/transformers#11887]
## Environment info
- `transformers` version: 4.7.0.dev0
- Platform: Windows
- Python version: 3.9.4
- PyTorch version (GPU?): No
- Tensorflow version (GPU?): No
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
@Narsil 
@francescorubbo 
@elk-cloner 

## Information

xlm-roberta-large-finetuned-conll02-dutch

The problem arises when using aggregation_strategy.

## To reproduce

Given this code:
```sentence = "Groenlinks praat over Schiphol."
nlp = pipeline('ner', model='xlm-roberta-large-finetuned-conll02-dutch')
nlp(sentence)
```

I get the following result:

```
[{'entity': 'B-ORG',
  'score': 0.9769433,
  'index': 1,
  'word': '▁Groen',
  'start': 0,
  'end': 5},
 {'entity': 'I-ORG',
  'score': 0.9935022,
  'index': 2,
  'word': 'link',
  'start': 5,
  'end': 9},
 {'entity': 'B-LOC',
  'score': 0.9999288,
  'index': 6,
  'word': '▁Schi',
  'start': 22,
  'end': 26},
 {'entity': 'I-LOC',
  'score': 0.99987257,
  'index': 8,
  'word': 'hol',
  'start': 27,
  'end': 30}]
```

We received subwords, where I would prefer to have real words. I found that `aggregation_strategy` was added in the latest release (master branch, 4.7.0.dev0). In an attempt to fix this, I tried this:

```
sentence = "Groenlinks praat over Schiphol."
nlp = pipeline('ner', model='xlm-roberta-large-finetuned-conll02-dutch', aggregation_strategy="max")
nlp(sentence)
```

Which yields:

```
[{'entity_group': 'ORG',
  'score': 0.98522276,
  'word': 'Groenlink',
  'start': 0,
  'end': 9},
 {'entity_group': 'LOC',
  'score': 0.99987257,
  'word': 'hol',
  'start': 27,
  'end': 30}]
```

## Expected behavior

This is different than expected, as subwords are merged in the wrong way. `Groenlink` and `hol` were both not part of the original sentence. I would expect this:

```
[{'entity_group': 'ORG',
  'score': 0.98522276,
  'word': 'Groenlinks',
  'start': 0,
  'end': 9},
 {'entity_group': 'LOC',
  'score': 0.99987257,
  'word': 'Schiphol',
  'start': 27,
  'end': 30}]
```

Do you have any clues how to fix this?

**Comment by francescorubbo** [comment]
I suspect we might have an issue recognizing subwords when using the BPE tokenizer.
Using a BERT based model works as expected:
```
>> nlp = transformers.pipeline('ner', model='wietsedv/bert-base-dutch-cased-finetuned-conll2002-ner', aggregation_strategy='first')
>> nlp("Groenlinks praat over Schiphol.")
[{'entity_group': 'org',
  'score': 0.99999315,
  'word': 'Groenlinks',
  'start': 0,
  'end': 10},
 {'entity_group': 'loc',
  'score': 0.9999975,
  'word': 'Schiphol',
  'start': 22,
  'end': 30}]
```

I'll take a closer look at the logic when using BPE sub-tokens and report back.

**Comment by francescorubbo** [comment]
@LysandreJik @sgugger The problem is how we decide whether or not a token is a subword [here](https://github.com/huggingface/transformers/blob/master/src/transformers/pipelines/token_classification.py#L273),
where we compare the token length with the corresponding span in the original text.
For WordPiece this works because `Groenlinks` is tokenized as `['Groen', '##link', '##s']`, so the last two tokens are tagged as subwords. However BPE tokenizes as `['_Groen', 'link', 's']`, so we incorrectly tag `_Groen` as subword and the other two tokens as words.

**Comment by LysandreJik** [comment]
Similar to https://github.com/huggingface/transformers/issues/11794

**Comment by Guidofaassen** [comment]
Any update on this issue?

**Comment by NielsRogge** [comment]
@francescorubbo thanks for investigating this. So the `gather_pre_entities` function of the NER pipeline needs an update to also work with BPE tokenizers. 

For WordPiece tokenizers, a token is a subword if it starts with ##. For BPE tokenizers, a token is a subword if it doesn't start with _. Is that correct?

cc @Narsil 

Mind opening a PR to support BPE tokenizers?

**Comment by Narsil** [comment]
I think the problem is tricky, I don't think it is properly linked to BPE, but more for tokenizers that are word aware vs not.

Right now, we use tokenizers that use `continuing_subword_prefix` to determine if a token is a subword.
I don't think there is a "correct" way to do that with byte level BPE like gpt2 (roberta) as they don't posess the notion of "word".

As mentioned in a previous issue, if we can find a good heuristic that would be great, but byte BPE can :
- have space as a prefix or suffix 
- use a different char than ' '  for space (_ for spm, `G for gpt2)

So classifying subwords for these tokenizers is always going to be tricky. We could however disable "word"-based strategies for tokenizers that do no provide "continuing_subword_prefix". It would be more correct (but less usable for sure)

**Comment by Guidofaassen** [comment]
I result is still incorrect after the new changes @Narsil.

Given the nightly build: '4.10.0.dev0'

With given code

```
nlp = pipeline('ner', model='xlm-roberta-large-finetuned-conll02-dutch', grouped_entities=True)
sentence = "Groenlinks praat over Schiphol."
nlp(sentence)
```

yields

```
[{'entity_group': 'ORG',
  'score': 0.98522276,
  'word': 'Groenlink',
  'start': 0,
  'end': 9},
 {'entity_group': 'LOC',
  'score': 0.9999288,
  'word': 'Schi',
  'start': 22,
  'end': 26},
 {'entity_group': 'LOC',
  'score': 0.99987257,
  'word': 'hol',
  'start': 27,
  'end': 30}]
```

The subwords are still not merged correctly as the found entities do not exist in the original text. I also tried setting `aggregation_strategy=AggregationStrategy.SIMPLE`, but that did not help either. Am I doing something wrong?
