### ISSUE TITLE
Adding new Jax Models.

### ISSUE THREAD

**Issue by jayendra13** [huggingface/transformers#11881]
Is there any board to track that how many current models have jax implementation ?
I would like to contribute to add jax implementation for the remaining ones, which model I can take to start ?

**Comment by patil-suraj** [comment]
Hi there, thank you for your interest in JAX.

We plan to add as many models as possible in JAX/Flax. Right now we are working on improving the JAX support in the lib, better JAX/Flax tests, cookie-cutter templates etc so that it'll become easier to add more models faster.

Please stay tuned, we'll soon share more details :)
