### ISSUE TITLE
What is the correct way to pass labels to DetrForSegmentation?

### ISSUE THREAD

**Issue by nateraw** [huggingface/transformers#12105]
The [current documentation](https://huggingface.co/transformers/master/model_doc/detr.html#transformers.DetrForSegmentation.forward) for `DetrModelForSegmentation.forward` says the following about `labels` kwarg:

> The class labels themselves should be a torch.LongTensor of len (number of bounding boxes in the image,), the boxes a torch.FloatTensor of shape (number of bounding boxes in the image, 4) and the **masks a torch.FloatTensor of shape (number of bounding boxes in the image, 4).**

But when I looked at the tests, it seems the shape of `masks` is `torch.rand(self.n_targets, self.min_size, self.max_size)` . 

https://github.com/huggingface/transformers/blob/d2753dcbec7123500c1a84a7c2143a79e74df48f/tests/test_modeling_detr.py#L87-L103

---

I'm guessing this is a documentation mixup!

Anyways, it would be super helpful to include a snippet in the DETR docs that shows how to correctly pass masks/other labels + get the loss/loss dict. 😄 

CC: @NielsRogge

**Comment by NielsRogge** [comment]
Thanks for noticing, that's a mistake. The masks needs to be torch.FloatTensor of shape (number of bounding boxes in the image, height, width) - with height and width equal to those of the `pixel_values`. 

Note that predicting boxes is required for the training to be possible, since the Hungarian matching is computed using distances between boxes.

However, I've got no less than 5 notebooks coming up that illustrate how to use DETR ;) 

I will fix this docs issue, together with some other small improvements, in a PR.

**Comment by nateraw** [comment]
No worries! I got it working after this. Training is a bit finicky though 😅. Looking forward to those notebooks!!
