### ISSUE TITLE
KnowBert

### ISSUE THREAD

**Issue by rishibommasani** [huggingface/transformers#1247]
As has amazingly and remarkably become a standard response to a new model announcement, will this new transformer model be implemented:
https://arxiv.org/pdf/1909.04164.pdf - KnowBert at EMNLP19.

**Comment by rishibommasani** [comment]
Yes, looking into if they are releasing pretrained weights, I incorrectly assumed they were.

**Comment by adai183** [comment]
Wow! Really looking forward to this.
I really feel that models that combine text and unstructured data are not getting enough attention.
This is so relevant for creating great AI products because I dare to say that in most real life applications you do not deal with text only data. Metadata is crucial!

**Comment by sarwar187** [comment]
The authors released the model. Any update on integrating it into huggingface?

**Comment by julien-c** [comment]
We'd welcome a community or author-contributed implementation! 

(Also might look into integrating it ourselves at some point, but bandwidth is low)
