### ISSUE TITLE
Issue in terms of accuracy of onnx converted models of SQUAD based ROBERTA  on legal domain.

### ISSUE THREAD

**Issue by kingafy** [huggingface/transformers#12563]
Hi Team,

I was using the  hugging face utility from latest transformer version to convert a SQUAD based Roberta model  to ONNX. After conversion, I observed the accuracy has dipped significantly even though I never quantized the model. Any suggestions or advice what could have been the reason. Does the ONNX conversion results in loss in terms of predictions? If so, is there any parameter which can be experimented with to reduce and yet improve the run time performance.

**Comment by LysandreJik** [comment]
Hello, thanks for opening an issue! We try to keep the github issues for bugs/feature requests.
Could you ask your question on the [forum](https://discuss.huggingface.co) instead?

If you'd like us to investigate this as a bug, please provide additional information so that we may help; for example, the ID of a pretrained model on the hub that loses accuracy when being converted, the commands run, the environment, library version.

Thanks!
