### ISSUE TITLE
Too Many kernels and embeddings were randomly initialized when loading Hugging Face GPT-2 Model

### ISSUE THREAD

**Issue by vivekvkashyap** [huggingface/transformers#12673]
## Environment info

- `transformers` version:
- Platform:colab
- Jax version (CPU):0.2.13
- Using GPU in script?:No
- Using distributed or parallel set-up in script?:No

### Who can help
@patrickvonplaten @patil-suraj 

Models:
Used hugging face GPT2 model for multiple choice task.

Examples:
```python
self.gpt2=FlaxGPT2Model(config=self.config, dtype=self.dtype)
```

## Information

Model I am using GPT2:

The problem arises when using:
*loading the model

The tasks I am working on is:
* mutliple choice
* dataset:COSMOS

## To reproduce

https://colab.research.google.com/drive/1uTwJ1X1WTxOTDSduKqoUTg3oizehPFJB?usp=sharing

While executing this command:
```python
model = FlaxGPT2ForMultipleChoice.from_pretrained('gpt2')
```
## Expected behavior

To run the following code without any warnings and randomly initialized kernels.

**Comment by patil-suraj** [comment]
Hi, this is because you are using a different base model prefix `self.gpt2` to load the base model. To be able to add any heads and still be able to load the base model weights the pre-trained class expects the base model to have the same prefix.

For gpt2 it is `self.transformer`, changing `self.gpt2` to `self.transformer` should fix this.

Also, try to avoid posting screen-shots, it's usually better for us, if you post the warning/stack-trace as text. Thanks!
