### ISSUE TITLE
 You must login to the Hugging Face hub on this computer by typing `transformers-cli login` and entering your credentials to use `use_auth_token=True`. Alternatively, you can pass your own token as the `use_auth_token` argument in the translation notebook.

### ISSUE THREAD

**Issue by Azitt** [huggingface/transformers#13124]
I'm trying to run the following but gives me this error. I made an account and login but am not sure about `transformers-cli login`. any help would be appreciated.
![image](https://user-images.githubusercontent.com/32965166/129429037-5909f09d-4bfd-4dd7-870e-eb07e32b34bf.png)

## Environment info

- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by NielsRogge** [comment]
In order to be able to push to model to the hub after training, make sure to follow these steps:

Add the following arguments to TrainingArguments:
push_to_hub=True,
push_to_hub_token="..."

=> your token can be found on huggingface.co, click on the top-right for your account, and then click "edit profile" and "API tokens". You can then pass that API token to the push_to_hub_token argument.

Also, make sure git lfs is installed. In Colab, you can do this as follows:

!sudo apt-get install git-lfs
!git config --global user.email "your email address"
# Tip: using the same email than for your huggingface.co account will link your commits to your profile
!git config --global user.name "your username"

**Comment by Azitt** [comment]
Thank you!
