### ISSUE TITLE
LEDForSequenceClassification example throws a ValueError on missing decoder_input_ids/embeds

### ISSUE THREAD

**Issue by alceausu** [huggingface/transformers#13669]
## Environment info

- `transformers` version: 4.9.0
- Python version: 3.8.10
- PyTorch version (GPU?): 1.9.0

### Who can help
@patrickvonplaten @beltagy 

## Information

LEDForSequenceClassification example throws an error on line 207 of modeling_led.py:
```
ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds
```

## To reproduce

Run the code from the documentation of [LEDForSequenceClassification](https://huggingface.co/transformers/model_doc/led.html#ledforsequenceclassification)
```
>>> from transformers import LEDTokenizer, LEDForSequenceClassification
>>> import torch

>>> tokenizer = LEDTokenizer.from_pretrained('allenai/led-base-16384')
>>> model = LEDForSequenceClassification.from_pretrained('allenai/led-base-16384')

>>> inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")
>>> labels = torch.tensor([1]).unsqueeze(0)  # Batch size 1
>>> outputs = model(**inputs, labels=labels)
>>> loss = outputs.loss
>>> logits = outputs.logits
```

**Comment by alceausu** [comment]
The same example in [BartForSequenceClassification](https://huggingface.co/transformers/model_doc/bart.html#bartforsequenceclassification) works just fine.

**Comment by patrickvonplaten** [comment]
Yes, however this is simply because BART can automatically generate `decoder_input_ids` for training: https://arxiv.org/abs/1910.13461 this would never be used for a downstream task even for BART. E.g. See this comment: https://github.com/huggingface/transformers/blob/a3ded170e22b37027dab456a12ff2f523c99d998/src/transformers/models/bart/modeling_bart.py#L594. Now LED was never pretrained from scratch and therefore there is no use case where the `decoder_input_ids` should **not** be provided. See comment here: https://github.com/huggingface/transformers/blob/a3ded170e22b37027dab456a12ff2f523c99d998/src/transformers/models/led/modeling_led.py#L1510 for comparison. => In LED we should always provide the `decoder_input_ids` in the forward pass
