### ISSUE TITLE
input decoder embedding for model.generate()

### ISSUE THREAD

**Issue by amy-hyunji** [huggingface/transformers#13917]
Hi, I'm using T5 model and is trying to generate a sentence using model.generate(). 
However, rather than using `decoder_input_ids` which gives the input_ids for the decoder part of T5, I would like to give a specific embedding I have to the decoder. Is there any way I can give specific decoder input embedding to model.generate()?

I noticed that in T5 model, I can give the embedding by `decoder_inputs_embeds`. Does this work in model.generate() too?

thanks :)

**Comment by aaafc** [comment]
Hi there, 
I've also encountered the problem myself, while I've attempted to use GPT causal model instead of Google T5 as my base model. 

I was meant to use beam search for next sentence generation, while adding some self-defined vectors as prefix (which are not inside the embeddings).

While tests on self-implemented algorithms is successful in predicting the sentence, the method is tremendously slow compared to encapsulated method `model.generate()`. But a change to the method generate() shows several error, for `input_ids` is a required parameter, while I was trying to use the concatenated embedding vector as input.

The source doc shows that **model_kwargs will check for external parameter `inputs_embeds`: 
`if input_ids is None and "inputs_embeds" not in model_kwargs:`
but even if I inserted the parameter, the method will still check for `input_ids`, and throw out an error for there's no "input_ids" in input parameters.

**Comment by amy-hyunji** [comment]
@aaafc Hi, Thanks for sharing the issue. 

I looked through the codes in `generation_utils.py` and also noticed the same problem. Though we pass `decoder_inputs_embeds` in the `model.generate()`, `model_inputs` in https://github.com/huggingface/transformers/blob/2024faf1713272464336ad97f371787b24cb3c53/src/transformers/generation_utils.py#L1785 doesn't contain the argument. 

I could partially solve the issue by separating the case where `decoder_inputs_embeds` value is passed or not
```
if decoder_inputs_embeds is None:
            outputs = self(
                **model_inputs,
                return_dict=True,
                output_attentions=output_attentions,
                output_hidden_states=output_hidden_states,
            )
else:
           del model_inputs['decoder_input_ids'] # this is to make sure that dependency exists in decoder_inputs_embeds. May not be necessary
            outputs = self( 
                **model_inputs,
                decoder_inputs_embeds=decoder_inputs_embeds
                return_dict=True,
                output_attentions=output_attentions,
                output_hidden_states=output_hidden_states,
            )
```

However, the issue still exists in that the last part of the process where the embeddings change to ids and are passed on to the next iteration by adding into input_ids. (https://github.com/huggingface/transformers/blob/2024faf1713272464336ad97f371787b24cb3c53/src/transformers/generation_utils.py#L1851) This part should also be changed to a separate case where it is passed by ***ids*** or ***embeds***. I'm still working on how to change the whole iteration process by adding and passing the embedding rather than ids. 
It would be helpful if you leave any ideas or suggestions on this :)

**Comment by amy-hyunji** [comment]
Thanks for pointing out more issues. I do agree that when it goes to beam search, things are going to be more complicated so I started off from greedy_search. 

For the part about 
https://github.com/huggingface/transformers/blob/9eda0d156dcf34203e3f7ea5ad220c960fd3227b/src/transformers/generation_utils.py#L1806
based on my understanding, I believe there won't be any problem since by giving `decoder_inputs_embeds` to the model, we are simply expecting the model to generate the next token based on the embeddings and don't expect this to modify any part about the logits_processor which will work based on the `input_ids` that is generated by the model *based* on the given embeddings. However, this won't be an appropriate solution if you want the input embedding (decoder_inputs_embeds) to be converted into the most likely ids and return the value by `model.generate()` function. 

Also, I agree that overwriting `prepare_inputs_for_generration` is one of the solutions! :)

**Comment by patrickvonplaten** [comment]
This should have been solved by https://github.com/huggingface/transformers/pull/14443 I think :-)
