### ISSUE TITLE
Enabling Discussion on github

### ISSUE THREAD

**Issue by sadakmed** [huggingface/transformers#14039]
# 🚀 Feature request

Enabling Discussion on github 

## Motivation

reserve issues for only feature request, bugs (anything that would be an addition to the transformers library). While, discussion will be for guidance and questions.
I know that this is the use of [discuss huggingface](https://discuss.huggingface.co/c/transformers/9). However, I think large portion of users interact just from github, it makes sense to have issues not include general question and guidance (**false issues**) and you as transformers maintainers will relate to the amount of notifications from it.

**Comment by pratikchhapolika** [comment]
Good idea!!

**Comment by LysandreJik** [comment]
Hello @sadakmed, thank you for your proposal! As you have mentioned, we have a forum that is already active. Rather than opening a new communication channel that would split interaction between the forum and the GitHub discussions, we'd rather stay focused on having only the forum.

Does that make sense?

cc @sgugger

**Comment by sgugger** [comment]
Yes, we do not want to duplicate the communication channels and I think it would just be too confusing for everyone to have the same discussions in two different places. The forums via Discourse were chosen as they are ultimately better integrated with the rest of the Hugging Face website and model Hub (same login, easy going from one to the other) whereas the Discussions on GitHub did not offer that feature.
