### ISSUE TITLE
How to install transformers with pytorch only?

### ISSUE THREAD

**Issue by littlethunder** [huggingface/transformers#1416]
## ❓ Questions & Help
Hi! Pytorch1.0 is installed and I'm installing the transformers with pip, everything is fine. But when I try:
```
import torch
from transformers import BertModel
```
then, an error occurred:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pc/miniconda3/lib/python3.7/site-packages/transformers/__init__.py", line 20, in <module>
    from .file_utils import (TRANSFORMERS_CACHE, PYTORCH_TRANSFORMERS_CACHE, PYTORCH_PRETRAINED_BERT_CACHE,
  File "/home/pc/miniconda3/lib/python3.7/site-packages/transformers/file_utils.py", line 30, in <module>
    assert int(tf.__version__[0]) >= 2
AttributeError: module 'tensorflow' has no attribute '__version__'
```

It seems like it cannot work unless both the tensorflow and pytorch have been installed, is that right? And is there a way to run transformers with pytorch only? (I don't want to install tensorflow)

Thanks in advance!

**Comment by LysandreJik** [comment]
Hi! No, you should be able to import every torch-related model without having TensorFlow installed. 

As I understand it, our method for identifying if you had TensorFlow 2.0 installed broke because the TensorFlow version you have in your environment does not have the attribute `__version__`.

Could you provide the TensorFlow version you have installed so that we may patch this bug? In the meantime, uninstalling TensorFlow from this environment or creating a new environment without this TensorFlow version should work fine. Thanks.

**Comment by littlethunder** [comment]
Thanks a lot! Now I got it, I think there is something wrong with my miniconda, because there is a build-in incomplete tensorflow, which has no version, no functions,...nothing but a box. My conda version is 4.7.11. As I cannot uninstall the incomplete version of tensorflow, I just install the latest tensorflow and leave it there, not it works fine with pytorch. Cheers!
