### ISSUE TITLE
How to prevent tokenizer from outputting certain information

### ISSUE THREAD

**Issue by wmathor** [huggingface/transformers#14285]
```
Be aware, overflowing tokens are not returned for the setting you have chosen, i.e. sequence pairs with the 'longest_first' truncation strategy. So the returned list will always be empty even if some tokens have been removed.
```

**Comment by MoritzLaurer** [comment]
I'm also slightly confused by the warning. If I'm reading the source code correctly, this is really only a warning and is not triggered if there is an actual issue. It's slightly confusing because you get it many times when you tokenize a lot of text and it feels like there is something wrong. Maybe it can just be returned once?
https://github.com/huggingface/transformers/blob/master/src/transformers/tokenization_utils_base.py

**Comment by wmathor** [comment]
> I'm also slightly confused by the warning. If I'm reading the source code correctly, this is really only a warning and is not triggered if there is an actual issue. It's slightly confusing because you get it many times when you tokenize a lot of text and it feels like there is something wrong. Maybe it can just be returned once?
> https://github.com/huggingface/transformers/blob/master/src/transformers/tokenization_utils_base.py

I try to modify the source code of `tokenization_utils_base.py`, delete the warning code segment. It works!

**Comment by eduOS** [comment]
Set the verbosity level as follows: 

> transformers.logging.set_verbosity_error()

**Comment by wmathor** [comment]
> Set the verbosity level as follows:
> 
> ` transformers.logging.set_verbosity_error()`

thank you so much!

**Comment by nreimers** [comment]
I'm using the Trainer class with a dataset that I stream (as it is too large) and perform on-the-fly tokenization (i.e. each mini-batch is passed to the tokenizer). Sadly this warning appears constantly with every mini-batch which is quite annoying. 

Sadly `transformers.logging.set_verbosity_error()` doesn't work in the multi-process setup (I use the trainer with multiple GPUs). Also it removes logs from the trainer that are quite relevant / interesting. 

Would be great if this warning could be removed / or changed so that it is only printed once.

**Comment by LysandreJik** [comment]
Indeed, it could be done by using the following variable: 

https://github.com/huggingface/transformers/blob/68810aa26c083fd97d976cef7ac65fdd9cc9b520/src/transformers/tokenization_utils_base.py#L1462-L1464

You can see an example of it used here:

https://github.com/huggingface/transformers/blob/68810aa26c083fd97d976cef7ac65fdd9cc9b520/src/transformers/tokenization_utils_base.py#L1486-L1490

Feel free to open a PR to offer this change!

**Comment by nreimers** [comment]
Thanks for the pointer @LysandreJik 

Will create a PR on this

**Comment by lextoumbourou** [comment]
Hi HuggingFace, I'm a bit fan of all you do! Please reconsider your approaches to warnings. Can we just put things in the documentation instead of the incessant warning spam?

![image](https://user-images.githubusercontent.com/1080552/175750347-9e19907b-eb9f-46d6-a3c7-92841516f02f.png)

For anyone coming from Google, this is the only way I've found to successfully suppress HuggingFace warnings:

```
import logging
logging.disable(logging.WARNING)
```

`transformers.logging.set_verbosity_error()` didn't work for me.

**Comment by heya5** [comment]
I'm just confused by this sentence in the warning
>  **So the returned list will always be empty** even if some tokens have been removed.
Does it mean I will get a empty returned list ??

**Comment by Larleyt** [comment]
I upvote for the last message. I've started getting this error when was using tokenizer with `text_pair` (context) argument.
And after that I've tried to decode messages and... have got a 2/3 of them empty. Why? How to prevent that? It was ok without `text_pair` arg.
