### ISSUE TITLE
LED models give: `IndexError: index out of range in self`

### ISSUE THREAD

**Issue by nicola-decao** [huggingface/transformers#14312]
Using a Longformer on more an input with than 1024 tokens doesn't seem to work. But it should as the Longformer was specifically designed to handle up to 16k tokens as input. See the code below.

To reproduce:
```python
from transformers import LEDTokenizer, LEDForConditionalGeneration
  
tokenizer = LEDTokenizer.from_pretrained("allenai/led-base-16384")
model = LEDForConditionalGeneration.from_pretrained("allenai/led-base-16384")

# this works (tokens < 1024)
model(**tokenizer("hello " * 120, return_tensors="pt"))

# this does not work! (tokens > 1024)
model(**tokenizer("hello " * 1200, return_tensors="pt"))
```

Versions:
* python 3.8.11
* pytorch 1.11.0.dev20210928+cu111
* transformers 4.11.0

**Comment by LysandreJik** [comment]
cc @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Hey @nicola-decao,

That's a great issue! The problem here is the following:

1. The forward pass of encoder-decoder models expects both `input_ids` (for the encoder) and `decoder_input_ids` (for the decoder). Now since LED was derived from BART, the logic of automatically generating `decoder_input_ids` from `input_ids` is kept which was used for BART for pre-training. This means that if you do `model(input_ids)` than `decoder_input_ids` is not provided and thus automatically created by shifting `input_ids`.

2. LED can handle up to 16K `input_ids` tokens, but **not** 16K `decoder_input_ids` tokens. The idea of LED was really to be able to process very long inputs (articles to summarize) with the assumption that the decoder outputs don't have to be very long (summaries). There can be at most 1024 `decoder_input_ids` tokens which is violated if `1200` tokens are automatically generated.

This being said the following example should work:

```python
from transformers import LEDTokenizer, LEDForConditionalGeneration
  
tokenizer = LEDTokenizer.from_pretrained("allenai/led-base-16384")
model = LEDForConditionalGeneration.from_pretrained("allenai/led-base-16384")

inputs = tokenizer("hello " * 12000, return_tensors="pt")
# let's make sure `decoder_input_ids` are provided so that they are < 1024
inputs["decoder_input_ids"] = inputs["input_ids"][:, :512]

model(**inputs)
```

**Comment by patrickvonplaten** [comment]
We probably should add a warning message here: https://github.com/huggingface/transformers/blob/29dfb2dbb10cdba6327ff287db56b182c1db29b1/src/transformers/models/led/modeling_led.py#L2212 to make sure the user is aware that `decoder_input_ids` are automatically generated. In case you would be interested to open a PR, that would be great!
