### ISSUE TITLE
HF space specific issue: can't import `AutoModelForSeq2SeqLM` from `transformers==4.6.1` with `torch` installed

### ISSUE THREAD

**Issue by aseifert** [huggingface/transformers#14604]
For some reason I can't import `AutoModelForSeq2SeqLM` when running on hf space AND having installed `torch==1.10.0`.

## Environment info

- `transformers` version: 4.6.1
- Platform: HF Space – https://huggingface.co/spaces/aseifert/AutoModelForSeq2SeqLM-not-working
- Python version: 3.8
- PyTorch version (GPU?): 1.10.0
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

## To reproduce

Here is a minimal example illustrating the problem, with the only difference being the installation of `torch` through `requirements.txt`:

Works: https://huggingface.co/spaces/aseifert/AutoModelForSeq2SeqLM-working
Doesn't work: https://huggingface.co/spaces/aseifert/AutoModelForSeq2SeqLM-not-working

As far as I can tell this only happens on HF Space. I can't reproduce the problem on Google Colab: https://colab.research.google.com/drive/1SfNk-YjwqxYC_92y-652NoYrCi-vBEHd?usp=sharing

Not sure what's happening here, hopefully someone can help me figure this out!

Thanks,
Alex

**Comment by osanseviero** [comment]
cc @cbensimon

**Comment by lewtun** [comment]
Thank you for flagging this issue @aseifert ! 

I was able to reproduce this locally in `conda` using:

```
conda create -n buggy-space python=3.9 && conda activate bugg-space
pip install transformers==4.6.1 torch==1.10.0
```

followed by running the following inside the Python repl:

```
from transformers import AutoModelSeq2SeqLM
```

The _really_ strange aspect is that the following runs without error:

```
python -c "from transformers import AutoModelSeq2SeqLM"
```

I was also able to reproduce the error up to `transformers` v4.8, after which the `AutoModelSeeq2SeqLM` class was replaced separate classes for encoder / decoder LM.

I'm not entirely sure what is causing the problem here, but don't think it's specifically connected to Spaces
