### ISSUE TITLE
FlaxVisionEncoderDecoderModel has no attribute 'from_encoder_decoder_pretrained' ?

### ISSUE THREAD

**Issue by PrithivirajDamodaran** [huggingface/transformers#14831]
Transformers Version: 4.14.1

`FlaxVisionEncoderDecoderModel.from_encoder_decoder_pretrained('google/vit-base-patch32-224-in21k', 'gpt2')`

throws the following error

`AttributeError: type object 'FlaxVisionEncoderDecoderModel' has no attribute 'from_encoder_decoder_pretrained'`

But the documentation below suggests its available 

https://huggingface.co/docs/transformers/model_doc/visionencoderdecoder

what am I missing?

**Comment by patil-suraj** [comment]
I think this is because `flax` is not installed, for flax models we should install `jax`, `jaxlib` and `flax`. The import returns a dummy `FlaxVisionEncoderDecoderModel` when flax is not installed which has no methods.

You could see in this colab that it works https://colab.research.google.com/drive/1g6oU-AYFpzVNWgn1qT5NKlEqor3tLCeI?usp=sharing
