### ISSUE TITLE
[ONNX] transformer.onnx exporting fails for longformer 

### ISSUE THREAD

**Issue by RaedShabbir** [huggingface/transformers#15217]
## Environment info

- `transformers` version: 4.16.0.dev0
- Platform: Linux-5.11.0-1024-gcp-x86_64-with-debian-bullseye-sid
- Python version: 3.7.11
- PyTorch version (GPU?): 1.10.1+cu102 (True)
- Tensorflow version (GPU?): 2.7.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Using transformer.onnx 
- Using distributed or parallel set-up in script?: No

Models:
- Longformer: @patrickvonplaten

## Information

The same error occurs for 
- allenai/longformer-base-4096
- valhalla/longformer-base-4096-finetuned-squadv1
- allenai/longformer-large-4096

## To reproduce

```
python -m transformers.onnx --model=allenai/longformer-base-4096  ./longformer-base-4096 

```

### Error Code 
`RuntimeError: 0INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/alias_analysis.cpp":584, please report a bug to PyTorch. We don't have an op for aten::constant_pad_nd but it isn't a special case.  Argument types: Tensor, int[], bool, `

**Comment by lewtun** [comment]
Hi @RaedShabbir thank you for reporting this bug! It seems that this one slipped through our unit tests and it's not currently possible to export Longformer due to a limitation with the ops supported in JIT.

We plan to remove Longformer from the list of supported architectures until a long-term solution can be found. In the meantime, if you'd like to investigate which part of the Longformer implementation is causing the error, then please feel free to comment here on what you find!

**Comment by RaedShabbir** [comment]
Working on it
