### ISSUE TITLE
Movement Prune

### ISSUE THREAD

**Issue by JackqqWang** [huggingface/transformers#15265]
Hi everyone. I expect to use the movement prune approach to get a pruned bert on a downstream task with this link

[https://github.com/huggingface/transformers/tree/master/examples/research_projects/movement-pruning](url)

Basically speaking, we have a bert, and downstream task( AG news/ Yahoo answers, classification tasks), we wanna get a pruned BERT fitting this task.

I am trying Iterative Magnitude Pruning in the link as above. But I am a little confused that what is the train-v1.1.json and dev-v1.1.json should look like?

Thanks!

**Comment by lewtun** [comment]
Hi @JackqqWang these kind of questions are best suited for our [forums](https://discuss.huggingface.co/) since we use issue to triage bug reports or feature requests.

In any case, my suggestion would be to use our `nn_pruning` [library](https://github.com/huggingface/nn_pruning) instead of the `movement-pruning` project. The reason I suggest this is that @madlag found a clever way to extend movement pruning such that inference can be improved by factors of 2-3x. You can find various examples for text classification in that repo :)
