### ISSUE TITLE
Whether instantiation is premature?

### ISSUE THREAD

**Issue by Fei-Wang** [huggingface/transformers#15269]
https://github.com/huggingface/transformers/blob/515ed3ad2a11a6b0cd9800b2ad4d3b313fdaea8c/src/transformers/feature_extraction_utils.py#L429

For example my code is:
```python3 
processor = LayoutXLMProcessor.from_pretrained('microsoft/layoutxlm-base', apply_ocr=False)
```
I don't need to use OCR, but pytesseract still has to be installed. 
Would it be a good solution to this kind of problem if the parameters were updated with kwargs before instantiation？

**Comment by Fei-Wang** [comment]
@NielsRogge any suggestions?

**Comment by NielsRogge** [comment]
Hi,

Thanks for the issue and apologies for the late reply. I'll look into this.

**Comment by NielsRogge** [comment]
cc'ing @sgugger. So the issue is that `LayoutLMv2Processor` consists of a tokenizer + feature extractor, and I have 2 variants of the feature extractor (it can be initialized with apply_ocr set to True or False).

The problem is here is that, 'microsoft/layoutxlm-base' on the hub has a `preprocessor_config.json` which has `apply_ocr = True`, hence the `from_pretrained()` method will raise the error that PyTesseract should be installed. However, the additional kwarg `apply_ocr=False` is only taken into account after this.

**Comment by sgugger** [comment]
Yes, that is the `FeatureExtractionMixin` is coded. I suggest moving the `requires_backends(self, "pytesseract")` to the call method instead of the init to solve this issue.
