### ISSUE TITLE
Using HuggingFace Models for Text Translation of sensitive data

### ISSUE THREAD

**Issue by prateekralhan** [huggingface/transformers#15331]
Hello folks,

Wish you all a belated happy new year! 🎉

First of all, thanks a ton for creating such transformers which have "transformed" the entire NLP landscape. 🤗

### Objective 🎯
I am working on developing a web application for performing multilingual translation using mBart and transformers of textual information found in documents - PDFs, word files etc. A basic prototype has been implemented [here.](https://github.com/prateekralhan/Multilingual-Translator)

### Question/Doubt ⁉
I am planning to scale this up and use it for handling/processing extremely sensitive data at enterprise level. My question is to get an understanding how do the APIs are storing the responses returned by the models which are present in the HF servers.

1. Is the data copied to the backend servers via the browser, and contained in a BytesIO buffer in Python memory (i.e. RAM, not disk) and the data will persist in RAM until my app re-runs from top-to-bottom??
2. Is the data erased from memory when the user uploads another file, replacing the original one or when the user closes the browser tab/exits the web app?
3. Or is there any time period for which the data gets stored in the backend servers and then gets erased post that duration?

Would love to get complete idea on this. 

### Who can help
@patrickvonplaten

Sincere apologies from my end should I unknowingly followed wrong protocol for raising such a doubt. Please let me know if you need any further information from my end.

Cheers,
Prateek

**Comment by LysandreJik** [comment]
You're using the inference API, right? cc @Narsil

**Comment by Narsil** [comment]
Hi @prateekralhan ,

Your demo code doesn't use the API but seems to be using Streamlit, so I guess you envision using Spaces ?

If that's the case, I suggest you look a bit more into the API https://api-inference.huggingface.co/docs/python/html/index.html since Spaces currently has no commercial offering.

For the API.
Currently, all requests are logged in our secure servers.
Access is only granted to API maintainers, to help debug actual bugs (somes bugs are caused by specific requests, so we need to know what they are to trigger them again and fix them). It's also used as a backup for accounting so we can always recount the API use of a given user should the need arise (didn't so far to my knowledge).

The logs are never used for any other reason than that, not sold, not examinated, not used as a dataset source, and access is limited to a handful of employees.

That being said, if you plan to use the API extensively, being on a custom plan, you can also asks for logs to not be written on your account.  You can reach out to api-enterprise@huggingface.co (This isn't something you can do self served).
As for the sensitivity of your data, you seem to want extra security, this is something that should better discussed during a call with our teams I think.

**Comment by prateekralhan** [comment]
@Narsil  and @LysandreJik , thank you for the clear explanation. This answers my doubt! 😄
