### ISSUE TITLE
snapshot_download() got an unexpected keyword argument 'allow_regex'

### ISSUE THREAD

**Issue by gnmarten** [huggingface/transformers#15393]
## Environment info

- `transformers` version: 4.16.0
- Platform: Linux-3.10.0-1160.24.1.el7.ug.x86_64-x86_64-with-glibc2.2.5
- Python version: 3.8.6
- PyTorch version (GPU?): 1.10.1+cu102 (False)
- Tensorflow version (GPU?): 2.7.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: not yet (testing)
- Using distributed or parallel set-up in script?: no (but on HPC)
### Who can help
@patrickvonplaten (loading ASR model with kenlm and pyctcdecode)

## Information

Model I am using (Bert, XLNet ...): 

```
>>> processor = AutoProcessor.from_pretrained("flozi00/wav2vec2-large-xlsr-53-german-with-lm")    
Traceback (most recent call last):    
  File "<stdin>", line 1, in <module>    
  File "/kyukon/scratch/gent/427/vsc42730/hftransformers/transformers_env/lib/python3.8/site-packages/transformers/models/auto/processing_auto.py", line 161, in from_pretrained
    return processor_class.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/kyukon/scratch/gent/427/vsc42730/hftransformers/transformers_env/lib/python3.8/site-packages/transformers/models/wav2vec2_with_lm/processing_wav2vec2_with_lm.py", line 174, in from_pretrained
    decoder = BeamSearchDecoderCTC.load_from_hf_hub(
  File "/kyukon/scratch/gent/427/vsc42730/hftransformers/transformers_env/lib/python3.8/site-packages/pyctcdecode/decoder.py", line 757, in load_from_hf_hub
    cached_directory = snapshot_download(model_id, cache_dir=cache_dir, **kwargs)
TypeError: snapshot_download() got an unexpected keyword argument 'allow_regex'
```

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

```
from transformers import AutoModelForCTC, AutoProcessor
model = AutoModelForCTC.from_pretrained(model_id)
processor = AutoProcessor.from_pretrained(model_id)
```

## To reproduce

1. pip install transformers
2. pip install pyctcdecode
3.  pip install https://github.com/kpu/kenlm/archive/master.zip

Possibly related to recent bugfix https://github.com/huggingface/transformers/pull/14881#discussion_r773823212

Similar result with
```
processor = Wav2Vec2ProcessorWithLM.from_pretrained
```
May also result in the following error when trying Wav2Vec2CTCTokenizer as intermediate step
```
TypeError: from_pretrained() takes 2 positional arguments but 3 were given
```

## Expected behavior

load processor

The current behaviour seems inherited from 
```
from pyctcdecode import BeamSearchDecoderCTC
```
and in accordance with https://github.com/huggingface/transformers/blob/master/src/transformers/models/wav2vec2_with_lm/processing_wav2vec2_with_lm.py

I hope this is the right place to ask after the integration, thanks in advance and keep up the good work

**Comment by patrickvonplaten** [comment]
Hey @gnmarten,

Could you copy-paste this command and state your` output here: 
```bash
python -c "import huggingface_hub; print(huggingface_hub.__version__)"
```

If your version is lower than 0.2.1 it would be nice if you could upgrade `huggingface_hub`

**Comment by gnmarten** [comment]
yes, it was <0.4.0, and after upgrade the download works (with remark "Loading the LM will be faster if you build a binary file.")


Thanks a lot for the fast reaction

**Comment by BaiMeiyingxue** [comment]
Hi everyone,
   My huggingface_hub is 0.11.1, and the error 
```
   TypeError: snapshot_download() got an unexpected keyword argument 'local_dir_use_symlinks'
   snapshot_download() got an unexpected keyword argument 'local_dir_use_symlinks'
   snapshot_download() got an unexpected keyword argument 'local_dir'
```
which version should I update to?

**Comment by patrickvonplaten** [comment]
Could you upgrade `huggingface_hub` to the newest version?

**Comment by MartinGrashei** [comment]
Hi everyone,

same error:
[/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py](https://localhost:8080/#) in _inner_fn(*args, **kwargs)
    116             kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.__name__, has_token=has_token, kwargs=kwargs)
    117 
--> 118         return fn(*args, **kwargs)
    119 
    120     return _inner_fn  # type: ignore

**TypeError: snapshot_download() got an unexpected keyword argument 'allow_regex'**


WIth huggingface_hub being upgraded to the latest version: 0.16.4 
I'm using original version of the colab-tutorial with only the first four lines modified in order to make the packages load properly for me: 
!pip install https://github.com/kpu/kenlm/archive/master.zip
!pip install https://github.com/kpu/kenlm/archive/master.zip pyctcdecode==0.3.0 
!pip install datasets==2.0.0
!pip install transformers==4.18.0 

regarding the package versions I get this overview: 
Requirement already satisfied: transformers==4.18.0 in /usr/local/lib/python3.10/dist-packages (4.18.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers==4.18.0) (3.12.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.18.0) (0.16.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.18.0) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.18.0) (23.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.18.0) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.18.0) (2023.6.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers==4.18.0) (2.31.0)
Requirement already satisfied: sacremoses in /usr/local/lib/python3.10/dist-packages (from transformers==4.18.0) (0.0.53)
Requirement already satisfied: tokenizers!=0.11.3,<0.13,>=0.11.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.18.0) (0.12.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers==4.18.0) (4.66.1)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.1.0->transformers==4.18.0) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.1.0->transformers==4.18.0) (4.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.18.0) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.18.0) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.18.0) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.18.0) (2023.7.22)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from sacremoses->transformers==4.18.0) (1.16.0)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from sacremoses->transformers==4.18.0) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from sacremoses->transformers==4.18.0) (1.3.2)

Support would be greatly appreciated, thank you!

**Comment by vin136** [comment]
I'm getting the same error:

    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
TypeError: snapshot_download() got an unexpected keyword argument 'ignore_files'

I'm on the latest version too

**Comment by 631068264** [comment]
```
Traceback (most recent call last):
  File "/workspace/work/private/st_base.py", line 14, in <module>
    my_local_config_path = snapshot_download(
                           ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
TypeError: snapshot_download() got an unexpected keyword argument 'allowed_patterns'
```

0.23.4
