### ISSUE TITLE
Support for larger XGLM models

### ISSUE THREAD

**Issue by Hritikbansal** [huggingface/transformers#15417]
According to the official XGLM repo, https://github.com/pytorch/fairseq/tree/main/examples/xglm, there are five versions of XGLM out there. The architecture of the larger XGLM versions is same as the base XGLM, ; why doesn't HF provide support for larger XGLM versions?  It seems that currently HF provides support for the smallest one (546M parameters) only.

**Comment by NielsRogge** [comment]
Hi,

There are already 4 variants available: https://huggingface.co/models?other=xglm.

Only the 4.5B variant seems to be missing as of now, but pretty sure @patil-suraj is going to add that one as well.

**Comment by patil-suraj** [comment]
As Niels pointed out, all the xglm checkpoints are available on the hub except the 4.5B. I'm having some issues with that checkpoint so will upload that once it's resolved.

**Comment by patil-suraj** [comment]
Just pushed the 4.5B checkpoint https://huggingface.co/facebook/xglm-4.5B

All XGLM checkpoints are now available on the hub. Closing this issue.

**Comment by WadeYin9712** [comment]
Hi @patil-suraj and @NielsRogge ! Thanks for your quick reply! I went through the code of XGLM model. It seems that for the model and tokenizer part, we can only use the smallest one. Because I noticed a snippet like this:

XGLM_PRETRAINED_MODEL_ARCHIVE_LIST = [
    "facebook/xglm-564M",
    # See all XGLM models at https://huggingface.co/models?filter=xglm
]

Would you like to provide any advice to make use of the larger models like 1.7B, 2.5B and 4.5B? For example, just add the model names in the list? Thanks in advance!

**Comment by patil-suraj** [comment]
Hi @WadeYin9712 

That list is only used for internal purposes. You can use all the xglm checkpoints available on the hub https://huggingface.co/models?other=xglm.

To use it, just pass the repo id to `from_pretrained`. For ex

```python3
model = XGLMForCausalLM.from_pretrained("facebook/xglm-1.7B")
```
