### ISSUE TITLE
Adding new tokens to uncased tokenizers - case insensitivity is lost

### ISSUE THREAD

**Issue by mbednarski** [huggingface/transformers#1545]
## ❓ Questions & Help

Hello!

I'm trying to add new tokens to bert-base-uncased. Let's say my token is '**cool-token**' and it was not present in the original vocab

```
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
print(tokenizer.tokenize('Sentence with cool-token'))
```

Prints as expected:

`['sentence', 'with', 'cool', '-', 'token']`

Now I add this token
`tokenizer.add_tokens(['cool-token'])`

Once again, prints as expected:
`['sentence', 'with', 'cool-token']`

However, when I try to utilize case-insensitivity my new token seems to be not recognized:

`print(tokenizer.tokenize('SenTenCE wIth cOOl-token'))`
prints
`['sentence', 'with', 'cool', '-', 'token']`

I would expect:
`['sentence', 'with', 'cool-token']`

It seems that custom tokens are not lowercased. Is it expected behavior and I have to `.lower()` my text manually or am I doing something wrong?

Anyway, I <3 your library

**Comment by watkinsm** [comment]
Hmm looks like BertTokenizer's super class handles `.add_tokens()` and the first steps of `.tokenize()`, and doesn't really seem to consider whether the tokens should be made lowercase. I'm not sure whether it's intentional, but I'll make a PR and find out :smile: 

In the meantime, it might be a good idea to manually lowercase your text before tokenization.
