### ISSUE TITLE
Tokenizers dictionaries not being saved to cache.

### ISSUE THREAD

**Issue by m-bain** [huggingface/transformers#15577]
Hi,

Sometimes huggingface servers are down. This can break training scripts if you are trying to load a tokenizer because they get the vocabulary through the API everytime.

e.g. 
`tokenizer = transformers.CLIPTokenizer.from_pretrained("openai/CLIP/ViT-B/32")`

If the servers are down the above line of code will fail:

`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/openai/CLIP/ViT-B/32`

Why not save the tokenizer vocab to the local model cache the first time this is called? This would reduce unnecessary calls to the server and make training models less sensitive to huggingface server downtime.

**Comment by beneyal** [comment]
Hello 🙂 

Tokenizers get automatically cached when first downloaded, so once you downloaded the tokenizer, you can use `AutoTokenizer.from_pretrained(model_name, local_files_only=True)` and if the tokenizer is present in the cache, you'll get the tokenizer. Otherwise, you'll get `TypeError: __init__() missing 1 required positional argument: 'vocab_file'`.

If you want to work completely offline, you can run your script with the `TRANSFORMERS_OFFLINE=1` environment variable.

**Comment by m-bain** [comment]
ok tbh i feel like the cache should be used automatically without needing the flag, it also seems to not have downloaded for me but ill check further
