### ISSUE TITLE
Need more understanding of the function: get_visual_embeddings(image_path)

### ISSUE THREAD

**Issue by dheeman00** [huggingface/transformers#15724]
Dear Developers

I was looking through the code for image embedding and found this section of the code in the visual_bert:

# this is a custom function that returns the visual embeddings given the image path
visual_embeds = get_visual_embeddings(image_path)

This is a user-defined function. But I want to know what are the existing imaging embedding process should work with visual_bert?

Some suggestions will be helpful.

Thanks
Dheeman

**Comment by LysandreJik** [comment]
Hey @dheeman00!

You should check out the following complete example for a fully working pipeline with VisualBERT: https://github.com/huggingface/transformers/tree/master/examples/research_projects/visual_bert

cc @gchhablani

**Comment by dheeman00** [comment]
Hey @LysandreJik 

I looked into the repo. But I think I found a better example that can be helpful for others.

https://huggingface.co/docs/transformers/model_doc/deit

deit directly represents a vector from a given image.

**Comment by LysandreJik** [comment]
cc @NielsRogge too

**Comment by Joaquin2000zz** [comment]
> Hey @LysandreJik
> 
> I looked into the repo. But I think I found a better example that can be helpful for others.
> 
> https://huggingface.co/docs/transformers/model_doc/deit
> 
> deit directly represents a vector from a given image.

Hey @dheeman00

You said _deit directly represents a vector from a given image. I would like to know if you can help me to understand which part is creating the visual embedding because I'm kinda lost. I wonder if you can bring me some help finding the `visual_embeds = get_visual_embeddings(image_path)` equivalent.

Thank you in advance, I would appreciate your help :D
