### ISSUE TITLE
AdamW requires torch>=1.2.0

### ISSUE THREAD

**Issue by carter54** [huggingface/transformers#1585]
## 🐛 Bug

AdamW requires torch>=1.2.0, torch < 1.2.0 will cause an importError: cannot import name 'AdamW'
Model I am using (Bert, XLNet....):

Language I am using the model on (English, Chinese....):

The problem arise when using:
* [ ] the official example scripts: (give details)
* [ ] my own modified scripts: (give details)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details)

## To Reproduce

1.
2.
3.

## Environment

* OS:
* Python version:
* PyTorch version:
* PyTorch Transformers version (or branch):
* Using GPU ?
* Distributed of parallel setup ?
* Any other relevant information:

**Comment by BramVanroy** [comment]
I don't think that's right. AdamW is implemented in transformers.optimization

https://github.com/huggingface/transformers/blob/82f6abd98aaa691ca0adfe21e85a17dc6f386497/transformers/optimization.py#L107

As far as I can see that does not require anything specific to torch 1.2. _However_, if you are trying to import [AdamW from torch ](https://pytorch.org/docs/stable/optim.html#torch.optim.AdamW), you may indeed be required to use torch 1.2.

I haven't compared the implementation in torch vs. transformers, but I'd go with torch's native implementation if you can and otherwise fallback to transformers' implementation.

**Comment by carter54** [comment]
sorry, I didn't show the details:
the error is from 29 line in transformers/examples/distillation/distiller.py
from torch.optim import AdamW
this AdamW is imported from torch.optim

**Comment by policeme** [comment]
does this really need torch >=1.2? I met this problem

**Comment by policeme** [comment]
my torch version is 1.1

**Comment by BramVanroy** [comment]
No.

**Comment by BramVanroy** [comment]
No. Importing AdamW from transformers should work with earlier versions. If you're trying to import it directly from torch, then you'll need 1.2+.

**Comment by BramVanroy** [comment]
Unstale.
