### ISSUE TITLE
Non-unique `local` in toctree

### ISSUE THREAD

**Issue by mishig25** [huggingface/transformers#15925]
`local` field in toctree is treated as an id; therefore, it has to be unique. Because of this, in https://huggingface.co/docs/transformers/multilingual, you cannot reach the second `multilingual` page

I will work on the doc-builder that checks locals are unique;

[line here](https://github.com/huggingface/transformers/blob/master/docs/source/_toctree.yml#L32)

<img width="300" alt="Screenshot 2022-03-03 at 18 08 52" src="https://user-images.githubusercontent.com/11827707/156615355-af17d9fc-0c8b-488c-ada3-77edc923bf15.png">

**Comment by stevhliu** [comment]
Thanks for this! I think we can actually remove the first `multilingual` page since it is outdated now. On a related note, can we also remove the `custom_datasets` [page](https://huggingface.co/docs/transformers/master/en/custom_datasets) since it has also been replaced by the fine-tune for downstream tasks section?

Is this also why for section headers that share the same name, the second header cannot be reached (i.e., feature extractor [here](https://huggingface.co/docs/transformers/master/en/preprocessing#feature-extractor))?

**Comment by sgugger** [comment]
@mishig25 Add you added something to error when entries are not unique?
