### ISSUE TITLE
add special tokens does not work in GPT2Tokenizer

### ISSUE THREAD

**Issue by ahxchzt** [huggingface/transformers#15975]
## Environment info

- `transformers` version: 3.5.0
- Platform: Pytorch
- Python version: 3.7.5
- PyTorch version (GPU?): torch-1.6.0 cuda102

Models: GPT-2 @patrickvonplaten

- Tokenizers: @SaulLu

## Information

I want to add some special tokens to the GPT2 vocab but the function "add_ special_tokens" do not work.
My code just like this

`tokenizer=GPT2Tokenizer.from_pretrained(gpt2path)`

`kb=torch.load(kbpath)`

`tokenizer.add_special_tokens({'additional_special_tokens':list(kb)})`

`print(tokenizer.tokenize("i'd like to book a table at resto_bombay_expensive_british_4stars_2",add_special_tokens=True))`

`print("resto_bombay_expensive_british_4stars_2" in list(kb))`

The output of last print is 
**"True"**, 

so I think the special tokens in KB has been added into GPT2 vocab.
But the output of the tokenizer.tokenize(...) is 
**['i', "'d", 'Ġlike', 'Ġto', 'Ġbook', 'Ġa', 'Ġtable', 'Ġat', 'Ġrest', 'o', '_', 'bomb', 'ay', '_', 'expensive', '_', 'b', 'rit', 'ish', '_', '4', 'stars', '_', '2']**

The special tokens is splited. Why?

## Expected behavior

**['i', "'d", 'Ġlike', 'Ġto', 'Ġbook', 'Ġa', 'Ġtable', 'Ġat', 'Ġresto_bombay_expensive_british_4stars_2']**

**Comment by patrickvonplaten** [comment]
Hey @ahxchzt,

Thanks for your issue.
Could you please provide at code-snippet that one can copy-paste into a Python environment and execute directly. Your code snippet doesn't work because:

- 1) `GPT2Tokenizer` is not imported 
- 2) No one has access to `gpt2path` nor `kbpath` so we can't reproduce the error at all even though we know how to do 1)

Could you make sure the code snippet is reproducible?

**Comment by ahxchzt** [comment]
Thanks for your reply.@patrickvonplaten
I updated my transformers to 4.17.0 and the problem had been solved. I think the issue can be closed.
