### ISSUE TITLE
Any reasons not using `processors` or `pipelines` modules in example codes?

### ISSUE THREAD

**Issue by nbqu** [huggingface/transformers#16096]
Hi, I'm wondering that is there any reasons, or purposes not using `processors` or `pipelines` modules in example codes, such as [`run_glue.py`](https://github.com/huggingface/transformers/blob/master/examples/pytorch/text-classification/run_glue.py) or [`run_qa.py`](https://github.com/huggingface/transformers/blob/master/examples/pytorch/question-answering/run_qa.py).

First, I strongly appreciate for providing example codes, which is very helpful to understand not only `transformers` library, but also entire workflows of NLP. Moreover, example codes could introduce useful APIs in `transformers` to beginners like me.

So I suggest that it would be great to apply such APIs to example codes, unless there are specific reasons not using them.

**Comment by LysandreJik** [comment]
Hey @nbqu, `processors` are preprocessing components that are specifically used for complex situations where a feature extractor and a tokenizer are needed for preprocessing. Examples which require them therefore have them, for example see here: https://github.com/huggingface/transformers/blob/5664d2762260ddb9e01f0566ddd43cafd5cdd807/examples/pytorch/speech-recognition/run_speech_recognition_ctc.py#L270

Pipelines, on the other hand, support inference rather than training. The examples under the `examples` directory are for training specifically, so there's no need to leverage pipelines there.

However, if you take a look at your [documentation](https://huggingface.co/docs/transformers/quicktour), you'll see that pipelines are mentioned!
