### ISSUE TITLE
Why is wandb being logged in and how to turn it off?

### ISSUE THREAD

**Issue by Nikita-Salkar** [huggingface/transformers#16594]
I do not have a profile with wandb profile. I have not logged into anything and I don't want to use wandb. I am simply following this notebook to finetune a T5 model for summarization https://colab.research.google.com/github/huggingface/notebooks/blob/master/examples/summarization.ipynb#scrollTo=X4cRE8IbIrIV (I am not running the huggingface login and the git cells)
The notebook was working fine till a day before and I was storing checkpoints but now when I try to run either from the checkpoint or by loading t5-small, I get asked for the wandb API key on running the trainer. I don't even have a profile. 
<img width="1013" alt="Screen Shot 2022-04-04 at 7 19 45 PM" src="https://user-images.githubusercontent.com/78582210/161647987-eeb3066e-72d9-4cad-9a7e-e2810073984f.png">

When I tried wandb off, it again asked me for the API key.
I tried os.environ["WANDB_DISABLED"]  = "true" but it doesn't work. 
trainer.train() runs for 501 iterations and then gives the following error : 
<img width="754" alt="Screen Shot 2022-04-04 at 7 04 49 PM" src="https://user-images.githubusercontent.com/78582210/161646555-26741d97-5c0e-44c5-9461-8dd93a35ab99.png">

I don't understand why it suddenly started asking me for this and how to resolve it. 
Please help

@sgugger

**Comment by morganmcg1** [comment]
hey @Nikita-Salkar I work at Weights & Biases, you can turn off all external logger logging, including wandb logging` by passing `report_to="none"` in your `Seq2SeqTrainingArguments`.

You might have noticed the following warning when setting up your TrainingArguments.

```
The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same behavior as now. You should start updating your code and make this info disappear :-)
```

Right now the default is to run all loggers that you have installed, so maybe you installed wandb on your machine since the last time you ran the script?

If you would like to log with wandb, best practice would already be to start setting `report_to="wandb"`

**Comment by Nikita-Salkar** [comment]
@morganmcg1 Yes yes. Thank you!

**Comment by IDoMathEveryDay** [comment]
I hate wandb, Why on earth do you think defaulting every training logs to wandb is a good idea?
