### ISSUE TITLE
A tool to generate this library with (a) specific model(s)

### ISSUE THREAD

**Issue by dinhanhx** [huggingface/transformers#16645]
# 🚀 Feature request

A tool that allows users (mostly researchers) to get a specific version of (a) transformer model(s) depending on framework, hugging face version.

For example, I want only the source code of BART model for PyTorch in the latest version of HuggingFace, but I don't want to break other HuggingFace feature. The tool should remove any files related to other models, and any frameworks such as TensorFlow. I could run `gettransformers bart pytorch`. This command should generate for me a huggingface/transformers library that only has BART model written with PyTorch.

## Motivation

To let the researchers obtain less line of codes that they can reuse. 

## Your contribution

I propose the feature.

**Comment by LysandreJik** [comment]
Hey @dinhanhx! The transformers library is made to have models be independent of each other, so that when modifying a model file, you're certain that it will not break other models. You can therefore feel free to modify the code of BART for your use-case, and rest-assured that it will not break other models.

If you'd like to create a brand new model from BART and tweak it to your use-case while keeping BART intact, I recommend you use the `add-new-model-like` command line feature. You can read more about it [here](https://github.com/huggingface/transformers/tree/main/templates/adding_a_new_model#add-new-model-like-command).
