### ISSUE TITLE
CodeT5 tokenizer.model_max_length is 1000000000000000019884624838656

### ISSUE THREAD

**Issue by khoda81** [huggingface/transformers#16842]
### System Info

```shell
- `transformers` version: 4.12.2
- Platform: Windows-10-10.0.22000-SP0
- Python version: 3.9.7
- PyTorch version (GPU?): 1.10.2 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: False
- Using distributed or parallel set-up in script?: False
```

### Who can help?

@patrickvonplaten

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("formermagic/codet5-large")
print(tokenizer.model_max_length)
```
This prints `1000000000000000019884624838656`.

### Expected behavior

```shell
To print 512.
```

**Comment by patrickvonplaten** [comment]
Hey @khoda81, 

The bug seems to be related directly to the model of @mozharovsky and not really to a canonical model. However, also not that T5 does **not** have a maximum length. You can use T5 with lengths as long as you want until your memory errors out. T5 uses relative positional embeddings so that there is no static weight that will give you an "out-of-index" error. 

Also see: https://github.com/huggingface/transformers/issues/5204
