### ISSUE TITLE
BertEmbeddings import missing for Torch in __init__ file

### ISSUE THREAD

**Issue by seanbenhur** [huggingface/transformers#17003]
### System Info

```shell
- `transformers` version: 4.18.0
- Platform: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.13
- Huggingface_hub version: 0.5.1
- PyTorch version (GPU?): 1.11.0+cu113 (True)
- Tensorflow version (GPU?): 2.8.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No
```

### Who can help?

@LysandreJik 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

`from transformers import BertEmbeddings`

raises

```
----> 1 from transformers import BertEmbeddings

ImportError: cannot import name 'BertEmbeddings' from 'transformers' (/usr/local/lib/python3.7/dist-packages/transformers/__init__.py)
```

### Expected behavior

[BertEmbeddings](https://github.com/huggingface/transformers/blob/e6f00a11d7fa34215184e3c797e19e6c7debe0fe/src/transformers/models/bert/modeling_bert.py#L182) is a class in Bert Model file that can be used for creating BertEmbeddings, the class is not imported in[ __init__ ](https://github.com/huggingface/transformers/blob/main/src/transformers/models/bert/__init__.py)file, so the user may not be able to import it. While the TF and jax version are imported it
```


It should be imported

**Comment by NielsRogge** [comment]
Feel free to open a PR to fix this :)

**Comment by LysandreJik** [comment]
I think in that case it's the TF and Jax versions which shouldn't add the embeddings to the main init. Those are not meant to be accessed from the main init, but to be accessed from their respective modules:

```py
>>> from transformers.models.bert.modeling_bert import BertEmbeddings
```

We took that decision so that the internal may be modified without breaking to public root API. These have very rarely been updated, however.

Removing the Flax and TF imports from the init isn't an option either, unfortunately, as it would result in a breaking change for users that do use it.

**Comment by seanbenhur** [comment]
Agree with you, Can I close this issue then?

**Comment by LysandreJik** [comment]
Yes, thanks for opening it in the first place!
