### ISSUE TITLE
    model = GPT2LMHeadModel.from_pretrained(args.model_path) try loads in json format

### ISSUE THREAD

**Issue by jinfagang** [huggingface/transformers#1782]
## 🐛 Bug

Initial a model in this code:

```
logging.info('loading model from: {}'.format(args.model_path))
    model = GPT2LMHeadModel.from_pretrained(args.model_path)
```

It seems inside transforms reading our model in json format which cause error:

```
INFO 11-10 16:18:49 generate.py:167 - loading model from: ./weights/ProseInChinese/pytorch_model.bin
I1110 16:18:49.226168 139982371047232 configuration_utils.py:148] loading configuration file ./weights/ProseInChinese/pytorch_model.bin
Traceback (most recent call last):
  File "generate.py", line 225, in <module>
    main()
  File "generate.py", line 168, in main
    model = GPT2LMHeadModel.from_pretrained(args.model_path)
  File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_utils.py", line 287, in from_pretrained
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/transformers/configuration_utils.py", line 154, in from_pretrained
    config = cls.from_json_file(resolved_config_file)
  File "/usr/local/lib/python3.6/dist-packages/transformers/configuration_utils.py", line 186, in from_json_file
    text = reader.read()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

**Comment by LysandreJik** [comment]
What string was passed under `args.model_path`? Is it a directory or a file name? (It should be a directory)

**Comment by jinfagang** [comment]
model_path is a model trained with xxx.pth format.

Is that a directory? contains what？

**Comment by LysandreJik** [comment]
The `model_path` should link to a directory holding the pytorch model and the configuration file associated with it, as if it was saved with `model.save_pretrained(directory)`.

What is your `xxx.pth` format, how did you obtain such a file?

**Comment by jinfagang** [comment]
Oh, no, I just got others trained xx.pth model, no config file.

Why a pytorch model need additional config.json? And people really don't know what's the format inside that file at all..... no convinient

**Comment by LysandreJik** [comment]
The Pytorch models require configuration files because the architectures in the library can have very different sizes. For example GPT-2 small, medium, large and XL all share the same model but have different sizes. Configuration files are essential for this purpose.

The format is defined by the `save_pretrained` method on the models. Models acquired from other sources than our library may not be loadable, or may need to be converted using one of our conversion scripts.

Please read the [quickstart portion of the documentation](https://huggingface.co/transformers/quickstart.html) to get a deeper understanding of the way the library works.
