### ISSUE TITLE
Clarifications about the Quick-tour of the fine-tuning scripts?

### ISSUE THREAD

**Issue by bulutsuzku** [huggingface/transformers#1875]
## ❓ Questions & Help

The [quick tour](https://github.com/huggingface/transformers#quick-tour-of-the-fine-tuningusage-scripts) mentions an example of fine-tuning on different GLUE tasks.

My task/trained model has nothing to do with GLUE tasks, i.e.: I already have a pre-trained  pytorch model file and the formatted corpus files (train.tsv, dev.tsv and test.tsv). 

Is the run_glue.py script meant to be edited by me for doing a new *NON GLUE* fine-tuning? 

Or it is a matter of adjusting parameters on the CLI?

If none of them applies, where I can find an example of fine-tuning with support for "customized" task?

**Comment by LysandreJik** [comment]
Hi, what exactly is your task? Is it question answering, sequence classification, language modeling, other?

**Comment by bulutsuzku** [comment]
> Hi, what exactly is your task? Is it question answering, sequence classification, language modeling, other?

Hi LysandreJik

I have two tasks: First one is sequence classification. Second one is Relation Extraction.

**Comment by LysandreJik** [comment]
For sequence classification, you can indeed take inspiration from the script `run_glue.py`. Those scripts are meant as examples showcasing how to manage models for different tasks, so that users may train our models in any way they see fit. The models are standard PyTorch models so they can be trained like any other model.

For relation extraction, there are no models specifically targeting this task but feel free to adapt a standard model by adding a few layers on top. For training there are examples in our [HMTL repository](https://github.com/huggingface/hmtl) which may be of help.
