### ISSUE TITLE
[ViT] Add note about interpolation of position encodings

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/transformers#18935]
### Feature request

We should add a note to the docs on the fact that, in order to fine-tune ViT on higher resolution (e.g. 512x512), one can set `interpolate_pos_encoding=True` in the forward of the model.

### Motivation

This thread on the forum: https://discuss.huggingface.co/t/fine-tuning-image-transformer-on-higher-resolution/22623/4

### Your contribution

I'll take this!

**Comment by jorgeili15** [comment]
Hi,

I'm findind hard to achieve to set the inteporlate_pos_encoding = True by redefining the forward method of the model. 
Could you make a brief step by step on how to do so in order to train the model, and not just make a forward pass?

I thought it was just about modifying the model.config which feeds the module parameters, as one can set the output_attentions = True per example, but I see is not the same case for the inteporlate_pos_encoding.

Thank you!
P.D: I have post this same question at the hugginface forum

**Comment by NielsRogge** [comment]
Could you clarify? The only thing you need to change is pass interpolate_pos_encoding=True to the forward when training the model (no need to redefine the forward method).

This issue was fixed in #19103, therefore I'm closing this issue.

**Comment by jorgeili15** [comment]
> 
I fine tune the model by using the Trainer build class from transformers, not directly by calling the forward method, so I'm not finding the way to set the interpolate_pos_encoding to true in that case.

**Comment by vibhas-singh** [comment]
Hi @NielsRogge 
Is there any method to use the `interpolate_pos_encoding` while using the Trainer API?
Not able to find a method to pass it as a parameter to the `forward` method without redefining the `forward` method.

**Comment by NielsRogge** [comment]
Pinging @sgugger here - the question is whether one can set a boolean argument in the forward of a model to `True` when using the Trainer API.

**Comment by sgugger** [comment]
No, that is not possible.

**Comment by vii33** [comment]
Sad to hear. Many code examples use the Trainer API. 

Would be great to bring this feature to the trainer API.

**Comment by Starlento** [comment]
> Could you clarify? The only thing you need to change is pass `interpolate_pos_encoding=True` to the forward when training the model (no need to redefine the forward method).
> 
> This issue was fixed in #19103, therefore I'm closing this issue.

Sorry to bother. Currently there are many models based on ViT. They do not support this argument (e.g. CLIP, MAE, SAM).
And the `interpolate_pos_encoding` is at a very beginning step which makes it hard to hijack. And what I am doing is modifying the source code (paste the interpolate function and run it on the pos_embeddings). Is there any suggestion to do this more elegant since they are all ViTs principlely?
