### ISSUE TITLE
Output scores in TranslationPipeline

### ISSUE THREAD

**Issue by d-miketa** [huggingface/transformers#18942]
### Feature request

Please consider adding scores to the output dict of TranslationPipeline.

https://huggingface.co/docs/transformers/v4.21.3/en/main_classes/pipelines#transformers.TranslationPipeline.__call__

### Motivation

It'd be nice to see the scores/probabilities of translated sentences rather than just an ordered list of the top k beam search outputs. In many cases the scores can be interpreted as a measure of confidence in the prediction and this is valuable, especially in production.

Pipelines are natively supported by Seldon Deploy so this would also improve that integration.

### Your contribution

I don't currently have capacity to submit a PR.

**Comment by LysandreJik** [comment]
cc @Narsil

**Comment by Narsil** [comment]
This seems a nice addition ! 

Same here, I have  limited bandwidth at the moment.

Notes for anyone wanting to implement this.

The goal is NOT to support every single feature `generate` supports in terms of return, only the one that make sense for users not knowing about ML, and not being power users (anyone that knows enough, should be able to drop down from pipelines and using lower level objects to get full control, or override the pipeline by subclassing). 
1 score per proposed translation fits that model.

A counter-example would be:  `score` per token was asked by users on `bloom` (it's `text-generation` not `translation`, but since it works similarly under the hood I'm leaving breadcrumbs. This for instance is outside of the scope of pipelines, since tokens are a ML construct, and users without any ML background will have trouble understanding what they are. In addition, returning such things change the return type which is never ideal when function/classes return types depend on arguments. (and subclassing should be easy enough to add support for anyone that so desires).
