### ISSUE TITLE
Documentation error in GPT2Tokenizer

### ISSUE THREAD

**Issue by CrafterKolyan** [huggingface/transformers#1906]
Documentation page:
https://huggingface.co/transformers/model_doc/gpt2.html#transformers.GPT2Tokenizer
Code place:
https://github.com/huggingface/transformers/blob/d7d36181fdefdabadc53adf51bed4a2680f5880a/transformers/tokenization_gpt2.py#L112-L113

This phrase:
> Otherwise, this tokenizer encode and decode method will not conserve the absence of a space at the beginning of a string: tokenizer.decode(tokenizer.encode(“Hello”)) = ” Hello”

is **NOT** correct.

Actually:
> tokenizer.decode(tokenizer.encode(“Hello”)) = ”Hello”

Try this example:
```
from transformers import GPT2Tokenizer
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
print("'" + tokenizer.decode(tokenizer.encode("Hello")) + "'")
```
Output:
```
'Hello'
```

**Comment by bkkaggle** [comment]
According to the code (https://github.com/huggingface/transformers/blob/master/transformers/tokenization_gpt2.py#L183) the docstring is incorrect. 

The `add_prefix_space` parameter should be passed to `tokenizer.tokenize()` not `tokenizer.encode()` or `tokenizer.decode()` as the docstring says.

According to #1380, the Roberta/GPT2 tokenizer expects sequences to start with a space.  Simply prepending a space to the input sequence doesn't give the same result because `GPT2Tokenizer` only overrides the internally-used `_tokenizer()` method and `PreTrainedTokenizer`'s `tokenize()` method (which is called by the user) does it's own preprocessing.
