### ISSUE TITLE
Download model too slow, is there any way

### ISSUE THREAD

**Issue by bigzhouj** [huggingface/transformers#1934]
in run_lm_finetuning.py  
transformers.file_utils -   https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased-pytorch_model.bin not found in cache or force_download set to True, downloading to ....

**Comment by LysandreJik** [comment]
If your model download is too slow and fails, you can manually download it from our S3 using your browser, wget or cURL as an alternative method.

You can then point to a directory that has both the model weights (xxx-pytorch_model.bin) and the configuration file (xxx-config.json) instead of the checkpoint name as the argument for `run_lm_finetuning.py`.

**Comment by karajan1001** [comment]
The models on  s3  are downloaded by **botocore**. And can be accelerated using a proxy.  Detailed information can be found on [](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html ).
Because It only supports **http** proxy now, other form of proxies like socks5 need to be converted to a http form.

**Comment by bigzhouj** [comment]
OSError: Couldn't reach server at 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased-config.json' to download pretrained model configuration file.

**Comment by karajan1001** [comment]
Could you open this [ https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased-config.json](url) in your browser ?

**Comment by bigzhouj** [comment]
It can be opened in a browser

**Comment by bigzhouj** [comment]
in run_lm_finetuning.py,
    probability_matrix.masked_fill_(torch.tensor(special_tokens_mask, dtype=torch.bool), value=0.0).
Why does dtyped equal torch.bool?
I have a difficulty here:
     Expected object of scalar type Byte but got scalar type Bool for argument #2 'mask'

**Comment by TheEdoardo93** [comment]
Tipically, when you say _masked_ *, you want to use boolean values (0 for absence and 1 for presence).
For what concern your issue, post the code for reproducibility and version of TensorFlow, PyTorch, Transformers.

> in run_lm_finetuning.py,
> probability_matrix.masked_fill_(torch.tensor(special_tokens_mask, dtype=torch.bool), value=0.0).
> Why does dtyped equal torch.bool?
> I have a difficulty here:
> Expected object of scalar type Byte but got scalar type Bool for argument #2 'mask'

**Comment by LysandreJik** [comment]
@bigzhouj this is probably due to a Pytorch version error. I believe `bool` was introduced in pytorch v1.2.0. What is your Pytorch version?
