### ISSUE TITLE
XLMRobertaTokenizerFast  Error

### ISSUE THREAD

**Issue by elmadany** [huggingface/transformers#19395]
### System Info

I've created a new vocab using sentencePiece PBE, I trained an xlm-roberta-base from scratch using [run_mlm.py](https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_mlm.py). When I tried loading the tokenizer using AutoTokanizer or XLMRobertaTokenizerFast it takes a long time and doesn't load, while I load it using XLMRobertaTokenizer is works well. 
I noticed this problem when I tried to finetune the model on ner using the official ner script [run_ner.py](https://github.com/huggingface/transformers/blob/main/examples/pytorch/token-classification/run_ner.py) which works only on fast tokanizer. 
I was wondering how to convert it to a fast tokenizer.

### Who can help?

@SaulLu @sgu

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I built the vocab using this command
spm_train --input="merged_vocab_data.txt" --model_prefix=sentencepiece.bpe --vocab_size=250002 --character_coverage=0.9995 --model_type=bpe --pad_id=0 --eos_id=1 --unk_id=2 --bos_id=-1

I used this vocab to initial the training model  using the official code run_mlm.py

### Expected behavior

How to convert the sentencepiece BPE slow vocab to fast

**Comment by elmadany** [comment]
@SaulLu

**Comment by LysandreJik** [comment]
Maybe of interest to @ArthurZucker as well!

**Comment by SaulLu** [comment]
Hi @elmadany

The conversion of a vocabulary coming from sentencepiece to a fast version of the tokenizer is indeed an operation which can take time, but it is an operation to be carried out only once because once loaded you can save the converted version with the fast format not to have to remake this operation the next time.

On the other hand, I am a little more concerned when you say that it "doesn't load", do you have an error message?

**Comment by elmadany** [comment]
Thanks @SaulLu
yes, it took 4 hours to convert.
So, I will close this issue
