### ISSUE TITLE
T5tokenizer.pre_trained("t5-small") is not callable whereas AutoTokenizer worked fine

### ISSUE THREAD

**Issue by mellow-d** [huggingface/transformers#19391]

**Comment by gante** [comment]
Hi @mellow-d  👋 Having a popular project like `transformers` means we get many support and feature requests — if we want to maximize how much we help the community, the community has to help us stay productive 🙏

To that end, please share a *short* script where the issue is clearly reproducible on *any* computer. Thank you 🤗
