### ISSUE TITLE
How to train my own dataset?

### ISSUE THREAD

**Issue by Arsmart1** [huggingface/transformers#20187]
### Feature request

Could you privide a tutorial for training the whole model using my own dataset? I am a new learner and very confused. Thanks!

### Motivation

Could you privide a tutorial for training the whole model using my own dataset? I am a new learner and very confused. Thanks!

### Your contribution

Could you privide a tutorial for training the whole model using my own dataset? I am a new learner and very confused. Thanks!

**Comment by sgugger** [comment]
You could start by checking out the [course](https://huggingface.co/course/chapter1/1). Also please use the [forums](https://discuss.huggingface.co/) for questions like this, since we keep features for bugs and feature requests only.

You could start by checking out the [course](https://huggingface.co/course/chapter1/1). Also please use the [forums](https://discuss.huggingface.co/) for questions like this, since we keep features for bugs and feature requests only.

You could start by checking out the [course](https://huggingface.co/course/chapter1/1). Also please use the [forums](https://discuss.huggingface.co/) for questions like this, since we keep features for bugs and feature requests only.
