### ISSUE TITLE
Transformer cannot tokenize Chinese texts into correct words

### ISSUE THREAD

**Issue by fivehills** [huggingface/transformers#20285]
### System Info

Linux Debian,
bert-base-multilingual-cased,
bert-base-chinese

### Who can help?

@SaulLu
@LysandreJik
@ArthurZucker

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

from minicons import scorer
import torch
from torch.utils.data import DataLoader

import numpy as np

import json

model = scorer.MaskedLMScorer('bert-base-multilingual-uncased', 'cpu')

sentences = ["我 昨天 下午 我 就 是 直接 买 了 一份 那个 凉菜", "他们 那边 都 是 小 小葱 包括 重庆 那边"]

model.token_score(sentences, surprisal = True, base_two = True)

### Expected behavior

Hi everyone, 

A package called "minicons" (https://github.com/kanishkamisra/minicons) can extract word representations from contextualized word embeddings, and compute word probability in context. The package is based on Transformer language models. The transformer models, like "bert-base-multilingual-uncased" could be introduced in "minicons" help compute taken surprisal or probabilities for different languages if we have a text of this language as an input. This can be applied in English, German, Spanish and some alphabet-based languages.

However, it doesn't seem to work in Chinese. As you know, Chinese will be pre-processed with word segmentation (word segmentation by space). Despite this, if the input Chinese text is the one with word segments (two-character, or three and more character combination)), the output is still on the surprisal with an invididual Chinese character in the text rather than Chinese words.   This is very different from the outputs of English, German, Spanish and other alphabet-based languages.

I have checked with the code of the package "minicon". The package uses "self.tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast = True)" to tokenize the input text in one given language. I think that this tokenization method is fine because some Chinese transformer language models use the similar one, like "bert-chinese-base" (https://huggingface.co/bert-base-chinese?text=%E7%94%9F%E6%B4%BB%E7%9A%84%E7%9C%9F%E8%B0%9B%E6%98%AF%5BMASK%5D%E3%80%82).  The following is an example.

```python
from minicons import scorer
import torch
from torch.utils.data import DataLoader

import numpy as np

import json
```

```python
model = scorer.MaskedLMScorer('bert-base-chinese', 'cpu')
```

```python
sentences = ["他边 都 是 小 小葱 包括 重庆 那边"]
```

```python
model.token_score(sentences, surprisal = True, base_two = True)
```

```python
This is the real output.
    [[('他', 12.03427505493164),
      ('边', 15.405355453491211),
      ('都', 2.9198732376098633),
      ('是', 0.4283633828163147),
      ('小', 4.383847236633301),
      ('小', 8.884271621704102),
      ('葱', 19.068641662597656),
      ('包', 0.0020940606482326984),
      ('括', 8.549302101135254),
      ('重', 0.4292893409729004),
      ('庆', 3.0496609210968018),
      ('那', 3.522364377975464),
      ('边', 13.743260383605957)]]
```

```
The following is the desirable result. 
[[('他边', 12.03427505493164), 
  ('都', 2.9198732376098633),
  ('是', 0.4283633828163147),
  ('小', 4.383847236633301),
  ('小葱', 19.068641662597656),
  ('包括', 8.549302101135254),
  ('重庆', 3.0496609210968018),
  ('那边', 13.743260383605957)]]
```
This means that transformer seems not tokenize the input text properly.  What I want to get is the probability of each word ("小葱"，“那边” etc.) rather than a single character (“小”， “葱”， “那”， “边” etc.).

It will be greatly appreciated if you could kindly solve this problem.

Best,
Kevin

The following is the desirable result. 

[[('他边', 12.03427505493164), 
  ('都', 2.9198732376098633),
  ('是', 0.4283633828163147),
  ('小', 4.383847236633301),
  ('小葱', 19.068641662597656),
  ('包括', 8.549302101135254),
  ('重庆', 3.0496609210968018),
  ('那边', 13.743260383605957)]]
```

**Comment by sgugger** [comment]
cc @ArthurZucker

**Comment by fivehills** [comment]
> cc @ArthurZucker

Many thanks!

**Comment by ArthurZucker** [comment]
Hey!
For starters, would be great if you could have provided the example with `transformers` only code because we are not really aware of what might be going on inside `minicons`. Does it use the `fast` or `slow` tokenizer? What arguments are modified behind it etc.. 

My question here would be "What is the expected behavior of the `bert-base-chinese` model. The problem might just come from the tokenizer that is used, it might not correspond to your needs. In this case, it is expected that the characters are tokenized one by one. 
However if you use `tokenizer = AutoTokenizer.from_pretrained('bert-base-chinese', use_fast = False, tokenize_chinese_chars =False)`, you should get the expected results. 

```python 
>>> tokenizer.batch_decode(tokenizer(sentences).input_ids)
['[CLS] 他边 都 是 小 小葱 包括 重庆 那边 [SEP]']
```
You should either create a copy model with that parameter set or see with `minicons`

**Comment by ArthurZucker** [comment]
Hi, I am sorry but this goes outside the scope of `transformers`. I believe the issue was fixed as the * chinese text is correctly tokenized*  in transformers! 

The expected behaviour was matched in the example script I provided you with, and I have no idea what post processing might be done here that prevents the correct prediction. I think the issue should be open on their repo!
