### ISSUE TITLE
Sentence-transformer: No such file or directory error

### ISSUE THREAD

**Issue by Rolv-Arild** [huggingface/transformers#20310]
### System Info

Using the sentence-transformer widget leads to the following error at https://huggingface.co/NbAiLab/nb-sbert:
`[Errno 2] No such file or directory: '/data/NbAiLab_nb-sbert/1_Pooling/config.json'`
I have checked all the config files, and can not find any references to this. 
I am able to load the model locally (from the HF repo), and do valid calculations. The only thing that does not work is the widget.
I found this on the discussion forum: https://discuss.huggingface.co/t/sentence-similarity-demo-not-working/8711
Any idea about what is happening here?

### Who can help?

@Narsil @LysandreJik

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. Open https://huggingface.co/NbAiLab/nb-sbert
2. In the widget, use Example 1 or fill in sentences
3. Press "compute"

### Expected behavior

Widget providing sentence similarities

**Comment by Narsil** [comment]
Fixed now.

The culprit is either the way the api works or sentence-transformers, but `sentence-transformers` is not great at dealing with missing files (it looks only for 1 file and assumes the rest is there, leading to the failure you are seeing).

Since the API uses massive storage to handle all the models on the hub, there is periodical cleaning of unused files, and sometimes it happens that sentence-transformers doesn't access all the files at the same time, leading to only partial cleanup of sentence-transformers model files and to this error.

Hope you understand a bit better what happened.
For the fix we'll see about maybe adding something upstream, but can't make any promises.

**Comment by ashokgunturu** [comment]
I am also facing the same issue.

**Comment by Yaffa16** [comment]
I am having the same problem, did you find a solution to this?

**Comment by Deepak2405** [comment]
Hi, is there any solution for this problem? I am facing the same issue

**Comment by NesanSelvan** [comment]
I solved this issue by removing get_cache_dir() from the HuggingFaceEmbedding package in the following line: 
cache_folder = cache_folder or get_cache_dir(). 
It seemed to use the wrong cache location, and when I checked, the specified file location didn’t exist
