### ISSUE TITLE
Issue Importing Image Resolution Models

### ISSUE THREAD

**Issue by pravin-santhanam27** [huggingface/transformers#21228]
Hey Everyone,

I am tying to import a model from transformers for deblurring images.

I am on Python 3.10.9 and just install transformers 4.25.1

The error comes on import

`from transformers import AutoImageProcessor, Swin2SRForImageSuperResolution`

and the error is:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Swin2SRForImageSuperResolution' from 'transformers' (\env\lib\site-packages\transformers\__init__.py)`

These are the packages currently installed in my virtual environment

`certifi==2022.12.7
charset-normalizer==3.0.1
colorama==0.4.6
filelock==3.9.0
huggingface-hub==0.11.1
idna==3.4
numpy==1.24.1
opencv-python==4.7.0.68
packaging==23.0
Pillow==9.4.0
PyYAML==6.0
regex==2022.10.31
requests==2.28.2
tokenizers==0.13.2
torch==1.13.1+cu117
torchaudio==0.13.1+cu117
torchvision==0.14.1+cu117
tqdm==4.64.1
transformers==4.25.1
typing_extensions==4.4.0
urllib3==1.26.14`

**Comment by susnato** [comment]
Hi, @pravin-santhanam27 there seems to be a problem loading `Swin2SRForImageSuperResolution` with stable transformers(4.25.1) which we install from pypi. But this error is not present if you install from the source(4.26.0.dev0). This error is likely fixed in the source version(which is regularly updated) and will also be updated to stable release later. If you want to use it right now then please install `transformers` from source - `pip install git+https://github.com/huggingface/transformers`

**Comment by NielsRogge** [comment]
Will close this as the issue seems resolved.
