### ISSUE TITLE
Transformers `pipeline` documentation is missing text2text_generation pipeline

### ISSUE THREAD

**Issue by mathcass** [huggingface/transformers#21557]
**Is your feature request related to a problem? Please describe.**

I had the question, "How can I use the new Seq2Seq model I've trained in a Transformers pipeline?" There's pipeline tasks for summarization, generation, etc, but nothing listed on this page for how to use the model I've trained. (I'm training a T5 model.) https://huggingface.co/docs/transformers/v4.26.1/en/quicktour#pipeline

I discovered by digging into the source code that the pipeline I want is [text2text_generation](https://github.com/huggingface/transformers/blob/ea55bd86b9a452c87c5383afc707ab7d710a3043/src/transformers/pipelines/__init__.py#L272-L278).

**Describe the solution you'd like**
It'd be great if this pipeline were listed on https://huggingface.co/docs/transformers/v4.26.1/en/quicktour#pipeline

Is it intentionally omitted or is that just an oversight?

**Describe alternatives you've considered**

Digging into the source code solved my problem.

**Additional context**
NA

**Comment by sgugger** [comment]
cc @stevhliu and @MKhalusova

**Comment by stevhliu** [comment]
Thanks for the feedback! I left the `text2textgeneration` pipeline out intentionally because I didn't want to make the table in the Quicktour super long with all the supported pipelines (I think we have 25 pipelines now!). I intended for it to give you a quick idea of some of the example tasks you can do with the pipeline, and if you're interested in seeing all the supported tasks, you can check out the [Pipeline API Reference](https://huggingface.co/docs/transformers/main/en/main_classes/pipelines). 

I think there are two things we can do to improve:

1. List all the pipelines in the table for completeness.
2. Make it super clear this isn't a comprehensive list of all the pipelines; for that, you should head over to the Pipeline API docs.

**Comment by mathcass** [comment]
Thanks @stevhliu ! Useful to know that this was an intentional decision and that all the available pipelines are under the API reference. 

If you went with (1), that might help with completeness, but could be hard to keep up-to-date, since documentarians would need to remember to update. 

For the reason above, I like (2) more than (1). However, I would caveat it with the feedback that I think there's already too many items on the table currently. If you move forward with (2) by making it clear that more exist, I might recommend removing a few of them to trim it down.
