### ISSUE TITLE
Huge JSON file causes error in run_summarization.py

### ISSUE THREAD

**Issue by AtheerAlgherairy** [huggingface/transformers#21605]
I tried to run transformers\examples\pytorch\summarization\run_summarization.py with my own data files (in JSON Lines format).  The problem arises only when using huge JSON file (> 20 GB). With smaller size files it works normally. 

Any suggestions how to use the code with large size JSON files?

**Framework:**
 Transformers 4.20.1
 Pytorch 1.11.0+cu113
 Datasets 2.3.2
 Tokenizers 0.12.1

**Comment by ydshieh** [comment]
Hi @AtheerAlgherairy This is not a `transformers` issue, and it's very likely some memory issue due to the huge file size. [Hugging Face Forum](https://discuss.huggingface.co/) is the place for such kind of questions.

Without going into the specific detail, for large dataset like this, you should try to use iterator to avoid loading the whole file into the memory from the beginning.
