### ISSUE TITLE
[Time-Series] time-series patching

### ISSUE THREAD

**Issue by elisim** [huggingface/transformers#22075]
### Model description

"time-series patching" refers to the process of segmentation the series into subseries-level patches which are served as input tokens to the transformer. It's really similar to what's done in ViT, but for time-series. This idea was first propsed in a recent ICLR paper:

[A Time Series is Worth 64 Words: Long-term Forecasting with Transformers](https://arxiv.org/abs/2211.14730)
code: https://github.com/yuqinie98/PatchTST

@kashif @NielsRogge 

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available

### Provide useful links for the implementation

@yuqinie98

Edit: I think that "new model" is not the best label to this issue, maybe there is a better label for this?

**Comment by elisim** [comment]
PatchTST is in Gluon, thanks to @kashif . Closing here :) https://github.com/awslabs/gluonts/pull/2748

**Comment by yuqinie98** [comment]
Oh I apologize that I just notice this issue. Somehow I haven't seen it previously... And I appreciate so much for your attention on the PatchTST! Anything I could do for it?

**Comment by kashif** [comment]
@yuqinie98 not a problem... i will get PatchTST added to transformers next

**Comment by kashif** [comment]
@yuqinie98 also note that the model on gluonts is not exactly the patchTST implementation as your paper:
 - it doesn't carry the multivariate time series around but rather each entry in the batch is some random time series from the data
  - it is probabilistic 
  - the model is given the mean and std of the window of each time series as input (a bit like the non-stationary transformer) 
  - a lag variant (instead of `torch.unfold` is also implemented
  
  the points I raised in my email to you still stand with respect to the paper
