### ISSUE TITLE
AdamW implementation

### ISSUE THREAD

**Issue by StrangeTcy** [huggingface/transformers#22263]
### Feature request

I'm getting the warning from optimization (https://github.com/huggingface/transformers/blob/main/src/transformers/optimization.py, lines 391 and on): 
```
"This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch"
                " implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this"
                " warning"
```
How worried should I really be? Are there plans to use the torch AdamW version and eventually discarding your own implementation?

### Motivation

Presumably the torch.optim.AdamW implementation is better and using it would make the whole library a bit leaner

### Your contribution

Not sure

**Comment by amyeroberts** [comment]
Hi @StrangeTcy, thanks for raising this issue! 

Please don't be worried :) The warning is there so that there isn't any unexpected changes for users when `AdamW` is eventually removed from the library and is part of the deprecation cycle. We advise that the torch implementation is used instead of the one in the transformers library, and making this switch now in the relevant places in your code will ensure that nothing breaks when the time comes. Until then, the `AdamW` class will remain in transformers. 

One thing this warning is missing is specific information about when i.e. which version, this will happen and should be added!

**Comment by StrangeTcy** [comment]
Great, thanks. Looking forward to the next versions
