### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [huggingface/transformers#22688]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by sgugger** [comment]
We are using another platform for vulnerability reporting. @Michellehbn can tell you more.

**Comment by Michellehbn** [comment]
Hi @igibek ! Thanks for reaching out to us! 🤗 We have a bug bounty program with HackerOne and would love for you to submit security vulnerability reports to our private program at https://hackerone.com/hugging_face. Will it be possible to send us your H1 username or email address so that we can invite you to our program please, either here or to security@huggingface.co? Thanks again!

**Comment by gogo2464** [comment]
Hello @Michellehbn !

I found a crticial vulnerability in hugging face. Could you invite me to the private program please? I swear you will not regret it.
