### ISSUE TITLE
resume_from_checkpoint is not used in TrainingArguments

### ISSUE THREAD

**Issue by SingL3** [huggingface/transformers#23325]
### System Info

N/A

### Who can help?

@sgugger 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Just pass a `resume_from_checkpoint` to `TrainingArguments`.

### Expected behavior

I have read the code and I see `resume_from_checkpoint` is used for `Trainer.train(resume_from_checkpoint=...)`, and this setting in `TrainingArguments` is not used. Any reasons?

**Comment by amyeroberts** [comment]
@SingL3 In the [docs for TrainingArguments](https://huggingface.co/docs/transformers/v4.29.1/en/main_classes/trainer#transformers.TrainingArguments.resume_from_checkpoint), it notes that `resume_from_checkpoint` is intended to be used in your own training/evaluation scripts. In the original PR, [this was discussed and decided upon](https://github.com/huggingface/transformers/pull/11492#discussion_r622339347) in order to remove ambiguity.

**Comment by SingL3** [comment]
I see but it is somehow confusing. Closing this issue.
