### ISSUE TITLE
QuestionAnsweringPipeline is never able to truncate the question

### ISSUE THREAD

**Issue by Marcusntnu** [huggingface/transformers#23654]
### System Info

I was trying out feeding some in-context examples question side to the pipeline, and based on the design of the QuestionAnsweringPipeline it's basically impossible to get the truncation done at the question side and not the context. 

question_first = bool(self.tokenizer.padding_side == "right") in the [docs](https://huggingface.co/transformers/v4.6.0/_modules/transformers/pipelines/question_answering.html) makes sure that whatever you try it's not possible to get actual question truncation (unless you just write out a whole new pipeline basically). 

Think this should be easily fixable if you made it possible to "force" truncation=longest.

tagging @Narsil as it's pipeline related.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Setup whatever QAPipeline

1. Send a long question together with whatever context that would require truncation.
2. See: Exception: Truncation error: Sequence to truncate too short to respect the provided max_length

### Expected behavior

It should be possible to pass very long questions, at least if specifying truncation=longest (this just get's overrides now).

**Comment by Narsil** [comment]
Are you sure it' s OK to truncate questions ? For the actual results of the model ?

We can definitely add more control over the truncation process, currently it's quite hardcoded because of all the Squad specific controls: https://github.com/huggingface/transformers/blob/main/src/transformers/pipelines/question_answering.py#L409

We could switch to `tokenizer_kwargs` to allow any parameters to be passed.

@sgugger for confirmation it' s a good idea ?

**Comment by sgugger** [comment]
I don't think it is a good idea. This seems like a specific use-case for which you can use the tokenizer and model directly, instead of using the `pipeline`.

**Comment by Marcusntnu** [comment]
Understandable 👍
