### ISSUE TITLE
Add  MQTTS

### ISSUE THREAD

**Issue by susnato** [huggingface/transformers#24142]
### Model description

MQTTS is a Text to Speech model which was introduced in the paper [A Vector Quantized Approach for Text to Speech Synthesis on Real-World Spontaneous Speech](https://arxiv.org/pdf/2302.04215.pdf). Their work explore the use of more abundant real-world data for building speech synthesizers. It's architecture is designed for multiple code generation and monotonic alignment, along with the use of a clean silence prompt to improve synthesis quality.They show that MQTTS outperforms existing TTS systems in several objective and subjective measures.

I would like to add this model to HF.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

Implementation - https://github.com/b04901014/MQTTS
Checkpoints - 
1. Config - https://cmu.box.com/s/hvv06w3yr8mob4csjjaigu5szq2qcjab
2. Quantize - https://cmu.box.com/s/966rcxkyjps80p7thu0r6lo2udk1ezdm
3. Transformer model - https://cmu.box.com/s/xuen9o8wxsmyaz32a65fu25cz92a2jei

**Comment by susnato** [comment]
cc: @sanchit-gandhi and @ArthurZucker

**Comment by sanchit-gandhi** [comment]
I think this is a cool model - whether it outperforms Bark (#24086) is up for debate. My only concerns are:
1. The NC license which is not super permissive
2. The low-visibility of the original repo: with only 130 GH stars, it seems like the community is not super excited by the model (and thus are unlikely to use it in the library)

While the voice prompting feature would be cool and inference much faster than a hierarchical transformer model like Bark, I think the lack of visibility / excitement around the model means it would be a big effort to add with maybe little usage as a result

cc @Vaibhavs10 who has had more experience with MQTTS, @ylacombe who's adding Bark and @hollance who's adding VITS MMS

What do you all think?

**Comment by Vaibhavs10** [comment]
IMO for MQTTS - doesn't make as much sense, purely from a licensing standpoint. Plus it uses a non-standard quantizer, which makes it difficult to maintain (primarily because it'll be used only for MQTTS).

I think a more ambitious idea would be to add tortoise-tts - https://github.com/neonbjb/tortoise-tts (Was released a while back but still is the king) - the original repo is not as optimised so with the transformers bells and whistles we can make sure that it works faster and better?

Another idea would be to add StyleTTS - https://github.com/yl4579/StyleTTS, the results are quite promising and given there is training code as well, it opens up the opportunity to train a bigger model.

**Comment by sanchit-gandhi** [comment]
Tortoise TTS would probably go in the [`diffusers`](https://github.com/huggingface/diffusers) repo (since we could build it as a diffusion pipeline with a transformer encoder) - since the purpose of `diffusers` is more pure performance (which is not the objective of `transformers`) it would be a good fit here

**Comment by sanchit-gandhi** [comment]
Perfect, thanks @susnato! Going to close this then since we're in agreement that MQTTS is not a good addition for transformers. Tortoise TTS issue in diffusers: https://github.com/huggingface/diffusers/issues/3891
