### ISSUE TITLE
Protobuf 4 support (again)

### ISSUE THREAD

**Issue by dustyketchum** [huggingface/transformers#24323]
### Feature request

Looking at https://github.com/huggingface/transformers/issues/21677#issuecomment-1435072007, I notice there are now new versions of tensorflow and tensorboard that may help with protobuf 4.x compatibility.  It would be awesome to get this upgraded, thanks!

### Motivation

easier upgrade path to python 3.10 and above

### Your contribution

nope, sorry.

**Comment by amyeroberts** [comment]
Hi @dustyketchum, 

Thanks for raising this issue. Managing the different dependencies in the library can be quite complex. As noted in the linked issue, the blocker for upgrading protobuf support was third-party libraries support of protobuf 4 rather than our own. 

If this is something you or someone else in the community believes is very important, please feel free to open a PR. Note that it's not just necessary for the CI to be green and protobuf 4 be supported, we must also remain backwards compatible with previous versions.

cc @ydshieh

**Comment by ydshieh** [comment]
BTW, what's blocking when you try to use python 3.10 without protobuf 4.x ?

**Comment by dustyketchum** [comment]
I am not blocked; I should have been more precise.

**Comment by ydshieh** [comment]
Fixed in #24599
