### ISSUE TITLE
RuntimeError: index out of range: Tried to access index 512 out of table with 511 rows.

### ISSUE THREAD

**Issue by supremepoison** [huggingface/transformers#2446]
## ❓ Questions & Help

I am receiving the error RuntimeError: index out of range: Tried to access index 512 out of table with 511 rows.
What can I do to increase this source sentence length constraint?

<img width="1316" alt="Screen Shot 2020-01-08 at 2 01 49 pm" src="https://user-images.githubusercontent.com/44693666/71954228-8ed63780-321f-11ea-84ef-eac4519235c4.png">

**Comment by LysandreJik** [comment]
Different models have different sequence lengths. Some models don't, like XLNet and TransformerXL.

**Comment by esbeneickhardt** [comment]
I have the same error.

**Comment by ogencoglu** [comment]
Quick reminder: Limit of 512 is not word limit, it is token length limit as BERT models do not use words as tokens. You always have more tokens than number of words.

You can divide the text into half and then pool afterwards even though this is not exactly the same as having the whole thing and then pooling.

**Comment by bpben** [comment]
Related to this: Using tokenizer.encode_plus(doc) gives a sensible warning:

`Token indices sequence length is longer than the specified maximum sequence length for this model (548 > 512). Running this sequence through the model will result in indexing errors`

And still outputs a token id sequence.  But tokenizer.batch_encode_plus  just throws the IndexError.  Seems like the behavior should be similar? Otherwise, for sequences that may contain documents longer than 512 tokens, it seems like there's no way to use batch_encode_plus.

Also: It seems like there should be an option for truncating sequences automatically.

**Comment by shravankoninti** [comment]
Hi All,

I am running a Roberta Model for predicting the sentence classification task. I am using Fastai implementation of it. I get a similar error as mentioned  above.  Please help me resolve this.


![fast_er_1](https://user-images.githubusercontent.com/6191291/81206700-1d01d500-8fea-11ea-8964-86298ad231cd.JPG)

**Comment by esbeneickhardt** [comment]
Check if you texts are longer than 512 characters, and if so the error is
expected.

Solutions:
1. Only use the first 512 characters of each text.
2. Divide you texts into chunks of 512 characters and make embeddings on
each chunk
