### ISSUE TITLE
LLamaTokenizer padding_side='left'

### ISSUE THREAD

**Issue by davidmrau** [huggingface/transformers#24522]
Trying to Fine-tune the LLama model I encountered that the LLama tokenizer adds padding tokens on the left side by default. I expect the padding to be added to the right side. Is this a bug or supposed to be like this?

https://github.com/huggingface/transformers/blob/6fe8d198e3e30b709a7d233240f273804b886dcc/src/transformers/models/llama/tokenization_llama_fast.py#L85C5-L85C5

**Comment by sgugger** [comment]
Please ask questions like this on the [forums](https://discuss.huggingface.co/) as we keep issues for bugs and feature requests only.

All decoder models use padding on the left side since they can't properly generate the next token after a sentence if it ends with pad tokens. Llama is a decoder model, so follows the same rule.
