### ISSUE TITLE
Adding gpu devices to Trainer.train

### ISSUE THREAD

**Issue by Ofir408** [huggingface/transformers#25321]
### Feature request

It would be helpful to extend the `train` method of the `Trainer` class with additional parameters to specify the GPUs devices we want to use during training. This extension can be implemented by setting the environment variable ``CUDA_VISIBLE_DEVICES`` appropriately before the training process begins.

### Motivation

Greater flexibility in specifying the GPUs or devices they want to use during model training. This enhancement simplifies the process of training models on specific hardware configurations, making it more accessible and convenient for users to leverage available resources efficiently.

### Your contribution

I can submit a PR if you prefer.

**Comment by amyeroberts** [comment]
@Ofir408 thanks for raising this feature request!

> This extension can be implemented by setting the environment variable CUDA_VISIBLE_DEVICES appropriately before the training process begins.

It's already possible to set the GPUs used during training with the `CUDA_VISIBLE_DEVICES` argument. See the docs here: https://huggingface.co/docs/transformers/main_classes/trainer#specific-gpus-selection

**Comment by Ofir408** [comment]
@amyeroberts Thank you for your answer. I know it's possible, but I think it will be more convenient if we add this parameter to the `train` method of `Trainer`. What do you think?

**Comment by muellerzr** [comment]
Yes, this isn't really going to be possible, it has to be set before `torchrun` or `accelerate launch` is performed, otherwise nothing will really happen. See below where I tried setting `CUDA_VISIBLE_DEVICES` before spinning up torch distributed via `Accelerate`'s `PartialState`:

```python
import os
from accelerate import PartialState

os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"
state = PartialState()
print(state)
```

Running via:
```bash
torchrun --nproc_per_node 4 test.py`

Output:
```python
Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 4
Process index: 1
Local process index: 1
Device: cuda:1

Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 4
Process index: 3
Local process index: 3
Device: cuda:3

Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 4
Process index: 2
Local process index: 2
Device: cuda:2

Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 4
Process index: 0
Local process index: 0
Device: cuda:0
```

So you must set it either when running `torchrun`, or when doing `accelerate config` it will prompt and ask if there are device ID's you'd like to run
