### ISSUE TITLE
Model to be adjusted

### ISSUE THREAD

**Issue by L4EPITTMSU** [huggingface/transformers#25610]
https://github.com/huggingface/transformers/blob/6b82d936d49956ba7b43c5ee590f4868de373b65/src/transformers/models/big_bird/modeling_big_bird.py#L977

getting this issue: 
/opt/software/Python/3.6.4-foss-2018a/lib/python3.6/site-packages/transformers/models/big_bird/modeling_big_bird.py:978: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  * num_indices_to_pick_from

**Comment by mayank2130** [comment]
If you're using a recent version of the transformers library, it should eventually be updated to address this issue.
This warning is indicating that the behavior of floordiv is deprecated and will change in a future version of PyTorch.
import torch

# Instead of this
result = torch.floordiv(a, b)

# Use this
result = torch.div(a, b, rounding_mode='floor')

**Comment by ArthurZucker** [comment]
It's not an issue but a warning, and since you do not have a reproducer I can't reproduce it. Given the warning, I am not entirely sur there anything to do here, we are already using :
> for actual floor division, use torch.div(a, b, rounding_mode='floor').

**Comment by mayank2130** [comment]
Yeah, the intention was to say it was a warning. Maybe wrong choice of words there.
@ ArthurZucker
