### ISSUE TITLE
AttributeError: 'CTCTrainer' object has no attribute 'scaler'

### ISSUE THREAD

**Issue by aprzez** [huggingface/transformers#25618]
When attempting to fine-tune Wav2Vec2 XLSR on my own dataset I get this error once training starts: "AttributeError: 'CTCTrainer' object has no attribute 'scaler'"

I followed the steps outlined here and as far as I can tell have all the necessary packages installed in my conda environment: https://github.com/huggingface/transformers/blob/main/examples/research_projects/wav2vec2/FINE_TUNE_XLSR_WAV2VEC2.md#local-machine
The only change to the run_common_voice.py file is that I am loading my own data from a CSV.

**Comment by ArthurZucker** [comment]
cc @sanchit-gandhi

**Comment by sanchit-gandhi** [comment]
Hey @aprzez - the examples script referenced is quite outdated and no longer maintained. It uses the Hugging Face Trainer **prior** to the recent `accelerate` upgrade in v4.30.0. As such, it is not guaranteed to work out of the box, since it requires updating for the new HF Trainer internals.

I would recommend you either:
1. Downgrade your `transformers` version to <4.30 (less optimal, you won't get the latest features from the last releases)
2. Use the latest version of `transformers`, but with the **updated** and maintained examples script [`run_speech_recognition_ctc.py`](https://github.com/huggingface/transformers/tree/main/examples/pytorch/speech-recognition#connectionist-temporal-classification) (more optimal - we maintain this and ensure it works with the latest `transformers` versions!)
