### ISSUE TITLE
Remove usage of warnings.warn

### ISSUE THREAD

**Issue by osanseviero** [huggingface/transformers#26381]
Usage of `warnings.warn` has been deprecated in favor of `logging.warning`, which is managed by the `transformers.logging` utility. 

* https://github.com/search?q=repo%3Ahuggingface%2Ftransformers+%22warnings.warn%22&type=code
* https://github.com/search?q=repo%3Ahuggingface%2Ftransformers%20UserWarning&type=code

`warnings.warn` may still be leveraged for situations where a single warning per runtime is favored, but this will be deprecated in the future as well.

**Comment by sahilbhosale63** [comment]
Hi @osanseviero I want to work on this issue. Can you please this issue to me so that I can start working on it?

**Comment by Adithya4720** [comment]
I have completed the task referenced as PR #26389

**Comment by ydshieh** [comment]
If I understand correctly, we should use `logger.warning` where `logger = logging.get_logger(__name__)` ?

**Comment by Adithya4720** [comment]
I can work on this!!

**Comment by sachinSingh16-09** [comment]
hey @osanseviero, I have started solving the issue. Please assign this issue to me.

**Comment by riiyaa24** [comment]
Hello, Can I work on this issue? Can you please assign me this?

**Comment by LysandreJik** [comment]
Hello, we have worked on a different approach with Omar that will not require us to change all `warnings` to `logging` statements.

I'm opening a PR here implementing it: https://github.com/huggingface/transformers/pull/26527

However, in order to honor the contributions you have wanted to make (or have already started making!), I have put you all five as co-authors of the commit, @sahilbhosale63, @Adithya4720, @sachinSingh16-09, @riiyaa24.

I have added the `HACKTOBERFEST-ACCEPTED` tag in case you're participating.

Thanks once again for your contribution, and we're looking forward to the next one :hugs:

**Comment by Adithya4720** [comment]
Thanks!!

**Comment by AVAniketh0905** [comment]
Is this still open?

**Comment by LysandreJik** [comment]
It will be closed by https://github.com/huggingface/transformers/pull/26527 @AVAniketh0905
