### ISSUE TITLE
support for MistralForCausalLM

### ISSUE THREAD

**Issue by NarenZen** [huggingface/transformers#26458]
### Feature request

Mistral AI claims its supports VLLM. 
`python -u -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --model mistralai/Mistral-7B-v0.1`

But getting error:
`ValueError: Model architectures ['MistralForCausalLM'] are not supported for now. Supported architectures: ['AquilaModel', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'FalconForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MPTForCausalLM', 'OPTForCausalLM', 'QWenLMHeadModel', 'RWForCausalLM']`

**Comment by LysandreJik** [comment]
Hey @NarenZen, `Mistral` is on the `main` branch and not in a stable release until early next week.

Would you mind installing `transformers` from source until then? You can do so with:
```
pip install git+https://github.com/huggingface/transformers
```

Please let me know if you run into any issues!

**Comment by AlexDut** [comment]
Hey,

By installing `transformers` using the [commit](https://github.com/huggingface/transformers/commit/72958fcd3c98a7afdc61f953aa58c544ebda2f79) for the Mistral support you can get the model work:

`pip install git+https://github.com/huggingface/transformers@72958fc`

If you install from `main` you might encounter unrelated issues due to continuous developments on that branch.

**Comment by LysandreJik** [comment]
The `main` branch should be quite stable though :)
