### ISSUE TITLE
Support download of models from Torrent 

### ISSUE THREAD

**Issue by filopedraz** [huggingface/transformers#26715]
### Description

Support models download from Torrent passing as a parameter in the `AutoTokenizer` and `AutoModel` class `magnet_url`.

### Example Usage

```python
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("magnet:?xt=urn:btih:XXXXXX")
model = AutoModel.from_pretrained("magnet:?xt=urn:btih:XXXXXX")

inputs = tokenizer("Hello world!", return_tensors="pt")
outputs = model(**inputs)
```

### Motivation

Models could be censored and removed from HF. In order to keep them alive, Torrent could be a solution.

### Your contribution

I can do a POC of the implementation using a model mirrored from HF to Torrent.

**Comment by ngv-sama** [comment]
Hi! I'm new to open source, can you please help me understand the issue better? I understand I have to show a POC for this, but has this functionality already been implemented, or would I have to make it myself? 
Thank You in Advance!

**Comment by ArthurZucker** [comment]
Hey! This is currently not planned 🤗

**Comment by tsilvs** [comment]
That would be much better than the current `git lfs clone` way.

Today I've spent several hours downloading a model that had about 64 GiB of pytorch weights, and after 72 GiB of GIT LFS downloading it still was on 14%.

This is just unusable.

**Comment by LysandreJik** [comment]
Hey @tsilvs, for a while we've been recommending the HTTP way to download models rather than the `git lfs clone`, which is, as you have seen, much slower. Read about it here: https://huggingface.co/docs/huggingface_hub/concepts/git_vs_http#what-should-i-use--and-when-

Additionnally, you may be interested in [this guide](https://huggingface.co/docs/huggingface_hub/v0.22.0/en/guides/download#faster-downloads) which goes over optimizing downloads for speeds using the `hf-transfer` utility to take advantage of your full bandwidth.
