### ISSUE TITLE
NEFTune Support pls

### ISSUE THREAD

**Issue by nivibilla** [huggingface/transformers#26899]
### Feature request

The TRL library introduced support for NEFTune in this [pr](https://github.com/huggingface/trl/pull/871) 

### Motivation

Improves Supervised Fine-tuning performance

See paper : https://arxiv.org/abs/2310.05914

### Your contribution

I can try to port code over from TRL.

**Comment by LysandreJik** [comment]
@younesbelkada could you share a bit about how one could go about leveraging NEFTune with `transformers` models?

I think it's important that the two frameworks complete each other rather than compete for the same features with differing implementations, so let's take a look at leveraging TRL simply for `transformers` models rather than importing the implementation within `transformers`.

**Comment by younesbelkada** [comment]
currently in TRL we monkey-patch the forward pass of the emebdding layer with a new one, but with https://github.com/huggingface/trl/pull/889 we'll have a cleaner implementation that leverage forward post hooks which is cleaner. I will open a PR to add that feature in Trainer and leverage that feature in TRL
