### ISSUE TITLE
Rating on NVIDIA A30 GPU is lower than RTX2080 and equal to GTX1070

### ISSUE THREAD

**Issue by ThangPetros** [huggingface/transformers#27075]
### Model description

Currently I'm evaluating a model on HuggingFace, it's called model_name = 'nguyenvulebinh/wav2vec2-base-vi'

When running on GTX1070, I evaluated the average result between audio track time and text conversion time and the result was 63x
With RTX2080 it is 130x
As for the A30, it is 68x

Is there any conflict and why the A30 should have achieved the highest results but it did not meet expectations!

I'm a newbie so I really hope for help from everyone

Thank!
```python
#!pip install transformers==4.20.0
#!pip install https://github.com/kpu/kenlm/archive/master.zip
#!pip install pyctcdecode==0.4.0
#!pip install huggingface_hub==0.10.0

from transformers.file_utils import cached_path, hf_bucket_url
from importlib.machinery import SourceFileLoader
from transformers import Wav2Vec2ProcessorWithLM
from IPython.lib.display import Audio
import torchaudio
import torch

# Load model & processor
model_name = "nguyenvulebinh/wav2vec2-large-vi-vlsp2020"
model = SourceFileLoader("model", cached_path(hf_bucket_url(model_name,filename="model_handling.py"))).load_module().Wav2Vec2ForCTC.from_pretrained(model_name)
processor = Wav2Vec2ProcessorWithLM.from_pretrained(model_name)

# Load an example audio (16k)
audio, sample_rate = torchaudio.load(cached_path(hf_bucket_url(model_name, filename="t2_0000006682.wav")))
input_data = processor.feature_extractor(audio[0], sampling_rate=16000, return_tensors='pt')

# Infer
output = model(**input_data)

# Output transcript without LM
print(processor.tokenizer.decode(output.logits.argmax(dim=-1)[0].detach().cpu().numpy()))

# Output transcript with LM
print(processor.decode(output.logits.cpu().detach().numpy()[0], beam_width=100).text)`
```
### Open source status

- [X] The model implementation is available
- [ ] The model weights are available

**Comment by ArthurZucker** [comment]
Hey, the model you are using seems to be using `SourceFileLoader` , and custom code.
First I would recommend you to use `trust_remote_code = True` and properly register your model to avoid using `model = SourceFileLoader("model", cached_path(hf_bucket_url(model_name,filename="model_handling.py"))).load_module().Wav2Vec2ForCTC.from_pretrained(model_name)
p`. 
Now you have custom code and I can't debug it for you. If you find that the models we natively supports are indeed slower on better hardwares we could dig in but otherwise would recommend you to ask on the [forum](https://discuss.huggingface.co/) instead as we reserve github for issues or bugs.
