### ISSUE TITLE
Speculative decoding functionality

### ISSUE THREAD

**Issue by domgri** [huggingface/transformers#27186]
### Feature request

Hey 👋 

Idea is to add speculative decoding functionality in assisted generation code path. There are several similar ways how that can be achieved.

Related papers: 
* [Blockwise Parallel Decoding](https://proceedings.neurips.cc/paper/2018/file/c4127b9194fe8562c64dc0f5bf2c93bc-Paper.pdf), by Google Brain
* [Speculative Sampling](https://arxiv.org/abs/2302.01318), by DeepMind
* [Fast Inference from Transformers via Speculative Decoding](https://arxiv.org/pdf/2211.17192.pdf)

### Motivation

- Shows promising inference time improvements.
- Would enable faster expermentation with various models.
- Could become a fundamental place for more elaborate experimentation of speculative decoding.

Related issues/discussions: #26565

Related blog post explaining current assisted generation implementation and its (improvements and) limitations: [here](https://huggingface.co/blog/assisted-generation) by @gante 

### Your contribution

I would like to give an attempt and rase a PR for this (e.g. for Google Brain implementation).

Although, might need some help with:

- Deciding which approach to implement
- Decision for code architecture - either combine with assisted generation, partially combine or implement separately
- Motivation - maybe I am only one interested in this idea 😊 

Any feedback would be greatly appreciated 🙇‍♂️

**Comment by amyeroberts** [comment]
Interesting! @gante WDYT?

**Comment by gante** [comment]
Hi @domgri 👋 

I'm very interested in having DeepMind's Speculative decoding when `do_sample=True`, in `assisted_generation`! It should only need a few extra if/elses, to handle the clever token acceptance strategy they came up with :)

As for the others, since they don't seem to bring additional benefits, I would like to avoid adding them -- maintaining different generation methods takes up a significant amount of time, so they need to bring benefits for us to justify adding them to the codebase. 

Finally, FYI, I'm trying to design a strategy for issues like this one: some way to leverage the Hub to add new generation methods than don't need to be approved (or maintained) by the transformers team 🙌

**Comment by domgri** [comment]
Thanks for a quick and encouraging feedback!

Then for now I will focus on DeepMind's Speculative decoding and see how it goes 🙌. Though, will be interested to see the outcome of strategy question as well 👍.
