### ISSUE TITLE
bus error when load codellama2 34b

### ISSUE THREAD

**Issue by boundles** [huggingface/transformers#27391]
### System Info

when I load model on 2*A6000 45G, bus error occurs

`model_path = 'CodeLlama-34b-hf'
model = AutoModelForCausalLM.from_pretrained(model_path, load_in_8bit=True, device_map="auto", trust_remote_code=True)
print('finish load model')
`

looking for your reply, thanks

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

run the code

### Expected behavior

load successfully

**Comment by amyeroberts** [comment]
Hi @boundles, thanks for raising an issue. 

So that we can best help you, can you make sure to follow the [issue template](https://github.com/huggingface/transformers/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml) and include all important information such as: 
* The running environment: run `transformers-cli env` in the terminal and copy-paste the output
* A minimal code snippet we can run to reproduce the error
* Full details of the error encountered, including full traceback
