### ISSUE TITLE
How to get input sentence embedding from Llama or Llama2?

### ISSUE THREAD

**Issue by waterluck** [huggingface/transformers#27600]
I'm trying to get the sentence embedding that I input, I checked some common practice to do it, but I'm not sure I'm doing the it right. Who may be help?  @gante  Thanks if you can be help. my code is as below: 

```
 model = LlamaForCausalLM.from_pretrained(
    args.pretrained_name_or_path,
    torch_dtype=torch.float16,
    device_map=device,
)
tokenizer = LlamaTokenizer.from_pretrained(args.pretrained_name_or_path, fast_tokenizer=True)
model.to(device)
model.eval()
tokenizer.pad_token_id = 0
tokenizer.padding_side = "left"

for i in range(0, len(sentences), batch_size):
    batch_sentences = sentences[i: i+batch_size]
    inputs = tokenizer(batch_sentences, padding=True, truncation=False, return_tensors='pt')
    inputs = inputs.to(device)

    with torch.no_grad():
        outputs = model(**inputs, output_hidden_states=True)
        hidden_states = outputs.hidden_states[-1]
        sentence_embeddings = hidden_states[:, -1, :]   # # here is using the **last token's** last layer hidden states as sentence embeddings,
        # or  sentence_embeddings = outputs.hidden_states[-1].mean(dim=1) # here use average sentence embedding. 
        # and I'm not sure which one is better.
        embeddings.append(sentence_embeddings.cpu())

embeddings = torch.cat(embeddings, dim=0)
```

And I found that in this way, if I use this to get the input sentence's embedding ,  and compare it with the generated output's embedding by using ' token's embedding`model.generate(**input, output_hidden_states=True, max_new_token=1)` , in each layer, they are nearly the same, with cosine similarity 0.99. I'm confusing why.

**Comment by gante** [comment]
Hey @waterluck 👋 

Following our [issues guidelines](https://github.com/huggingface/transformers/blob/main/ISSUES.md), we reserve GitHub issues for bugs in the repository and/or feature requests. For any other matters, we'd like to invite you to use our [forum](https://discuss.huggingface.co/) or our [discord](https://discord.com/invite/hugging-face-879548962464493619) 🤗 If you still believe there is a bug in the code, check [this guide](https://huggingface.co/course/chapter8/5?fw=pt).

Since this is your first issue with us, I'm going to share a few pointers:
1. To get the best embeddings, models trained to embed the whole sentence should be used, not standard generative LLMs. See our [sentence similarity task page](https://huggingface.co/tasks/sentence-similarity) and check out the `sentence-transformers` repo
2. If you want to use an LLM, I'd say to average the hidden states for all the tokens, not simply for the last token (as you have in your commented code)

**Comment by waterluck** [comment]
@gante Well noted the issue guidelines, I'll follow them next time! 
Also great thanks for your kindness in sharing which embedding should be used in by using LLMs. That's helped a lot!
