### ISSUE TITLE
RuntimeError: Could not infer dtype of JpegImageFile

### ISSUE THREAD

**Issue by realbigi** [huggingface/transformers#27739]
### System Info

transformers, windows 11, python 3.11.6

I have been trying to replicate this https://huggingface.co/docs/transformers/tasks/image_classification image classification with PyTorch. But when I run the skript I get this error:

RuntimeError: Could not infer dtype of JpegImageFile

Does anyone have an idea what the problem could be?

### Who can help?

@amyeroberts

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

https://github.com/realbigi/Classifier_2_Pytorch_Image_Classification

### Expected behavior

It should train on the data without a mistake

**Comment by amyeroberts** [comment]
Hi @realbigi, thanks for raising an issue! 

The error itself is arising because torch can't decode jpeg files. From the notebook, it's not immediately obvious what's happening, as the images should be opened as PIL.Image.Image. I can see there was an error reading in the dataset and some of the cells have been run out of order. Because of the statefulness of notebooks, it is therefore difficult to debug wrt to the error message. Could you update the notebook so that each cell has been executed in order?

**Comment by realbigi** [comment]
Hi @amyeroberts 

I just executed the notebook in order and reuploaded it. But you should be able to run it anyways as I uploaded the data as well to GitHub. Could the problem arise because there are webp images instead of jpeg's? Altough I don't think that is the problem because they were converted to PIL objects right?

**Comment by realbigi** [comment]
@amyeroberts 

I must have made a mistake while copying the code. I downloaded the original notebook and loaded my data and it seems to work.

**Comment by ArthurZucker** [comment]
Thanks for clarifying ! 🤗
