### ISSUE TITLE
add system prompt option in .apply_chat_template()

### ISSUE THREAD

**Issue by ONE-THING-9** [huggingface/transformers#27922]
### Feature request

Currently, I cannot find the option of adding a system prompt while doing tokenizer.apply_chat_template().

### Motivation

Because of this I have to avoid using apply_chat_template

### Your contribution

we can add this in {'role':'system'..........}

**Comment by ArthurZucker** [comment]
Hey, I think it already supports this! see [here](https://huggingface.co/docs/transformers/chat_templating) (you just need to customize the roles)

**Comment by ONE-THING-9** [comment]
Got it, i missed that.

**Comment by ArthurZucker** [comment]
Thanks for the feedback! cc @Rocketknight1 if that's something you noticed

**Comment by Rocketknight1** [comment]
Hi @unoriginalscreenname - unfortunately, this is an unavoidable consequence of how these models were trained. Some models were trained with system prompts as part of the training data, and other models were not. When a model was not trained with a system prompt, it will not have any tokens that it can use to represent a system prompt, and trying to insert a prompt will confuse the model and probably significantly reduce the output quality.

In the cases when a model was trained without a system prompt, the model's chat template can be configured to raise an error if a `system` message is included in the input, and this is indeed what happens with some models (e.g. LLaMA/Mistral/Mixtral). This is correct and intended behaviour, and there isn't really any way to "fix" it without retraining the models!

The only solution I can suggest is that there is usually a different fine-tune of most models that supports a system prompt. For example, instead of Mistral-instruct you can use [Zephyr-beta](https://huggingface.co/HuggingFaceH4/zephyr-7b-beta), and instead of Mixtral-instruct you can use [Dolphin](https://huggingface.co/cognitivecomputations/dolphin-2.7-mixtral-8x7b). Both of these models were trained with system prompts, and will understand them correctly (and apply them in their chat template).

**Comment by arunpatala** [comment]
hi I am also facing a similar problem, where I am using llama 3.1 8B instruct model. I am finetuning using lora models, but there is no way to disable adding the system prompt when finetuning the model, using apply_chat_template to create the text data. I donot want to use system prompt, as I using another library for inference that doesnt need adding system prompts. Is there an easier way than writing custom chat template. Like a flag use_system_prompt=False.

**Comment by mohsenhariri** [comment]
`use_system_prompt=False` is also helpful when using `chat_template` multiple times, e.g. for CoT and then appending another text
