### ISSUE TITLE
Problems importing LlavaForConditionalGeneration

### ISSUE THREAD

**Issue by ppsmk388** [huggingface/transformers#27936]
### System Info

transformers version: 4.35.2
Platform: Linux-5.10.0-26-cloud-amd64-x86_64-with-glibc2.31
Python version: 3.9.2
Huggingface_hub version: 0.19.4
Safetensors version: 0.4.1
Accelerate version: 0.25.0
PyTorch version (GPU?): 2.1.1+cu121 (True)

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import  LlavaForConditionalGeneration

### Expected behavior

An error message will be displayed:
ImportError: cannot import name 'LlavaForConditionalGeneration' from 'transformers' (/data/kkk/anaconda3/envs/va/lib/python3.9/site-packages/transformers/__init__.py)

**Comment by ArthurZucker** [comment]
Hey! 👋 llava is no part of the latest release! You need to install from source or wait until tomorrow! 🤗

**Comment by ppsmk388** [comment]
ok, thank you for your reply

**Comment by Albert337** [comment]
> ### System Info
> transformers version: 4.35.2 Platform: Linux-5.10.0-26-cloud-amd64-x86_64-with-glibc2.31 Python version: 3.9.2 Huggingface_hub version: 0.19.4 Safetensors version: 0.4.1 Accelerate version: 0.25.0 PyTorch version (GPU?): 2.1.1+cu121 (True)
> 
> ### Who can help?
> _No response_
> 
> ### Information
> * [x]  The official example scripts
> * [ ]  My own modified scripts
> 
> ### Tasks
> * [x]  An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
> * [ ]  My own task or dataset (give details below)
> 
> ### Reproduction
> from transformers import LlavaForConditionalGeneration
> 
> ### Expected behavior
> An error message will be displayed: ImportError: cannot import name 'LlavaForConditionalGeneration' from 'transformers' (/data/kkk/anaconda3/envs/va/lib/python3.9/site-packages/transformers/**init**.py)

Have you solved the problem? i met the error no matter i reinstalled the bag version of transformers or install it from source.
<img width="576" alt="image" src="https://github.com/user-attachments/assets/0c195dc4-1f8b-45ae-9e43-8a28c5fe2eac">

**Comment by ArthurZucker** [comment]
you have a typo: 
```diff
- LLava
+ Llava
```

**Comment by CurryFlink** [comment]
Llava works.

but i think why people has this problem is because in this page:
https://huggingface.co/docs/transformers/model_doc/llava#overview

Batched inference part show two wrong examples, 

Batched inference
LLaVa also supports batched inference. Here is how you can do it:

Copied
import requests
from PIL import Image
import torch
from transformers import AutoProcessor, LLavaForConditionalGeneration

# Load the model in half-precision
model = LLavaForConditionalGeneration.from_pretrained("llava-hf/llava-1.5-7b-hf", torch_dtype=torch.float16, device_map="auto")
processor = AutoProcessor.from_pretrained("llava-hf/llava-1.5-7b-hf")

you can see there is LLavaForConditionalGeneration not Llava

**Comment by ArthurZucker** [comment]
Indeed! Do you want to open a PR for a fix?
