### ISSUE TITLE
Supoport batch image processing

### ISSUE THREAD

**Issue by wcy1122** [huggingface/transformers#28008]
### Feature request

A faster image processing which supports batch image processing, especially for input data like video.

### Motivation

The speed of image processing is too slow if the amount of image is large.

> 

### Your contribution

The image processor like CLIPImageProcessor processes each image sequentially, which makes it very slow.

**Comment by ydshieh** [comment]
The input images are not necessary homogenous (unlike a tensor with batch dimension along which the elements are the same format).

You can definitely use `datasets` batch processing feature to speedup the  task.

cc @amyeroberts to see if they has any further suggestion/comment.

**Comment by amyeroberts** [comment]
Hi @wcy1122, thanks for raising this feature request! 

As @ydshieh highlights, because the input images can be of different sizes and formats, and making them batchable may or may-not happen depending on the processor's configuration. Using `map` alongside `datasets` is a great way to parallize this process.

The image processors are, admittedly and unfortunately, very slow. Their principle purpose is to make it as easy as possible to go from an image to inputs which can be fed to the model i.e. a user can quickly test and get a prediction. 

Part of the reason for not engineering a highly-performant image processing library is that many great libraries already exist. You'll notice that in our training examples for vision models, [we use torchvision](https://github.com/huggingface/transformers/blob/3060899be51fe1a96b12de97376f2e2b8315bc4c/examples/flax/vision/run_image_classification.py#L338) for this very reason.

**Comment by wcy1122** [comment]
Get it. Thanks for the reply and suggestion.

**Comment by ldh127** [comment]
> Hi @wcy1122, thanks for raising this feature request!
> 
> As @ydshieh highlights, because the input images can be of different sizes and formats, and making them batchable may or may-not happen depending on the processor's configuration. Using `map` alongside `datasets` is a great way to parallize this process.
> 
> The image processors are, admittedly and unfortunately, very slow. Their principle purpose is to make it as easy as possible to go from an image to inputs which can be fed to the model i.e. a user can quickly test and get a prediction.
> 
> Part of the reason for not engineering a highly-performant image processing library is that many great libraries already exist. You'll notice that in our training examples for vision models, [we use torchvision](https://github.com/huggingface/transformers/blob/3060899be51fe1a96b12de97376f2e2b8315bc4c/examples/flax/vision/run_image_classification.py#L338) for this very reason.

yes， i use the dataset map with multiprocess to process CLIPImageProcessor, but when data process finished , the program hang, it seems that wait for something, long long time after, it is over because the time error , can you help to give a good example?
