### ISSUE TITLE
CircleCI doesn't run slow tests

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#2800]
circle_ci.cfg says `RUN_SLOW: yes`, but all my circleci runs have the slow tests skipped.
Is this expected behavior?
@LysandreJik

**Comment by LysandreJik** [comment]
When deploying on CircleCI, it runs the `build_and_test` job, which runs the [following suites](https://github.com/huggingface/transformers/blob/master/.circleci/config.yml#L126-L133).

The slow tests are ran by the `run_all_tests_torch_and_tf` suite, which only triggers [weekly](https://github.com/huggingface/transformers/blob/master/.circleci/config.yml#L137). 

The slow tests are especially slow, and currently fail on CircleCI because the machines can't run for so long. We're exploring options to run them on a specific machine cc @julien-c

**Comment by sshleifer** [comment]
Got it, thanks. Can I delete this line  https://github.com/huggingface/transformers/blob/81d6841b4be25a164235975e5ebdcf99d7a26633/.circleci/config.yml#L23

it confused me.

**Comment by LysandreJik** [comment]
If you remove this line the slow tests won't run during the weekly tests though

**Comment by sshleifer** [comment]
Oh I get it, was missing
`run_all_tests_torch_and_tf` vs `run_tests_torch_and_tf`

**Comment by julien-c** [comment]
should we rename `run_all_tests_torch_and_tf` to `run_slow_tests_torch_and_tf`?

**Comment by LysandreJik** [comment]
Well its purpose really is to run all tests, not only the slow tests but the custom tokenizers and soon the doc examples as well, so I feel that the current name is fitting.
