### ISSUE TITLE
What's the purpose of Pad to 64 in LLaVA

### ISSUE THREAD

**Issue by ShoufaChen** [huggingface/transformers#28013]
Hello @younesbelkada,

Thanks for your awesome work that integrates LLaVA to transformers repo.

Would you mind providing more details about the padding tokenizer to 64 here? 

https://github.com/huggingface/transformers/blob/fe44b1f1a974139cd32a8884a63686425283b07c/src/transformers/models/llava/convert_llava_weights_to_hf.py#L71-L73

What's the advantage of 64? I thought 2 is enough? 

Thanks in advance.

**Comment by younesbelkada** [comment]
Hi @ShoufaChen 
Thanks for the issue,
In contrast to the official implementation, we decided to padd the language model's vocabulary size to introduce the new <image> token. Instead of adding 2, which is in fact sufficient, we decided to go for 64 for performance reasons as explained in this document: https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html#requirements-tc shared by @ArthurZucker here: https://huggingface.co/llava-hf/llava-1.5-7b-hf/discussions/5 
Let me know if this makes sense to you

**Comment by ShoufaChen** [comment]
Thanks for your detailed reply

**Comment by younesbelkada** [comment]
Thank you very much @ShoufaChen !
