### ISSUE TITLE
MobileVitV2 doesn't have optimizer and loss argument in `model.compile()`?

### ISSUE THREAD

**Issue by adhiiisetiawan** [huggingface/transformers#28258]
### System Info

- `transformers` version: 4.35.2
- Platform: Linux-6.1.58+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.4.1
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Tensorflow version (GPU?): 2.15.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.7.5 (cpu)
- Jax version: 0.4.23
- JaxLib version: 0.4.23
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

vision models: @amyeroberts 

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Run this official tensorflow [notebook](https://colab.research.google.com/github/huggingface/notebooks/blob/main/transformers_doc/en/tensorflow/image_classification.ipynb#scrollTo=-Pi8UI110qKL) from huggingface and change the model to `apple/mobilevitv2-1.0-imagenet1k-256`. When try to `model.compile()` will result an error `TypeError: compile() got an unexpected keyword argument 'optimizer'`. But, when we delete the arguments, code will run without problem, but of course, we need define optimizer there.

Also when we not pass the arguments, `model.fit` give an error too `AttributeError: 'MobileViTV2Model' object has no attribute 'fit'`

Try with my own notebook for better reproducibility [here](https://colab.research.google.com/drive/1-TFfsun98fKchJRY-ZCV5_tYOwPYLtuX?usp=sharing).

### Expected behavior

MobileViTV2 can running

**Comment by LysandreJik** [comment]
cc @Rocketknight1

**Comment by Rocketknight1** [comment]
Hi @adhiiisetiawan, the issue here is that when you changed the code, you switched from TF classes to PyTorch classes. Your code uses `MobileViTV2Model`, but this is a PyTorch class. Therefore, the reason that the `compile()` method is behaving incorrectly for you is that you're actually loading a PyTorch model and calling PyTorch's `compile()` method, which does something very different to TensorFlow's `model.compile()`!

Unfortunately, `MobileVitV2` is not yet supported in TensorFlow in `transformers`, so if you want to use this model for now you'll need to do it in PyTorch. You can either use another model (and change the code back to use `TFAutoModelForImageClassification`) if you want to stick with TensorFlow, or you can switch to the PyTorch notebook instead if you want to fine-tune `apple/mobilevitv2-1.0-imagenet1k-256`.

**Comment by adhiiisetiawan** [comment]
ohh i see, okay thank you @Rocketknight1 for explanation
