### ISSUE TITLE
Disabling adapters is not removing the adapter from active adapters

### ISSUE THREAD

**Issue by balachandra** [huggingface/transformers#28565]
### System Info

Using AWS sagemaker notebook with conda_pytorch_p310 as env.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Add an adapter to the model using `add_adapter`
2. Disable all adapters using `disable_adapters`
3. List active adapters using `active_adapters`

### Expected behavior

Ideally, when all the adapters are disabled, the active adapters should return an empty list.

**Comment by amyeroberts** [comment]
Hi @balachandra, thanks for raising an issue! 

So that we can be best help you, please make sure to follow the [issue template](https://github.com/huggingface/transformers/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml) and provide: 
* The running environment: run `transformers-cli env` in the terminal and copy-paste the output
* A minimal code snippet we can run to reproduce the error 
* All relevant details about the error including the full error traceback

**Comment by Coconut3223** [comment]
same case
