### ISSUE TITLE
UserWarning: The number of elements in the out tensor of shape [1] is 1 

### ISSUE THREAD

**Issue by lenyabloko** [huggingface/transformers#2865]
# ❓ Questions & Help

## Details

I am using HuggingFace pytorch-transformers and one of my pre-trained models refuse to fine tune giving me those UserWarnings for every torch.utils.data.DataLoader call.

I have described the details in  https://stackoverflow.com/questions/60218634/userwarning-the-number-of-elements-in-the-out-tensor-of-shape-1-is-1

Here is my Notebook so you can run and see the results:
https://colab.research.google.com/drive/1mq9RZ_BX1O5vgxCM0CvPzAm9YVKnq4DQ

But someone downgraded my question for some  reason. What am I missing?

Thanks for your help!

**A link to original question on Stack Overflow**:  https://stackoverflow.com/questions/60218634/userwarning-the-number-of-elements-in-the-out-tensor-of-shape-1-is-1

**Comment by BramVanroy** [comment]
It is likely that your SO question was downvoted because it is a lot of unreproducible code, and not a lot of explanation. In other words: when someone reads your qusetion, it is almost impossible to answer because we cannot try your code ourselves. Try reducing it to a minimal, verifiable, executable example.

That being said: you don't need to install pytorch-transformers AND transformers. The latter is the successor to the former, so you should only install one or the other (preferably only transformers), and fix your imports accordingly.

**Comment by lenyabloko** [comment]
Thanks for your answer. I am following your suggestions. However when I replace
```
from pytorch_transformers import AdamW, WarmupLinearSchedule
``
with 

```
from transformers import AdamW, WarmupLinearSchedule

```

I get this error

```
ImportError                               Traceback (most recent call last)
<ipython-input-7-fc8519a4dbdc> in <module>()
     19                                   RobertaConfig, RobertaForSequenceClassification, RobertaTokenizer)
     20 
---> 21 from transformers import AdamW, WarmupLinearSchedule
     22 
     23 from utils import (convert_examples_to_features,output_modes, processors)

ImportError: cannot import name 'WarmupLinearSchedule'
```
Can you help me  out?
Thanks

**Comment by BramVanroy** [comment]
You are probably looking for

https://github.com/huggingface/transformers/blob/20fc18fbda3669c2f4a3510e0705b2acd54bff07/src/transformers/optimization.py#L47-L59
