### ISSUE TITLE
Update the default depth estimation model of the pipeline

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/transformers#28762]
### Feature request

The current depth estimation pipeline leverages https://huggingface.co/Intel/dpt-large by default.

However, with recent models like Depth Anything, it might make sense to update the default model.

For reference, DPT-large (also called DPT 3.0) was released in 2021, we do have better models in 2024 :)

### Motivation

Having better depth estimation models by default would be great.

### Your contribution

I could contribute this, but let's perhaps first discuss

**Comment by amyeroberts** [comment]
In principle, I think this might be a good idea: people want to just get good predictions, and serving the "best" model by default is probably improving user experience. However, it does change things silently for the users. 

There's a few questions this brings up: 
* Backwards compatibility - users who were calling the default pipeline will see their predictions change and possibly compatibility with the environment and hardware. If things suddenly stop working then it's a bad user experience.  
* What's the reason for not upgrading to different models for the other pipelines? I can see they're all using older / more basic models like vit and distilbert. Simplicity and size might be a reason for having a default model: a pipeline call anyone can run is better than one that needs e.g. a large machine. 
* What are the rules for updating models? Is anyone responsible? What are the criterea for a new model to become the default?

**Comment by Narsil** [comment]
Afaik we don't have rules around changing default models.

So far, I think the main thing has been routing users to call pipeline on specific models rather than task themselves (so they are responsible for upgrading their model, and we are not so we don't have to worry about backward compatibility).

I think the best course of action is to promote 

```python
pipeline(model="LiheYoung/depth-anything-base-hf")
```

instead of 

```python
pipeline("depth-estimation")
```

Updating the docs (So the default model within the docs) would be non breaking and still be up to date for new users.

**Comment by ArthurZucker** [comment]
cc @Rocketknight1
