### ISSUE TITLE
ValueError is raised when `num_return_sequences > num_beams` even if `do_sample` is True

### ISSUE THREAD

**Issue by JohnnieDavidov** [huggingface/transformers#28896]
### System Info

In [configuration_utils.py](https://github.com/huggingface/transformers/blob/main/src/transformers/generation/configuration_utils.py#L506) an error is raised if `num_return_sequences > num_beams`, but I think that this error should be raised only when do_sample is False. This is because in [utils.py](https://github.com/huggingface/transformers/blob/main/src/transformers/generation/utils.py#L1519) if the generation mode is set to sample, then we expand the input to create multiple generations, and do not rely on the beam size.
If this makes sense, I can open a PR that addresses this issue by adding a condition that checks if we are in a sample generation mode.

@gante I would appreciate your input on this. This validation was added in [this PR](https://github.com/huggingface/transformers/commit/5bd8c011bb24201148c1a2ba753ffd3f0822f004).

Thanks

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

[this line](https://github.com/huggingface/transformers/blob/main/src/transformers/generation/configuration_utils.py#L506)
 and I get this Error:
 `num_return_sequences` (30) has to be smaller or equal to `num_beams` (4).

### Expected behavior

To find out if there's a bug in what I'm thinking.

**Comment by Saibo-creator** [comment]
I personally don't think this is a bug but rather a correct behavior because this error is only triggered when the param `num_beams` is set, which means the user either opt `beam search` or `beam sample`. Both the two sampling methods only keep `num_beams` candidate during searching so they really can not return more than `num_beams` generations. 

(N.B. beam sample != sample multiple times)

If the user wants to get multiple generations from random sampling, the `num_beams` param should be removed.

**Comment by gante** [comment]
@JohnnieDavidov 👋  @Saibo-creator wrote the correct answer :)
