### ISSUE TITLE
Language modeling example script missing the next sentence predicion

### ISSUE THREAD

**Issue by salmanmashayekh** [huggingface/transformers#2898]
The example script in `run_language_modeling.py` does not include the next sentence prediction for pre-training BERT. I was wondering if that is a) an oversight, b) for simplicity, or c) because you have found its impact to be non-significant?

**Comment by LysandreJik** [comment]
It is both b) and c) :).

**Comment by mahdirezaey** [comment]
Hello @LysandreJik  and @BramVanroy 

Did you have any results in training   run_language_modeling.py    for some language from scratch (i mean with and  without NSP (next sentence prediction) as is in that script) ?

Did you get better or relatively the same losses (and perplexity, accuracy) by first doing MLM then 
NSP ?

what were your warmup steps and  block size (maximum sequence length) for each (MLM , NSP) task , if you have down them separately ?

**Comment by mahdirezaey** [comment]
I really need your answer and I will be grateful if you answer

**Comment by mahdirezaey** [comment]
Or as @LysandreJik mentioned here

**Comment by mahdirezaey** [comment]
If it is right  ,  I think we can set  block size (maximum sequence length)  equal to 64  for MLM
 
Because the  original paper used  128 , and it had two sentences (A and B for the sake of NSP) which means average 64 for each one 

And it means grate speed up in training BERT 
As mentioned in original paper of BERT that "Longer sequences are disproportionately expensive because attention is quadratic to the sequence length"

**Comment by mahdirezaey** [comment]
Perhaps, another idea is that 
words in sentence A do attention on sentence B, anyway
and that attention is very important to get great results in MLM task (here I mean block size of 128)

even regarding the fact that  A and B are related sentences juts half of the times 
(and that attentions are the main inputs for task NSP)

And by using block size of 64 (and not doing task NSP during the training) , I will get very bad results
