### ISSUE TITLE
`get_torch_version()` doesn't return same result as `import torch; torch.__version__` 

### ISSUE THREAD

**Issue by relh** [huggingface/transformers#29022]
### System Info

ubuntu linux with conda and pip

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

`get_torch_version()` doesn't return same result as `import torch; torch.__version__` 

Hi, if you happen to have a version of torch installed with `pip` and one with `conda`, there can be an issue where the `import_utils` function doesn't return the same thing as actually importing.

This was recently an issue for me because I had a version `2.1.0` and a version `2.2.0` and the naming for `_torch_pytree.register_pytree_node` had been `_torch_pytree._register_pytree_node`. 

The solution is someone shouldn't have both installed (duh) but this problem could be avoided if line 311 in `generic.py` checked for the existence of a function and then fell back instead of parsing a version. 

### Expected behavior

1. have 2 versions of torch installed in an environment
2. use code that involves `generic.py` 
3. ???
4. profit

**Comment by amyeroberts** [comment]
Hi @relh, thanks for raising this issue! 

Indeed, despite the promised profit, I don't think this is something we should be handling within `generic.py`. Assuming there's one version installed is a fair one, and being able to parse the torch version is something we do throughout the library e.g. [here](https://github.com/huggingface/transformers/blob/5f06053dd821c91f7bd697309109abaa3396b605/src/transformers/pytorch_utils.py#L31). It's better to have this failure hit with the parsed version not matching and raising and error because a function couldn't be found instead of trying to do some magic on the inspection. After all, it caught this problem :)!  

We should expect `get_torch_version` to match `import torch; torch.__version__` though. I don't think this is an easy fix, as the reason this is happening is `importlib` isn't reading the "correct" torch. The question is, how can we know which is the "correct" version without importing (which `_is_package_available` does)?
