### ISSUE TITLE
What optimizations are available for AutoModelForVision2Seq

### ISSUE THREAD

**Issue by FurkanGozukara** [huggingface/transformers#29025]
Hello. I am using AutoModelForVision2Seq for Kosmos 2 model like below

```
    model_source = "microsoft/kosmos-2-patch14-224"

    model = AutoModelForVision2Seq.from_pretrained(model_source).to("cuda")
    processor = AutoProcessor.from_pretrained(model_source)
```

I checked this link but couldn't find anything regarding optimizations

Such as load as BF16?
Enable xformers?
Enable CPU offloading?
anything that can reduce VRAM usage, quantize or speed up inference?

Thank you

https://huggingface.co/docs/transformers/model_doc/auto

transformers==4.37.2

### Who can help?

text models: @ArthurZucker and @younesbelkada 
vision models: @amyeroberts
generate: @gante
pipelines: @Narsil
Big Model Inference: @SunMarc

**Comment by younesbelkada** [comment]
Hi @FurkanGozukara !
Thanks for the issue !

`AutoModelForVision2Seq` inherits from HF transformers' `PreTrainedModel`, therefore it benefits from most of the optimizations that are available, for instance you can load it in fp16, bf16 as usual through the `torch_dtype` argument, and you can also load the model in 4-bit / 8-bit through the `load_in_kbit=True` argument. 

For more "advanced" optimisations such as SDPA or Flash Attention 2, it is per-architecture basis, for `microsoft/kosmos-2-patch14-224`. From what I can see kosmos2 does not support SDPA or FA2 so you can open a separate issue as a feature request so that we can work on adding that feature

**Comment by FurkanGozukara** [comment]
> Hi @FurkanGozukara ! Thanks for the issue !
> 
> `AutoModelForVision2Seq` inherits from HF transformers' `PreTrainedModel`, therefore it benefits from most of the optimizations that are available, for instance you can load it in fp16, bf16 as usual through the `torch_dtype` argument, CPU offloading through device_map, and you can also load the model in 4-bit / 8-bit through the `load_in_kbit=True` argument (some models require to have the `accelerate` integration, so if it's not the case you can let us know).
> 
> For more "advanced" optimisations such as SDPA or Flash Attention 2, it is on per-architecture basis, for your specific question you are asking for `microsoft/kosmos-2-patch14-224`. From what I can see kosmos2 does not support SDPA or FA2 so you can open a separate issue as a feature request so that we can work on adding that feature

Awesome

this model is simply just amazing

Do you suggest FP16 or BF16?

I added 4, 8, 16 and 32 bit options
By default it was running at 32 bit

**Comment by FurkanGozukara** [comment]
16 February 2024 Update:
4-bit, 8-bit, 16-bit and 32-bit loading options added to the Kosmos-2
I think Kosmos-2 is the very best caption model if you have a lower VRAM GPU
4-bit of Kosmos 2 only uses 2 GB VRAM and 32-bit uses only 7.5 GB VRAM
Please reinstall with newest Kosmos-2_v2.zip
