### ISSUE TITLE
ValueError: lags cannot go further than history length, found lag 37 while history length is only 16

### ISSUE THREAD

**Issue by nikhilajoshy** [huggingface/transformers#29113]
### System Info

- `transformers` version: 4.37.2
- Platform: Linux-5.15.0-94-generic-x86_64-with-glibc2.31
- Python version: 3.11.7
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.2
- Accelerate version: 0.27.2
- Accelerate config:    not found
- PyTorch version (GPU?): 2.2.0+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

`model = TimeSeriesTransformerModel.from_pretrained(
    "models/time-series-transformer-tourism-monthly"
)

outputs = model(
    past_values=past_values,
    past_time_features=past_time_features,
    past_observed_mask=past_observed_mask,
    # static_categorical_features=static_categorical_features"],
    # static_real_features=static_real_features"],
    future_values=future_values,
    future_time_features=future_time_features,
)
`

### Expected behavior

Size of the arguments passed to model is below:
past values torch.Size([502, 8])
past_time_features torch.Size([502, 8, 1])
past_observed_mask torch.Size([502, 8])
future_values torch.Size([502, 8])
future_time_features torch.Size([502, 8, 1])

**Comment by amyeroberts** [comment]
cc @kashif @NielsRogge

**Comment by kashif** [comment]
@nikhilajoshy  can you kindly paste in some more verbose error?

**Comment by nikhilajoshy** [comment]
@kashif 
```
outputs = model(
              ^^^^^^
  File "/home/nikhila/encdec_venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nikhila/encdec_venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nikhila/encdec_venv/lib/python3.11/site-packages/transformers/models/time_series_transformer/modeling_time_series_transformer.py", line 1384, in forward
    transformer_inputs, loc, scale, static_feat = self.create_network_inputs(
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nikhila/encdec_venv/lib/python3.11/site-packages/transformers/models/time_series_transformer/modeling_time_series_transformer.py", line 1304, in create_network_inputs
    lagged_sequence = self.get_lagged_subsequences(sequence=inputs, subsequences_length=subsequences_length)
```

**Comment by amyeroberts** [comment]
Gentle ping @kashif

**Comment by kashif** [comment]
@nikhilajoshy  so when the history length is small you will need to for your dataset decrease the context-length and select lag indices such that they do not take values from very past values... so e.g. set the lag indices to just `[1]` for example... let me know how that goes!

**Comment by saddekbouriah** [comment]
Hello , i have the same error but it doesn't make sense  "ValueError: lags cannot go further than history length, found lag 7 while history length is only 690" with this configuration config = TimeSeriesTransformerConfig(
        prediction_length = len_pred  , #size of my future values vector and past values vector
        distribution_output = 'student_t',
        loss = 'nll',
        input_size = nb_features , 
        num_time_features = 6 , 
        # context_length= len_pred   ,
        # lags_sequence= [1],
        # num_parallel_samples=5
)  ? Thank you in advance for responding

**Comment by NielsRogge** [comment]
cc @kashif

**Comment by ArgyleR** [comment]
Hi, I have the same issues as @saddekbouriah, very keen to hear the answer!

**Comment by kashif** [comment]
so for your understanding... recall that a transformer takes as inputs a sequence of vectors and thus for a 1-dim (univariate) time series we need to figure out how to convert this seq of 1-d array into a sequence of vectors. Of course, we can add the date-time and other features as covariates to each point of the 1-d array to create a sequence of vectors. Another thing that is done here is that since transformers are quadratic in the seq length we can trade off the seq length by incorporating information from the past into the resulting sequence vectors. This however requires that the input to the transformer be larger than the resulting context length so that the lags can be constructed as in this diagram:

![lags drawio](https://github.com/user-attachments/assets/a5ffb7e8-61a6-4e51-a0f3-dfec7ffa66f3)

As you can see if we set our lag sequence indices to `[5, 10]` we will need the max of this index (10) extra time points to construct the feature vectors for the required context length.  

Thus depending on the context_length you specify as well as the lag sequences you will need larger input else you will run into the above error. 

Let me know if that helps?

**Comment by ArgyleR** [comment]
Thank you so much for the quick response!
 
 To clarify, is context_length just the total input the model manages (input and predicted output combined?) similar to how a language transformer takes k tokens as input and produces j tokens as response, the context_length would be at least k + j?
 
 Additionally: this has solved the error I was getting earlier however I now have a matrix mismatch
 RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x7 and 9x192)
 
 I understand this is because I've taking the 'ibm-granite/granite-timeseries-ttm-v1' and made the following changes:
 
 model = TimeSeriesTransformerModel.from_pretrained('ibm-granite/granite-timeseries-ttm-v1')
# Modify the lags_sequence in the existing model's configuration but keep the pre-trained weights
model.config.lags_sequence = [1, 2, 3, 4]
model.config.prediction_length = 1
model.config.context_length = 4

model = TimeSeriesTransformerModel.from_pretrained('ibm-granite/granite-timeseries-ttm-v1', config=model.config)
model.eval()

batch_size = 1
past_values = torch.tensor([[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]])  
past_time_features = torch.tensor([[[0.0], [1.0], [2.0], [3.0], [4.0], [5.0], [6.0], [7.0]]])    
past_observed_mask = torch.tensor([[1, 1, 1, 1, 1, 1, 1, 1]])  

static_real_features = torch.empty((batch_size, 0)).float()  

Is this something that should be padded to reach the 9 dim of mat2?

**Comment by kashif** [comment]
I believe taking the weight from the `ibm-granite/granite-timeseries-ttm-v1` will not work as that is a completely different architecture to the vanilla `TimeSeriesTransformerModel` I was referencing here...

**Comment by kashif** [comment]
to clarify the other question about context-length etc. The `context_length` as defined here is the number of final sequences size of the context part of the vectors... and `prediction_length` the subsequent prediction length number of vectors. It is the same in language models... however, for decoder-only models, these two windows can be considered as a single window and the next-step ahead distribution is learned and the same would happen if we had a decoder-only time series model. For encoder-decoder models (like the original transformer and hence this model) there is a separation between the two windows, where the context-length number of vectors goes to the encoder and the prediction length goes to the decoder during training. Let me know if that clears up the confusion.

**Comment by ArgyleR** [comment]
Thank you, this does clear up the context size issue! Now I just have to figure out how I can mold the models/inputs to my task! Thank you @kashif, I may have more follow up questions at some point but this has been a big help :)

**Comment by LiZirui11** [comment]
context.length+max(lags)==sequence.length
sequence.length input of model
