### ISSUE TITLE
TFBertModel: InvalidArgumentError.__init__() missing 2 required positional arguments: 'op' and 'message'

### ISSUE THREAD

**Issue by tomigee** [huggingface/transformers#29566]
### System Info

- `transformers` version: 4.38.2
- Platform: macOS-14.1.1-arm64-arm-64bit
- Python version: 3.10.13
- Huggingface_hub version: 0.20.2
- Safetensors version: 0.4.2
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): 2.15.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes, I'm on an M2 Mac
- Using distributed or parallel set-up in script?: Yes

### Who can help?

@ArthurZucker @younesbelkada 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Hi Hugging Face team,
First off thanks for the work you do. Here's my issue:
When I try to create a TFBertModel with a BertConfig object, it errors out on me

**Environment information**
Operating System: macOS Sonoma 14.1.1

```python
from transformers import TFBertModel, BertConfig
configuration = BertConfig(max_position_embeddings=2048)
bert = TFBertModel.from_pretrained("bert-base-uncased", config=configuration)
```

The returned error traceback is located in this [gist.](https://gist.github.com/tomigee/6c5b39629305463d9799b8ae5e5548b9)

### Expected behavior

A TFBertModel is created with no errors

**Additional context**
I reproduced this error on Google Colab, so it's not platform specific.

**Comment by amyeroberts** [comment]
Hi @tomigee, thanks for raising this issue! 

Three comments: 
* The canonical checkpoints have been deprecated, so all models should have an org identifier. In this case, it's advisable to use `google-bert/bert-base-uncased` instead of `bert-base-uncased` 
* To change a parameter of a pretrained model, you should pass that directly to the model's from_pretrained call. This will ensure the correct config is loaded for that checkpoint: the default values for `BertConfig` may not match those in `google-bert/bert-base-uncased` checkpoint. Doing it this way will avoid any unexpected behaviours e.g. some weights not loading.
* This is happening because you're modifying the default embedding size, by trying to load in the old weights which have a different shape. You need to set `ignore_mismatched_sizes=True`

The following works when I run on `main`:

```py
from transformers import TFBertModel
bert = TFBertModel.from_pretrained("bert-base-uncased", max_position_embeddings=2048, ignore_mismatched_sizes=True)
```

**Comment by tomigee** [comment]
Hi @amyeroberts,

Thanks for resolving! I guessed the issue had something to do with the way I was instantiating the `TFBertModel`, but I had no clue where to start debugging as the error message wasn't particularly helpful 😅. Thanks again, issue resolved.
