### ISSUE TITLE
Conversion Script for Mamba checkpoints (`mamba_ssm` -> `transformers`)

### ISSUE THREAD

**Issue by haileyschoelkopf** [huggingface/transformers#29631]
### Feature request

Thanks very much for the Mamba support (#28094), this interoperability is fantastic!

I wanted to ask if there were any utility (doesn't have to be clean, just functional) for converting checkpoints provided for use in the `mamba_ssm` library into the format provided in `transformers`. 

This would be very helpful if it exists! Thanks 🤗 

### Motivation

I'd like to be able to convert novel trained mamba models from the `state-spaces/mamba` repo into HF transformers without rewriting a conversion script myself if need be.

### Your contribution

I could write a utility for this if none exists but would probably not have the bandwidth to upstream it.

**Comment by amyeroberts** [comment]
Hi @haileyschoelkopf, thanks for opening this feature request! 

Normally we have conversion scripts under each model's folder (would [be here](https://github.com/huggingface/transformers/tree/b340d90738fa14bd6f81b65e4148173cbec62ff6/src/transformers/models/mamba)). 

I think adsding conversion script sounds like a good idea! @ArthurZucker contributed the model. He's off at the moment, but back soon - I'll let him reply in case there's a good reason we didn't add it alongside the model originally

**Comment by haileyschoelkopf** [comment]
Thank you! I'll share here if I get the time to implement one myself!

**Comment by haileyschoelkopf** [comment]
yep! Basically just load checkpoint file -> convert to a format loadable by the other library, e.g. reshaping or renaming weights as needed -> run `load_state_dict()` using `transformers` or `mamba_ssm` model -> call `save_pretrained()` to output new loadable/uploadable model.

**Comment by SrGonao** [comment]
I've made this if it's helpful for anyone.
https://gist.github.com/SrGonao/33f373a13a6cad6b245450f3d6361598

**Comment by byi8220** [comment]
Thanks, that's very helpful. I'll try to get a PR out soon modeled off that.

**Comment by ArthurZucker** [comment]
hey! The reason I did not add one is because the original checkpoints are compatible. This can still be added but only the config should be inferred / updated!

**Comment by byi8220** [comment]
> So your checkpoint should already be compatible, no renaming and no reshaping

Hm, when I try to run a conversion, I get an error suggesting there needs to be a rename:
```
RuntimeError: Error(s) in loading state_dict for MambaForCausalLM:
        Missing key(s) in state_dict: "backbone.embeddings.weight". 
        Unexpected key(s) in state_dict: "backbone.embedding.weight". 
```

The unexpected key contains "embedding" (with no s at the end), while the missing key contains "embeddings" (with an s at the end)

I've attempted to create a PR which both converts the config and does the above renaming: https://github.com/huggingface/transformers/pull/29705

(Huge thanks to @SrGonao , my PR does pretty much the same thing as his script, except on local files instead of interacting with the hub)

**Comment by ArthurZucker** [comment]
Oh no 😅 
I am not getting this one on the original checkpoints, so maybe it was updated at some point?

**Comment by byi8220** [comment]
> maybe because the weights are tied it used the lm_head's weights and tied using them.

I'm confused by what you mean here.

I thought that the problem was due to a difference in naming conventions between the two packages, where the [transformers library](https://github.com/huggingface/transformers/blob/76a33a10923ccc1074917f6b6a1e719e626b7dc9/src/transformers/models/mamba/modeling_mamba.py#L497) and the [mamba_ssm model library](https://github.com/state-spaces/mamba/blob/main/mamba_ssm/models/mixer_seq_simple.py#L105) just chose to name their embedding layer differently.

>Just saw your PR to remove the tie_weights that were forced before in ssm-state

Are you referring to @haileyschoelkopf's PR in https://github.com/state-spaces/mamba/pull/211?

**Comment by ArthurZucker** [comment]
I'll add a loading hook just this once! IMO should be the cleanest way to fix this

**Comment by ArthurZucker** [comment]
I mean that on my side, when implementing mamba in transformers I did not have a warning about the weights. I suppose that this is because the weights are by default tied. `tie_word_embeddings=True`. Thus this: 
```python 
>>> from transformers import AutoModelForCausalLM
>>> model = AutoModelForCausalLM.from_pretrained("state-spaces/mamba-130m", num_hidden_layers=24, vocab_size = 50280)
```
does not produce any warning. 
while:
```python
>>> from transformers import AutoModelForCausalLM
>>> model = AutoModelForCausalLM.from_pretrained("state-spaces/mamba-130m", num_hidden_layers=24, vocab_size = 50280, tie_word_embeddings=False)
Some weights of MambaForCausalLM were not initialized from the model checkpoint at state-spaces/mamba-130m and are newly initialized: ['backbone.embeddings.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```
does. 

and:
```python
>>> from transformers import AutoModel

>>> model = AutoModel.from_pretrained("state-spaces/mamba-130m", num_hidden_layers=24, vocab_size = 50280)
Some weights of MambaModel were not initialized from the model checkpoint at state-spaces/mamba-130m and are newly initialized: ['backbone.embeddings.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```

**Comment by ArthurZucker** [comment]
That a really silent bug, and I got tricked by it...

**Comment by ArthurZucker** [comment]
cc @amyeroberts core issue !

**Comment by byi8220** [comment]
Hm, just to make sure I understand:

1. The lack of warning about uninitialized weights is because when `tie_word_embeddings=True`, the input embedding layer weights name is somehow ignored at some step of loading a pretrained model?
2. A converter which renames weights alongside config conversion _should_ exist.
3. This issue may exist in other models since it's due to behavior in weight tying and not something mamba specific?

**Comment by ArthurZucker** [comment]
2. A converter which renames weights alongside config conversion should exist.
"Could ", what I am thinking about is just a simple hook triggered in `from_pretrained`, let me open a PR in a bit. This avoids having a conversion script

3.This issue may exist in other models since it's due to behavior in weight tying and not something mamba specific?
Totally. But most probably we would have heard of that, as people use the AutoModel api a lot, and don't always tie weights.

**Comment by byi8220** [comment]
1. Just wondering, if it's an error, should these be logged at warning level or are these generally just warnings: https://github.com/huggingface/transformers/blob/main/src/transformers/modeling_utils.py#L4011-L4030
2. "This avoids having a conversion script" - Wouldn't there still need to be one to convert the `MambaConfig`? (If there doesn't need to be a converter at all, I guess I can discard https://github.com/huggingface/transformers/pull/29705)
3. If it causes issues immediately then yeah that makes sense too.

**Comment by ArthurZucker** [comment]
About 2. I mean avoid having to explicitly convert if you know the config. Config can be initialized first with from_pretrained! 

But let's still have the conversion script! It will be beneficial to have a mapping between the names and the config explicitly!

**Comment by ArthurZucker** [comment]
For 1. yes a warning should indeed be issued sorry, we raise error for mismatch sizes!

**Comment by byi8220** [comment]
Sg, I removed the weight rename from my PR (although now my PR won't actually work until yours is checked in)

**Comment by byi8220** [comment]
Just a quick plug: I think your PR fixes the checkpointing issue, but PR https://github.com/huggingface/transformers/pull/29705 is still open for config->config conversion.

**Comment by ArthurZucker** [comment]
Indeed opening again!
