### ISSUE TITLE
AttributeError: 'BertTokenizer' object has no attribute 'split_special_tokens'

### ISSUE THREAD

**Issue by KeshavUnnikrishnanTR** [huggingface/transformers#29654]
### System Info

System Info
Python version: 3.12.0
transformers version: 4.38.2
Platform: MacOS
scikit-learn version: 1.4.0

When loading a sklearn.feature_extraction.text.TfidfVectorizer model, got following error:
`AttributeError: 'BertTokenizer' object has no attribute 'split_special_tokens'`
 
I had noticed this error from other issues too:
https://github.com/flairNLP/flair/issues/1796#issue-674666035
I use 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer

# Load the pickled vectorizer
with open("models/HaVoCuVaSu_label_10_digits_tfidf_vectors.pickle", "rb") as f:
    vectorizer = pickle.load(f)
print(type(vectorizer))
# Use the vectorizer to transform some text
text = ["This is the first document.", "This is the second document."]
X = vectorizer.transform(text)
```

### Expected behavior

Expect no error for the transform step.

**Comment by amyeroberts** [comment]
Hi @KeshavUnnikrishnanTR, thanks for raising an issue! 

Without knowing what's in `"models/HaVoCuVaSu_label_10_digits_tfidf_vectors.pickle"` it's very hard to know what's happening here. For security, we won't however accept the file to unpickle :) It would help to show the code how this object was created. 

From the linked issue, it appears this can happen from incompatible versions. How old is this file? Which version of transformers was used to create it? What happens if you create a new vectorizer, save it and reload it?

**Comment by KeshavUnnikrishnanTR** [comment]
@amyeroberts can you please remove the model name from the issue here.

**Comment by amyeroberts** [comment]
Hi @KeshavUnnikrishnanTR, sure, I've updated my comment. 

One thing to note for your own information, is that the model name will still be available if someone were to look at the history of the issue
