### ISSUE TITLE
Getting the output of the from the forward function of the GPT-2

### ISSUE THREAD

**Issue by h56cho** [huggingface/transformers#2972]
Hello,

Is there any way that I can extract the output of the ```self.merge_heads(a)``` and the ```self.c_proj(a)``` from the forward function for the Hugging Face GPT-2, which are found[ here](https://github.com/huggingface/transformers/blob/73028c5df0c28ca179fbe565482a9c2143787f61/src/transformers/modeling_gpt2.py#L192) and [here](https://github.com/huggingface/transformers/blob/73028c5df0c28ca179fbe565482a9c2143787f61/src/transformers/modeling_gpt2.py#L193)?

Thank you,

**Comment by LysandreJik** [comment]
There isn't a way to retrieve that from the current API, but feel free to clone the repository and modify it to fit your needs.

**Comment by h56cho** [comment]
Hello,

Thank you for your reply. Can I make a request to the Hugging Face so that the code can be modified for users to extract ```self.merge_heads(a)``` and ```self.c_proj(a)```? If yes, how can I make the request?

Thank you,

**Comment by BramVanroy** [comment]
> Hello,
> 
> Thank you for your reply. Can I make a request to the Hugging Face so that the code can be modified for users to extract `self.merge_heads(a)` and `self.c_proj(a)`? If yes, how can I make the request?
> 
> Thank you,

You can suggest feature requests here, as a feature (so here in this topic), but chances are very slim that it will be picked up. It is not high in priority, I would think. @LysandreJik suggests that you clone the repository and implement it yourself. If you successfully do so, you can do a pull request so that your code becomes part of this repository!
