### ISSUE TITLE
Add TokenClassification support for modern LLMs

### ISSUE THREAD

**Issue by josephenguehard** [huggingface/transformers#29940]
### Feature request

Implement TokenClassification for Llama, Mistral and similar models.

### Motivation

A few of the recently developed LLMs (e.g. Llama, Mistral) do not support the TokenClassification task, which is used for instance for Named Entity Recognition (NER) and Part-of-Speech (PoS) tagging.

It would be beneficial for the `transformers` library to have this task implemented for these models.

### Your contribution

Implement the following classes:
- `LlamaForTokenClassification`
- `MistralForTokenClassification`
- Other models which are similar to Llama and Mistral, where the code can simply be copied from either of these models.

**Comment by KoichiYasuoka** [comment]
Thank you @josephenguehard and I've already released two TokenClassification models, [Swallow-7b-plus-upos](https://huggingface.co/KoichiYasuoka/Swallow-7b-plus-upos) and [Swallow-MS-7b-upos](https://huggingface.co/KoichiYasuoka/Swallow-MS-7b-upos), in order to compare LLM POS-tagging methods between two papers:

-  https://aclanthology.org/2023.acl-long.367
-  https://arxiv.org/abs/2310.01208

One of these methods needs CausalLM and the other needs TokenClassification...

**Comment by KoichiYasuoka** [comment]
In [Swallow-7b-plus-upos](https://huggingface.co/KoichiYasuoka/Swallow-7b-plus-upos) I included Dropout layer in the decoder. So as [Swallow-MS-7b-upos](https://huggingface.co/KoichiYasuoka/Swallow-MS-7b-upos).

**Comment by josephenguehard** [comment]
PR merged
