### ISSUE TITLE
TypeError: BARTDecoder.prepare_inputs_for_inference() got an unexpected keyword argument 'cache_position'

### ISSUE THREAD

**Issue by Rlahuerta** [huggingface/transformers#30029]
https://github.com/huggingface/transformers/blob/03732dea60fba1da78c79eb59c443ebf975c2be6/src/transformers/generation/utils.py#L2429C9-L2429C21

I got this error in Transformers 4.39.1 when I was trying to use Nogaut from facebook (https://github.com/facebookresearch/nougat) 

I think this method "prepare_inputs_for_generation" is not supporting "cache_position" kwargs

**Comment by zucchini-nlp** [comment]
@Rlahuerta hey! 

It seems to be failing because nougat has implemented its own "prepare_inputs_for_generation", which differs from `transformers` implementation. I would say that older version of `transformers` should be used in nougat, before the "cache_position" changes were introduced. For ex:

`pip install transformers==4.38.2`

**Comment by Rlahuerta** [comment]
@zucchini-nlp You are alright; I tested with this transformers==4.38.2, and it worked! I have notified them about this issue...

**Comment by shridhardamle** [comment]
I confirm with `transformers==4.38.2` the error `BARTDecoder.prepare_inputs_for_inference() got an unexpected keyword argument 'cache_position'`

Should reported on nougat ocr github page.
