### ISSUE TITLE
Remove pipelines, chatformatters, templates etc  --> Replace with simple generator function / manual string interpolation ---> Just have one standardized way for building datasets and running inference 

### ISSUE THREAD

**Issue by bdytx5** [huggingface/transformers#30625]
### Feature request

https://huggingface.co/docs/transformers/main/en/chat_templating

Theres a lot of complexity here. I dont think that it needs to be as complicated as it is. We can just look at what special tokens are being used for the model, and create a dataset based on what we need.

### Motivation

Its hard to tell whats actually being passed to the model, as there are several different pipeline and generators, its extremely difficult to know if your dataset is actually being formatted correctly 

### Your contribution

https://github.com/bdytx5/llama3_finetune/blob/main/tr.py

This is my best simplification. There's no need for chat templates or anything like that, as it's really just simple string interpolation. Trying to abstract this just creates more complexity and confusion.

**Comment by amyeroberts** [comment]
Hi @bdytx5, thanks for opening this feature request! 

Pinging @Rocketknight1 as he's the master of the chat templates.

**Comment by Rocketknight1** [comment]
I think this simplification might be a little too simplified, since it doesn't seem to support anything like system prompting, multi-turn conversations, or any model other than LLaMA-3. It also doesn't support e.g. control over whether we append a generation prompt.

We did consider the solution of just using string formatting rather than a templating language, but what we found was that many models have templates too complex for a universal string formatting solution to work. In particular, here are some tricky ones:

- LLaMA-2 [injects the system message](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/blob/main/tokenizer_config.json), if present, inside the first user message.
- Command-R has [three different templates](https://huggingface.co/CohereForAI/c4ai-command-r-plus/blob/main/tokenizer_config.json#L304), for basic generation, tool use and RAG generation. Arguments for the latter two can be optional or nested.

In addition, any replacement solution would need, at a minimum, the following properties:
- Has to support all known existing model chat formats (including the two listed above, but also many others)
- Has to work with a single universal Python function in the `transformers` codebase - no code in the model repos, which includes f-strings, as these allow arbitrary execution!
- Ideally not Python-specific, since Rust libraries like TGI are also handling chat templates via `minijinja`, or `huggingface/jinja` for JS.

I think you'll find that if you expand your solution to cover all of these possible cases, you'll end up reinventing chat templates, or something that looks a lot like them!

Good-naturedly closing this for now, but feel free to reopen it if you want to propose a more complete replacement for chat templating.
