### ISSUE TITLE
Only enable some labels in BERT fine-tuned NER

### ISSUE THREAD

**Issue by jmamou** [huggingface/transformers#3074]
# ❓ Questions & Help
Only enable some labels in BERT fine-tuned NER

## Details
I would be interested to enable only some labels in BERT fine-tuned NER prediction. 
For example, I know what are the entities and I would like to train a model that will classify entities - but I am not interested to train/predict O tag.
What would be the best way to do it?
Thanks

**Comment by LysandreJik** [comment]
I'm not sure I understand your question. The O tag is here in order to identify a token which is not an entity in the IOB1 tagging scheme. If you don't have such a tag, every token will have to be classified as an entity, which does not make sense?

If you would like to define a custom tagging scheme and train a model to predict on that tagging scheme, you would have to create a dataset for that and train your model on that dataset.

**Comment by jmamou** [comment]
Thanks @LysandreJik 
Let me provide some additional details. Given a sentence, I use some external resources to find what are the candidates for tagging. For the candidates, I need to classify between 2 different labels (binary classification). That's the reason why I wrote that I am not interested in predicting the O tag, since I use external resources for it. 
I have data for train/test.

**Comment by clmnt** [comment]
Hey @jmamou , we might be able to help. Mind sending me an email at clement [at] huggingface [dot] co?
