### ISSUE TITLE
Whisper for audio classification Hey @rokayabencheikh     82         If the key is a string, returns the value of the dict associated to `key` ('input_values', 'attention_mask', - could you confirm that you're using the latest version of the Transformers library? i.e. with:

### ISSUE THREAD

**Issue by manjualoshious** [huggingface/transformers#30831]
inputs = feature_extractor(sample["array"], sampling_rate=sample["sampling_rate"])

print(f"inputs keys: {list(inputs.keys())}")

print(
    f"Mean: {np.mean(inputs['input_values']):.3}, Variance: {np.var(inputs['input_values']):.3}"
)

     82         If the key is a string, returns the value of the dict associated to `key` ('input_values', 'attention_mask',

**Comment by amyeroberts** [comment]
Hi @manjualoshious, what is the issue here being reported?

**Comment by manjualoshious** [comment]
Audio Classification using whisper Model

****inputs = feature_extractor(sample['array'], sampling_rate=sample["sampling_rate"])****

**print(    f"Mean: {np.mean(inputs['input_values']):.3}, Variance: {np.var(inputs['input_values']):.3}"**

The second statement shows error message

**Comment by amyeroberts** [comment]
So that we can best help you, please make sure to follow the [issue template](https://github.com/huggingface/transformers/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml) and include: 

* The running environment: run `transformers-cli env` in the terminal and copy-paste the output
* A minimal code reproducer. At the moment, we cannot copy-paste the example code provided as we don't have access to `sample`
* The full error traceback

Could you also update the title to something more meaningful?

**Comment by amyeroberts** [comment]
cc @sanchit-gandhi

**Comment by manjualoshious** [comment]
Thank very you for your response. This issue is solved now.

I have raised another issue regarding WhisperFotAutoClassification.

Even with latest transformer 4.40.2  it is not possible to import
WhisperFotAutoClassification.
Kindly help me to solve this problem

Thanking you

Manju

**Comment by amyeroberts** [comment]
> This issue is solved now.

@manjualoshious Could you please share how this was solved for anyone coming to this issue in the future?

**Comment by manjualoshious** [comment]
inputs keys: ['input_features']
