### ISSUE TITLE
GenerationConfig throws Object is not JSON serializable when setting constraints

### ISSUE THREAD

**Issue by OS-leonardopratesi** [huggingface/transformers#31070]
### System Info

From the GenerationConfig documentation Constraints should be [supported ](https://huggingface.co/docs/transformers/en/main_classes/text_generation#transformers.GenerationConfig.constraints) but when I try to load any it fails. 
I know I can also set the constraints directly in the `pipeline.generate()`, (*edit: not really a constraint but through the logit_ processor)  but for my use case I need to store the constraints in the configuration for later usage.
Following code reproduces the issue:
```
from transformers import PhrasalConstraint, AutoTokenizer
from transformers import GenerationConfig

model_name = "deepseek-ai/deepseek-coder-1.3b-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
stop_token_id = tokenizer("STOP").input_ids
constraint = PhrasalConstraint(stop_token_id)

generation_config, unused_kwargs = GenerationConfig.from_pretrained(
    model_name,
    constraints=[constraint])
```
```
TypeError: Object of type PhrasalConstraint is not JSON serializable
File <command-2448391505512096>, line 4
      1 import json
      3 # Convert the constraint to a JSON serializable format
----> 4 constraint_json = json.dumps(constraint)
File /usr/lib/python3.11/json/encoder.py:180, in JSONEncoder.default(self, o)
    161 def default(self, o):
    162     """Implement this method in a subclass such that it returns
    163     a serializable object for ``o``, or calls the base implementation
    164     (to raise a ``TypeError``).
   (...)
    178 
    179     """
--> 180     raise TypeError(f'Object of type {o.__class__.__name__} '
    181                     f'is not JSON serializable')

```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import PhrasalConstraint
from transformers import GenerationConfig

model_name = "deepseek-ai/deepseek-coder-1.3b-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
stop_token_id = tokenizer("STOP").input_ids
constraint = PhrasalConstraint(stop_token_id)

generation_config, unused_kwargs = GenerationConfig.from_pretrained(
    model_name,
    constraints=[constraint])

### Expected behavior

From documentation it should support Constraints, https://huggingface.co/docs/transformers/en/main_classes/text_generation#transformers.GenerationConfig.constraints, I expect the constraints to be stored somehow and be loaded automatically when calling AutoModelForCausalLM.

**Comment by zucchini-nlp** [comment]
cc @gante

**Comment by dhaivat1729** [comment]
I think this error is coming because we are trying to get serialized representation of an the constraint object at several places. 
In line [993](https://github.com/huggingface/transformers/blob/a564d10afe1a78c31934f0492422700f61a0ffc0/src/transformers/generation/configuration_utils.py#L993), we are trying to log the config, which has json object in it, which would fail because constraint class doesn't support such serialization. 
This error can also occur at `from_pretrained` method, where we are calculating hash of the config in line [#952](https://github.com/huggingface/transformers/blob/a564d10afe1a78c31934f0492422700f61a0ffc0/src/transformers/generation/configuration_utils.py#L952) and [#956](https://github.com/huggingface/transformers/blob/a564d10afe1a78c31934f0492422700f61a0ffc0/src/transformers/generation/configuration_utils.py#L956). 

I think the easy fix would be have a serialization method for constraint class that can be triggered. 

Can I propose a PR for this? For this, I think we might have to go through all possible class objects that can be consumed by GenerationConfig class, and implement a general purpose serialization mechanism, easiest is to replace class object with `obj.__dict__` for the purpose of serialization. From my understanding, serialization is only for logging and hashing purposes, and it might not have an impact on actual flow of execution. 

@gante I would like to propose a PR but I am not sure what would be ideal approach, would like to get suggestions to move forward.  :)

**Comment by OS-leonardopratesi** [comment]
This should serialize also the code of my custom defined constraints, I don't see a way of doing this without pickle.

**Comment by gante** [comment]
Hi folks 👋  Apologies for the late response -- constraints in general is very poorly maintained at the moment. We're refactoring beam methods, let's hold on changes to constraints for now. See related trackers: [1](https://github.com/huggingface/transformers/issues/28981) [2](https://github.com/huggingface/transformers/issues/30810)
