### ISSUE TITLE
NER tutorial: run_tf_ner.py reports an entity number not matching the one in the .txt files

### ISSUE THREAD

**Issue by ChessMateK** [huggingface/transformers#3125]
Hi everyone,

I'm following this tutorial https://github.com/huggingface/transformers/tree/master/examples/ner .

Generated results are the same but I noticed that the reported entity numbers ("support" column) are not the same B-entity numbers I can count through Notepad++ in *.txt files used as source for training, validation or test.

Which is my mistake?

Thank you.

UPDATE: run_ner.py works correctly. I suppose there is a bug in run_tf_ner.py.

I also tag @stefan-it who is the only mentioned in tutorial. Thank you Stefan.

**Comment by stefan-it** [comment]
I'm currently not able to run the TF ner training script - I'm using TF in version 2.0.0b1 and the following error message is thrown:

```bash
...
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops_v2.py", line 769, in _assert_float_dtype
    raise ValueError("Expected floating point type, got %s." % dtype)
ValueError: Expected floating point type, got <dtype: 'int32'>.
```

🤔

**Comment by over-shine** [comment]
I met the same problem. The script "run_tf_ner.py" can not get the same report result, have you solved it?

**Comment by over-shine** [comment]
I have solved this issue. Because I evaluate the ner model with train.txt, and when the mode is "train", the dataset will be repeated and shuffled, so the support item of metric report is not same with the last report.

When I copy train.txt as dev.txt and change mode from "train" to "dev" during evaluation in the load_and_cache_examples, the dataset will not be repeated and shuffled and the report is reproductive.
