### ISSUE TITLE
LLama3 won't stop when provide eos_token_id

### ISSUE THREAD

**Issue by lucasjinreal** [huggingface/transformers#31362]
I have a model genereate config like this:

```
output_ids = model.generate(
                input_ids,
                images=images_tensor,
                do_sample=False,
                temperature=0.2,
                max_new_tokens=1024,
                streamer=streamer,
                use_cache=True,
                # cache_position=None,
                pad_token_id=tokenizer.eos_token_id,
                eos_token_id=conv.stop_token_ids,
                stopping_criteria=[stopping_criteria],
            )
```

the pad token id is <|end_of_text|> it's wont stop when <|eot_id|> got which needed for each assitatn message stops.

So I provide that id in eos_token_id, but still, it doesn't respect it. how to resolve it?

**Comment by zucchini-nlp** [comment]
Hey, can your provide a more complete code to reproduce it (e.g. model_id, what's "conv.stop_token_ids")?

In general providing in `eos_token_id` an int or a list of int (when two or more tokens can be `eos`) should stop generation. Make sure that the generated text contains one of the provided `eos_token_ids`, because sometimes the same string can be mapped to another sequence of `token_ids`

**Comment by gasvn** [comment]
I get a similar issue. The reason for this might be that part of `<|eot_id|>` is combined with other output and becomes two tokens. For example,  `Over.<|eot_id|>` is tokenized to `Over.<|e` and `ot_id|>`. Is there a way to solve this issue? Or does the tokenizer in Transformers support first tokenizing the message, then adding the token id of <|eot_id|>?

**Comment by gasvn** [comment]
@zucchini-nlp

**Comment by zucchini-nlp** [comment]
@gasvn yeah, that could be the reason. If you want to fix the generation and stop at "<eot_id>", you can use [StopStringCriteria](https://huggingface.co/docs/transformers/en/internal/generation_utils#transformers.StopStringCriteria) and pass eos as a string. Should be working.

For skipping special tokens at tokenizer level, I believe you can use ["add_special_tokens" arg](https://huggingface.co/docs/transformers/main_classes/tokenizer#transformers.PreTrainedTokenizer.__call__) when calling tokenizer, and manually append EOS and BOS later. Ping @ArthurZucker and @itazap

**Comment by ArthurZucker** [comment]
If you are training the base model, it is expected that the eot token is not special nor added because the base model was not trained with it. You need to 1st add it, then make sure you set `add_eos_token = True` and set `add_special_tokens = True` when encoding to automatically add your new eos token. Set it to false to skip the addition of bos en eos
