### ISSUE TITLE
phi3 model is not running in cpu

### ISSUE THREAD

**Issue by devang-choudhary** [huggingface/transformers#32243]
1) microsoft/Phi-3-small-128k-instruct is not running on cpu  (ICELAKE or Graviton) 
the script which i was using : 

![Screenshot 2024-07-26 165001](https://github.com/user-attachments/assets/e0b2ee77-1f03-4d83-9865-78f39f5044f3)

Error I got for Graviton:-
![Screenshot 2024-07-26 162942](https://github.com/user-attachments/assets/040d5bd1-1c10-438d-b885-d62371beecbf)

Error for ICELAKE :-

![Screenshot 2024-07-26 163015](https://github.com/user-attachments/assets/efd77b24-7849-48f9-9bce-28d65f9cd234)

 
2) microsoft/Phi-3-mini-128k-instruct and other mini models are running on cpu but showing warning that You are not running the flash-attention implementation, expect numerical differences.
![Screenshot 2024-07-26 170522](https://github.com/user-attachments/assets/f9a2bcc5-a18b-4c72-94e8-2828e4f02426)

but the implementation of Flash attention for cpu is available in pytorch aten native is there any flag I need to enable in order to use the flash attention for cpu.

**Comment by qubvel** [comment]
Probably, similar to (the same error regarding Flash Attention)
 - https://github.com/huggingface/transformers/issues/32201

**Comment by zucchini-nlp** [comment]
Hey @devang-choudhary ! 

Similar issue was reported at https://github.com/huggingface/transformers/issues/32365. I just digged a bit, Phi3-small models are not natively supported in Transformers because their implementation is slightly different from mini/medium series. So the error you're seeing is related to code in the `hub` and seems like you are unable to `import flash_attn`. FA2 requires CUDA and particular hardware to be installed/run properly (see [here](https://huggingface.co/microsoft/Phi-3-small-128k-instruct#hardware) and [here](https://github.com/Dao-AILab/flash-attention?tab=readme-ov-file#installation-and-features))

Also, imo we should add native support for Phi3-small but not sure if anyone is already working on it. Nice to see if we can make it work without relying on FA2. cc @ArthurZucker for that

**Comment by ArthurZucker** [comment]
I think it is supported, just their checkpoints are not in the correct format. I don't remember because they are a bit messy and don't seem willing to integrate it natively 😓

**Comment by zucchini-nlp** [comment]
For phi-small it is also the code, because they have some interleaving of two dense/sparse attention and changes the activation function. Sad to hear they don;t want to contribute, should we work on integration ourselves then?

**Comment by ArthurZucker** [comment]
seems to be asked a bit, but I am not entirely sure, we can open an issue for community contribution!

**Comment by zucchini-nlp** [comment]
Agreed, it is too much for the community. I meant we can work on if it's asked a lot, but we'll will be slow
