### ISSUE TITLE
'weight' must be 2-D

### ISSUE THREAD

**Issue by bahriwissal** [huggingface/transformers#32285]
### System Info

    transformers version == 4.42.4
    dp-transformers version == 1.0.1
    accelerate version == 0.29.3
    llm == Distil-gpt2
    torch version == 2.0.0
    The model is runned under ddp with 2 GPUs

### Who can help?

@ArthurZucker 

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Hello, I am trying to train a Tabula (https://github.com/zhao-zilong/Tabula) model using FSDP. I rewrote my Tabula trainer without middle padding to use the FSDP model. I added the parameters for training arguments fsdp=full_shard, and then I used setup and multiprocessing.spawn to run my code. When I run my code using DDP, it works, but when I run it using FSDP, the training works, but the sampling does not. I get the error 'weight' must be 2-D. I know that FSDP works because when I print the memory usage, the memory reduces while using FSDP instead of DDP.

### Expected behavior

The sampling function should generate data.

**Comment by LysandreJik** [comment]
Hey @bahriwissal we'd love to help you with `transformers` but distilgpt is a very heavily tested model we know should work; so the problem likely comes from your script. You can share it here to get opinions/help from the community but it'd be awesome if you could reduce it to a minimal reproduction script so that we may help the best.
