### ISSUE TITLE
index is out of bounds for dimension with size 0 (after  4.41.2)

### ISSUE THREAD

**Issue by geekodour** [huggingface/transformers#32321]
### System Info

see this issue for more details: https://github.com/kijai/ComfyUI-moondream/issues/19

Getting this error post this version which is preventing usage of the latest version. I'll try digging for a fix for this but otherwise if seems like an easy pick might be worth fixing.

### Who can help?

@amyeroberts  @ArthurZucker 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

 https://github.com/kijai/ComfyUI-moondream/issues/19

### Expected behavior

 https://github.com/kijai/ComfyUI-moondream/issues/19

**Comment by zucchini-nlp** [comment]
Hey @geekodour ! From what I see the Phi-model code is totally defined within moondream, while they are calling to the `transformers` implementation of `generate()`. I recommend you to open an issue in moondream since they would have to update Phi modeling code, we have been actively modifying it lately.
