### ISSUE TITLE
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

### ISSUE THREAD

**Issue by fancy45daddy** [huggingface/transformers#32345]
### System Info

google colab with T4 runtime

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I run the following code in google colab
```
!python3 -m pip install -U diffusers
import diffusers
pipeline = diffusers.DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", use_safetensors=True)
pipeline.to('cuda')
pipeline("An image of a squirrel in Picasso style").images[0]
```
I get The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

But which line the transformers.utils.move_cache() should goto? Above pipeline = diffusers.DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", use_safetensors=True)
or below?

I try both, but none of them work!!!

### Expected behavior

no warning

**Comment by LysandreJik** [comment]
This should be somewhat handled by https://github.com/huggingface/transformers/pull/31694

I don't have the bandwidth to ship it right now, cc @ydshieh in case you have a few minutes to spare at some point and want to help on this issue

**Comment by ydshieh** [comment]
I am doing

```
!python3 -m pip install -U diffusers
import diffusers
import transformers
transformers.utils.move_cache()

pipeline = diffusers.DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", use_safetensors=True)
```
and no more issue you mentioned.

**Comment by LuisRG30** [comment]
I think this still needs to be addressed. I have a docker image that is supposed to be reliable and crashes because of the cache issue. It says the cache is impossible to find from huggingface when it previously did not request it. 

Please advice on the fix for a docker cuda environment. Running: pipe = DiffusionPipeline.from_pretrained(
            "stabilityai/stable-diffusion-xl-base-1.0",
            torch_dtype=torch.float16,
            use_safetensors=True,
            variant="fp16",
        )
    pipe = pipe.to("cuda")

**Comment by ydshieh** [comment]
Hi @LuisRG30 . I believe the original issue reporter here didn't have a crash but just state there shouldn't have a warning and asking about the usage of `move_cache()`. (and even with that information, I wasn't able to reproduce on Colab)

For the crash you encounter, I would suggest opening a new issue with more detailed information, for example, the traceback / error message.

 I see you are using docker, it would be great if we can access to it to check, otherwise a step of step process to create the env. in order to reproduce.
