### ISSUE TITLE
No InternVLChatModel和InternVisionModel class in the transformers source code

### ISSUE THREAD

**Issue by AmazDeng** [huggingface/transformers#33611]
Why can the InternVLChatModel(https://huggingface.co/OpenGVLab/InternVL2-2B) and InternVisionModel(https://huggingface.co/OpenGVLab/InternViT-6B-448px-V1-5) models be loaded in the following way, but these two classes, InternVLChatModel and InternVisionModel, cannot be found in the transformers code? What is the reason for this?

Can you help me look at this issue? @zucchini-nlp @sgugger @LysandreJik @ydshieh

InternVLChatModel
```
import torch
from transformers import AutoTokenizer, AutoModel
path = "OpenGVLab/InternVL2-2B"
model = AutoModel.from_pretrained(
    path,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    use_flash_attn=True,
    trust_remote_code=True).eval().cuda()

```

InternVisionModel
```
import torch
from PIL import Image
from transformers import AutoModel, CLIPImageProcessor

model = AutoModel.from_pretrained(
    'OpenGVLab/InternViT-6B-448px-V1-5',
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True).cuda().eval()

image = Image.open('./examples/image1.jpg').convert('RGB')

image_processor = CLIPImageProcessor.from_pretrained('OpenGVLab/InternViT-6B-448px-V1-5')

pixel_values = image_processor(images=image, return_tensors='pt').pixel_values
pixel_values = pixel_values.to(torch.bfloat16).cuda()

outputs = model(pixel_values)

```

**Comment by molbap** [comment]
Hi @AmazDeng, the reason is `trust_remote_code=True` and the modeling code is present under the files of the hub repositories you linked. If you look there for instance https://huggingface.co/OpenGVLab/InternVL2-2B/blob/main/modeling_internvl_chat.py, you'll find the modeling code corresponding to these models, uploaded by the original authors directly. 

Since there is no issue here, I'm closing, feel free to open if an issue arises or check out our [forums](https://discuss.huggingface.co/)!
