### ISSUE TITLE
Add DBRX GGUF Support Error

### ISSUE THREAD

**Issue by cjfghk5697** [huggingface/transformers#33978]
### System Info

- `transformers` version: 4.46.0.dev0
- Platform: Linux-6.1.85+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.24.7
- Safetensors version: 0.4.5
- Accelerate version: 0.34.2
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.4.1+cu121 (True)
- Tensorflow version (GPU?): 2.17.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.5 (gpu)
- Jax version: 0.4.33
- JaxLib version: 0.4.33
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: Tesla T4

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

 [Check it in Colab](https://colab.research.google.com/drive/1-bwbck3IjOf0-uGw4amheQEUWk7XJVBb?usp=sharing)
 Draft Code #33977 

### Expected behavior

Hi, I'm working on dbrx to support GGUF architecture(#33260). `ggml.py` has been modified for this purpose, but I'm encountering the following error: "TypeError: expected str, bytes or os.PathLike object, not NoneType".

It seems the error is caused by `gguf_checkpoint_path` being defined as `None` in the `load_gguf_checkpoint` function in `modeling_gguf_pytorch_utils.py`. I'm currently tracking down why it is being set to `NoneType`.

Upon investigation, I found that the value is being passed as `NoneType` at line 2441 in `tokenization_utils_base.py`. I need to understand why this value, which previously worked correctly, is now being set to `NoneType` and address this issue.
```python
try:
    tokenizer = cls(*init_inputs, **init_kwargs)
```
It seems that the initial value for the GGUF file is being set to `NoneType`.

Here's the code for reference: [Check it in Colab](https://colab.research.google.com/drive/1-bwbck3IjOf0-uGw4amheQEUWk7XJVBb?usp=sharing)

Any help would be greatly appreciated.

**Comment by VladOS95-cyber** [comment]
Hey @cjfghk5697, @SunMarc ! If I am not mistaken, It is not a bug, It happens because tokenization_utils_fast.py L122 - `gguf_param = load_gguf_checkpoint(kwargs.get("vocab_file"))` tries to get vocab_file from tokenizer which is None by default. If you don't explicitly assign `vocab_file=vocab_file` and `merges_file=merges_file` in you case I suppose in tokenization_gpt2_fast.py L100-101, then, even if you provide those in tokenizer object creation, kwargs.get("vocab_file") still will not get vocab file and returns None. So, you could try to fix `vocab_file=vocab_file` and `merges_file=merges_file` in tokenization_gpt2_fast.py and check the behaviour.

**Comment by cjfghk5697** [comment]
@VladOS95-cyber, thank you so much!! 😭😭😭
I really appreciate your help. I checked that my tokenizer works well, haha. Thanks a lot!
