### ISSUE TITLE
Add barlow twins

### ISSUE THREAD

**Issue by dame-cell** [huggingface/transformers#34008]
### Model description

I'm seeking guidance on potentially contributing a pretrained ResNet50 model to the Hugging Face model hub. but the problem is that they did not provided the linear weights which they evaluated the model on the imagenet1k images 
would contributing this model still seems viable

Model details:
- Architecture: ResNet50 
- Training method: Self-supervised learning 
- Weights: Pretrained backbone weights available, but no linear classification layer

in their repo they provided the weights for both the renset50 and full checkpoints but both do not contain linear weights 

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

model implementation -  [barlow-twins](https://github.com/facebookresearch/barlowtwins)
model weights - [weights](https://github.com/facebookresearch/barlowtwins)
paper - [paper](https://arxiv.org/pdf/2103.03230)

**Comment by dame-cell** [comment]
@amyeroberts @

**Comment by LysandreJik** [comment]
cc @qubvel

**Comment by qubvel** [comment]
Hi @dame-cell, thanks for your interest in contribution! We already have [resnet50](https://github.com/huggingface/transformers/tree/main/src/transformers/models/resnet) model in transformers, if you are interested in this particular weights, you can convert them to a compatible format and put it on the [Hub](https://huggingface.co/models) so that anyone can use it!

**Comment by dame-cell** [comment]
@qubvel  I see thank you so much for  replying I got it
