### ISSUE TITLE
requests.exceptions.ReadTimeout on already cached/downloaded model using SentenceTransformers

### ISSUE THREAD

**Issue by HeAndres** [huggingface/transformers#34162]
### System Info

transformers version: 44.2
python version: 3.11.6
system OS: Linux

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

When HuggingFace servers are down or you have no internet connection, try to initialize an already downloaded/cached model. I was using SentenceTransformers (running SentenceTransformer(model_name_or_path=model_id, device=my_device), but the problem comes from the transformers library, so I'm not sure which library should make the changes.

### Expected behavior

The model loads properly without requiring any connection to the hub.

**Comment by LysandreJik** [comment]
Hey @HeAndres, you can force transformers to run offline a few different ways; check this documentation for more info: https://huggingface.co/docs/transformers/v4.45.2/en/installation#offline-mode

**Comment by HeAndres** [comment]
I could try to work on a PR to change this, let me know if it would be of help!

**Comment by LysandreJik** [comment]
The assumption you should have is for `from_pretrained` to always try and fetch the latest revision of the model; if it fails to get it, I believe it's much safer to let the user know it couldn't retrieve it rather than use a previous version from the cache. 

This seems to me like a potential pitfall/debugging hell users would not understand. I personally think having the ability to load from cache but requiring the user to specify that it should take from the cache is the least dangerous path
