### ISSUE TITLE
Limit number of parametes logged with `MLflowCallback`

### ISSUE THREAD

**Issue by cecheta** [huggingface/transformers#34276]
### Feature request

Add a new environment variable, such as `MLFLOW_MAX_LOG_PARAMS`, which can limit the number of parameters logged by the `MLflowCallback`.

### Motivation

When using mlflow in Azure ML, there is a limit of 200 parameters that can be logged in a single run, meaning that when attempting to run a training job, the callback needs to be disabled entirely, or the module needs to be "monkeypatched" to limit the number of params logged.

### Your contribution

I will submit a PR

**Comment by LysandreJik** [comment]
cc @ydshieh what do you think? :)

**Comment by ydshieh** [comment]
Hi @cecheta 

Happy to have a way to unblock this situation. 

- This `200` limit is from Azure and not from `mlflow` itself, right?
- Does `Azure` provide any way to change `mlflow` behavior regarding this? Look at https://github.com/Azure/azure-sdk-for-python/issues/35685 and it seems the answer is no.

Regarding the approach, maybe

```python
class MLflowCallback(TrainerCallback):

    def __init__(self, max_log_params=None):
```
instead of a environment variable?
