### ISSUE TITLE
Auto Classes docs _toctree

### ISSUE THREAD

**Issue by jun048098** [huggingface/transformers#34672]
Is the path to [Auto Classes](https://huggingface.co/docs/transformers/v4.46.2/en/model_doc/auto) docs appropriate?

It is written as ```model_doc/auto``` in [line 275 of _toctree.yml](https://github.com/huggingface/transformers/blob/a06a0d12636756352494b99b5b264ac9955bc735/docs/source/en/_toctree.yml#L275). 

<https://huggingface.co/docs/transformers/v4.46.2/en/model_doc/auto>

Because of this, the end of the url is ```model_doc/auto```. However, in the left list of [docs](https://huggingface.co/docs/transformers/v4.46.2/en/model_doc/auto), it belongs to ```MAIN CLASSES```.

Should it belong to ```main_classes``` like other docs?

Or is there a special reason why the path to _toctree is ```model_doc/auto```?

If it's an error, can I change that line in _toctree to ```main_classes/auto```?

Please check @stevhliu

Thank You!

**Comment by stevhliu** [comment]
Yeah, this is correct. When the docs were reorganized, the `AutoClass` was moved into the Main classes section from the Models section because it included other objects (configuration, processors, tokenizers, etc.) that weren't just models. To avoid breaking links in the docs, we just moved `model_doc/auto` under Main classes instead of renaming it.

**Comment by jun048098** [comment]
I understand. I will close this issue without making any changes. Thank you for checking the issue!
