### ISSUE TITLE
CircleCI ExamplesTests::test_run_squad failing

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#3469]
Started happening at  https://github.com/huggingface/transformers/pull/3428
and has been happening consistently.

scroll all the way down for [traceback](https://circleci.com/gh/huggingface/transformers/26044?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by sshleifer** [comment]
![image](https://user-images.githubusercontent.com/6045025/77713019-b7163c80-6fab-11ea-9b78-0ed668943c18.png)

Happy to help on this @LysandreJik @patrickvonplaten

**Comment by patrickvonplaten** [comment]
The test runs fine locally on my computer. A couple of wild thoughts:

- It happened after merging #3411 and #3428 which adds quite some long `t5-large` and `t5-base` tests to the test examples. Could this test fail because of some kind of time-out error?
- The test consumes 10GB RAM when running locally - this doesn't seem too much to fail though.

**Comment by julien-c** [comment]
Did you try connecting to a failing circle-ci box, to investigate?

**Comment by visonger** [comment]
unsubscribe




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Julien Chaumond"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 晚上10:15
收件人:&nbsp;"huggingface/transformers"<transformers@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [huggingface/transformers] CircleCI ExamplesTests::test_run_squad failing (#3469)



 Did you try connecting to a failing circle-ci box, to investigate?

**Comment by patrickvonplaten** [comment]
I think this is solved with https://github.com/huggingface/transformers/pull/3485 .
