### ISSUE TITLE
Argument “never_split” not working on bert tokenizer

### ISSUE THREAD

**Issue by acmilannesta** [huggingface/transformers#3518]
I used the ```never_split``` option and tried to retain some tokens. But the tokenizer still divide them into wordpieces. 

```
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', never_split=['lol'])
tokenizer.tokenize("lol That's funny")
['lo', '##l', 'that', "'", 's', 'funny']
```
**A link to original question on Stack Overflow**: 
https://stackoverflow.com/posts/60914793/edit

**Comment by BramVanroy** [comment]
Does this problem arise with the fast tokenizer too? Can you try both:

```python
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', never_split=['lol'], use_fast=True)
# and
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', never_split=['lol'], use_fast=false)
```

**Comment by acmilannesta** [comment]
> Does this problem arise with the fast tokenizer too? Can you try both:
> 
> ```python
> tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', never_split=['lol'], use_fast=True)
> # and
> tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', never_split=['lol'], use_fast=False)
> ```

Tried. Neither works...

**Comment by BramVanroy** [comment]
This problem still exists where the "never_split"

```python
from transformers import BertTokenizer
USE_FAST = False

tokenizer = BertTokenizer.from_pretrained("bert-base-cased",
                                          use_fast=USE_FAST,
                                          never_split=['lol'],
                                          do_basic_tokenize=True)
print(tokenizer.tokenize(" lol That's funny"))
```
I started going through the code, but it's a bit of a rabbit hole since you have "never_split" as an init argument of the basic tokenizer as well as the pretrained tokenizer, but also as part of the `tokenize` method. It isn't clear to me exactly where it is used.

Perhaps some doc changes are needed as well, since it is typed as boolean:

https://github.com/huggingface/transformers/blob/35df91148545e09cd199d89e707043eba5434f59/src/transformers/tokenization_bert.py#L133

cc @n1t0 @mfuntowicz

**Comment by n1t0** [comment]
I just tested the last example provided by @BramVanroy and it seems to work after #4723. Do not hesitate to reopen if needed!
