### ISSUE TITLE
why isn't AlbertForMultipulChioce in modeling_albert?

### ISSUE THREAD

**Issue by oashua** [huggingface/transformers#3522]
# ❓ Questions & Help

## Details

I just copy code from RobertaForMultipleChoice to modeling_albert and change all 'roberta' to 'albert', but the loss didn't goes dowm evidently. And the result is even worse than articles.

**A link to original question on Stack Overflow**:

**Comment by Chenyzsjtu** [comment]
I have come accross the same problem when I was testing RACE for Albert.
Your implementation might be right because there are few differences betweent "roberta" and "albert" finetune heads.
If you are testing RACE like me, the real problem may lie in the lack of max_qa_length implementation in run_multiple_choice.py.
