### ISSUE TITLE
Checking that the LM actually trained 

### ISSUE THREAD

**Issue by nikkon3** [huggingface/transformers#3728]
I have trained a gpt2 from scratch with the way that is decribed in that post https://huggingface.co/blog/how-to-train  . 
Just in the step 4, where he checks if the trained model actually works, he uses from pipeline the 
"fill-mask" but that works only for models with  masked language modeling objective. 
Exists something similar i could use like "fill-mask" for my case?

**Comment by julien-c** [comment]
Yes: simply `model.generate()` (not even a need for a Pipeline in that case)

cc @patrickvonplaten

**Comment by patrickvonplaten** [comment]
I'd check if 'GPT2' works by sampling from a simple prompt. E.g.:

```
output = model.generate(tokenizer.encode('The president', return_tensors='pt'), do_sample=True)
tokenizer.decode(output[0])
```

**Comment by enzoampil** [comment]
Thanks for clarifying!  I was about to consider sending a PR for a `GenerationPipeline` under `transformers.pipeline`.

**Comment by enzoampil** [comment]
I have an initial version of `GenerationPipeline` [here](https://github.com/enzoampil/transformers/blob/generation_pipeline/src/transformers/pipelines.py), where I've registered it to the `pipeline` function using `gpt2` as the default.

The implementation is based on the approach taken in `run_generation.py`, which means the forward pass uses the `model.generate()` method explained by @julien-c above.

However, I noticed that the code above is only working so far for `open-ai` and `gpt2`. Will find the root cause in the next few days.

**Comment by enzoampil** [comment]
[UPDATE] The issues above have been resolved and I'll be sending a PR soon.

Tutorial [here](https://colab.research.google.com/drive/1PHmYRpgzdMeSR68i4w5tPfUjlv0npCQz) for running `GenerationPipeline` for the following LM models:
1. OpenAI GPT
2. OpenAI GPT-2
3. Transformer-XL
4. XML
5. XLNet
6. T5
7. CTRL

**Comment by patrickvonplaten** [comment]
You're PR looks very nice so far :-) I will take a look early next week!

**Comment by enzoampil** [comment]
Thanks!
