### ISSUE TITLE
Loading pipeline("summarization") failed

### ISSUE THREAD

**Issue by asymmetric-supernova** [huggingface/transformers#3731]
Hi guys, when I try to load pipeline("summarization") I get the following error:

`Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "PATH", line 11, in <module>
    summarizer = pipeline("summarization")
  File "PATH\venv\lib\site-packages\transformers\pipelines.py", line 1626, in pipeline
    return task_class(model=model, tokenizer=tokenizer, modelcard=modelcard, framework=framework, task=task, **kwargs,)
  File "PATH\venv\lib\site-packages\transformers\pipelines.py", line 367, in __init__
    task_specific_params = self.model.config.task_specific_params
AttributeError: 'NoneType' object has no attribute 'config'
`

**Setup:** 
Python: 3.7.6
transformers==2.8.0
tensorboard==2.0.2
tensorflow==2.0.0
tensorflow-estimator==2.0.1
tensorflow-hub==0.7.0

```
from transformers import pipeline
from transformers import TFAutoModelWithLMHead, AutoTokenizer

summarizer = pipeline("summarization")
```

**Comment by julien-c** [comment]
The default summarization pipeline doesn't have support for TF unfortunately, but we should probably add an explicit error message @sshleifer

**Comment by BenWhiteJam** [comment]
+1

**Comment by patrickvonplaten** [comment]
You can use `T5's` TF summarization though, like:
`pipeline("summarization", model="t5-base", framework="tf")`

**Comment by patrickvonplaten** [comment]
I think the error has nothing to do with "summarization" or "Bart". I think the problem is that you were calling a pytorch pipeline without having pytorch installed. If this happens a weird error message like the one above is thrown out. We should probably add a better error message here:
https://github.com/huggingface/transformers/blob/700ccf6e35616fcbee59de81edd60cec9e14fb6b/src/transformers/pipelines.py#L1567
Something along the lines: `if modelclass in None: <good_error_message>`

**Comment by patrickvonplaten** [comment]
To run pipelines in TF, the argument `framework="tf"` should be added to `pipeline()`

**Comment by julien-c** [comment]
I don't think that's right, @patrickvonplaten.

Pipelines use TF automatically if that's what you have instead of PyTorch: ie it does `framework = "pt" if is_torch_available() else "tf"`

However, as I was saying, the **default** (bart-based) summarization pipeline doesn't have a TF model, see line 1447:
```python
"default": {
            "model": {"pt": "bart-large-cnn", "tf": None},
}
```

**Comment by patrickvonplaten** [comment]
Sorry, you are 100 % right @julien-c! 

I overlooked this line:
https://github.com/huggingface/transformers/blob/700ccf6e35616fcbee59de81edd60cec9e14fb6b/src/transformers/pipelines.py#L1564

So, we do need a better error message for pipelines that have a `None` as a default model.

**Comment by asymmetric-supernova** [comment]
@julien-c works fine with pytorch, thanks

**Comment by BenWhiteJam** [comment]
Thanks, works for me as well!
As mentioned before, the improved error message would help a lot.

**Comment by julien-c** [comment]
Do you want to take a stab at a better error message for this @patrickvonplaten?
