### ISSUE TITLE
Cannot Load bert-base-japanese tokenizer

### ISSUE THREAD

**Issue by bayartsogt-ya** [huggingface/transformers#4060]
# 🐛 Bug

## Information

Model I am using BertJapaneseTokenizer:

Language I am using the model on Japanese:

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is: Just to load

## To reproduce
```
>>> from transformers import BertJapaneseTokenizer
>>> tokenizer = BertJapaneseTokenizer.from_pretrained('bert-base-japanese')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bayartsogtyadamsuren/DDAM-Projects/isid/myenv/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 393, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/Users/bayartsogtyadamsuren/DDAM-Projects/isid/myenv/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 496, in _from_pretrained
    list(cls.vocab_files_names.values()),
OSError: Model name 'bert-base-japanese' was not found in tokenizers model name list (bert-base-japanese, bert-base-japanese-whole-word-masking, bert-base-japanese-char, bert-base-japanese-char-whole-word-masking). We assumed 'bert-base-japanese' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.
```

## Expected behavior

To load

## Environment info
     
- `transformers` version: 2.7.0
- Platform: Darwin-18.7.0-x86_64-i386-64bit
- Python version: 3.7.4
- PyTorch version (GPU?): 1.3.1
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

**Comment by reo11** [comment]
Hi I had the same issue and I solved it by downloading the required files locally with the steps below.
1. Download [vocab.txt](https://github.com/huggingface/transformers/blob/455c6390938a5c737fa63e78396cedae41e4e87e/src/transformers/tokenization_bert_japanese.py#L33), [config.json](https://github.com/huggingface/transformers/blob/455c6390938a5c737fa63e78396cedae41e4e87e/src/transformers/configuration_bert.py#L42), [pytorch_model.bin](https://github.com/huggingface/transformers/blob/455c6390938a5c737fa63e78396cedae41e4e87e/src/transformers/modeling_bert.py#L51) from the source URL

2. Enter the folder containing the three files in the from_pretrained method
e.g. BertModel.from_pretrained ('./models/bert-base-japanese/')
where
```
─ models
 └- bert-base-japanese
     ├- vocab.txt
     ├- config.json
     └- pytorch_model.bin
```
I think this is probably an obstacle caused by a change in the path on S3 due to this commit. The version of transformers installed by pip is old and you may be pointing to the wrong path.
https://github.com/huggingface/transformers/commit/455c6390938a5c737fa63e78396cedae41e4e87e

Reinstall with the latest transformers and it should work.
```
git clone git@github.com: huggingface / transformers.git
pip install ./transformers
```

**Comment by julien-c** [comment]
I apologize, it's my fault. I `mv`ed files around instead of `copy`ing them as we do usually, so I broke backward compatibility for the `bert-base-japanese` models.

As @reo11 said, you'll need to install from source for now. You can also do: 
`pip install git+git://github.com/huggingface/transformers.git`

Sorry about that.

**Comment by bayartsogt-ya** [comment]
@reo11 Thank you so much!
@julien-c  Thank you for you response. Since a lot of us trying to use transformers in production too, please consider having stable workflow. (Anyways you guys doing great!)
