### ISSUE TITLE
[Request] NER Scripts on CoNLL 2003 dataset 

### ISSUE THREAD

**Issue by gyuwankim** [huggingface/transformers#4250]
# 🚀 Feature request

## Motivation
Current NER scripts (data preparation, train, and evaluation) is for the GermEval 2014 dataset.
It is very nice. However, according to the original BERT paper, experiments are done on the CoNLL-2003 dataset. It would be much better if the NER script could reproduce the results on this dataset.

## Your contribution
Looking forward to the feedback. Thanks in advance!

**Comment by stefan-it** [comment]
Hi @gyuwankim the problem with English CoNLL dataset is, that it is not freely available (because it requires access to Reuters corpora in order to create it from scratch with the provided scripts).

You can find the dataset somehow on GitHub, but legally this is very dubious (and you have no guarantee that it is the original dataset).

That's the reason why I did use the GermEval 2014 dataset :)

**Comment by stefan-it** [comment]
But what you think about adding a detailed description of training a NER model on the WNUT17 dataset?

Data can be accessed here: https://github.com/juand-r/entity-recognition-datasets/tree/master/data/WNUT17

I could add a short example with some resuls (for other Transformer-based models as well). So we have both German and an English example of how to use the NER script :)

/cc @julien-c

**Comment by stefan-it** [comment]
Additionally, the BERT evaluation strategy cannot be simply reproduced, see this [thread](https://github.com/allenai/allennlp/pull/2067#issuecomment-443961816) on the problem.
