### ISSUE TITLE
Save pretrained MarianTokenizer

### ISSUE THREAD

**Issue by NonaryR** [huggingface/transformers#4371]
Hello! 
I can't save pretrained MarianTokenizer, it's raising NotImplementedError as a subclass of PretrainedTokenizer.

**Comment by NonaryR** [comment]
Also, how can I transfer to cuda `BatchEncoding` object which return after call `prepare_translation_batch` method on `MarianTokenizer`

**Comment by stefan-it** [comment]
This could be fixed by specifiying a `save_vocabulary` function, like it is used in:

https://github.com/huggingface/transformers/blob/7defc6670fa76e857109e1b99f3e919da8d11f42/src/transformers/tokenization_xlm_roberta.py#L292-L311

(both source and target vocab needs to be written),

Additionally, it would be awesome if the `MarianTokenizer` class would be `pickle`-able using `__getstate__` and `__setstate__` methods :)

/cc @sshleifer

**Comment by sshleifer** [comment]
@NonaryR `BatchEncoding.to(device:str)` should work.
Will fix vocab saving, great catch!

**Comment by NonaryR** [comment]
Thank you,  `to(device)` helped!
I can close the task if you want it. 
Also, many thanks for this new release with all these new awesome translation models, it will bring significant change to the community!!

**Comment by erikchwang** [comment]
But how can you load the saved MarianTokenizer from your local directory? 
Can anyone give a complete example about how to save and load MarianTokenizer?

**Comment by erikchwang** [comment]
Can anyone help with this issue: #5040 ?
