### ISSUE TITLE
tokenizer.vocab has not changed after using add_tokens

### ISSUE THREAD

**Issue by suyulan** [huggingface/transformers#4486]
# ❓ Questions & Help

## Details

When I use the add_tokens, I have the following problems
```python3
# len(tokenizer)  == 30522
 tokens_dict = ['[HL]']
 num_added_toks = tokenizer.add_tokens(tokens_dict)
# len(tokenizer)  == 30523
# But tokenizer.vocab_size == 30522
```
Should I change the dictionary by myself ?

**Comment by BramVanroy** [comment]
This is the expected behaviour: `len(tokenizer)` shows you the actual size, whereas `.vocab_size` tells you the original size.

https://github.com/huggingface/transformers/blob/a08652772791fdaeed6f263b1a99926ca64be5dc/src/transformers/tokenization_utils.py#L2285-L2290

PS: don't forget to update your model's embeddings!

```python
model.resize_token_embeddings(len(tokenizer))
```

**Comment by kaankork** [comment]
I find it confusing that the vocab_size doesn't get modified. Also, the Hugging Face documentation describes `tokenizer.add_tokens` as follows: 

> Add a list of new tokens to the tokenizer class. If the new tokens are not in the vocabulary, they are added to it with indices starting from length of the current vocabulary.
