### ISSUE TITLE
Tokenize something with a "." in between Decode these ids, you will find it mismatch

### ISSUE THREAD

**Issue by Xunzhuo** [huggingface/transformers#4497]
🐛 Bug
Information
Model I am using (Bert, XLNet ...): XLNet

Language I am using the model on (English, Chinese ...): Chinese
The problem arises when using: Tokenizer

 the official example scripts: (give details below) N/A
 my own modified scripts: (give details below) N/A
The tasks I am working on is: Any

 an official GLUE/SQUaD task: (give the name) N/A
 my own task or dataset: (give details below) N/A
To reproduce

Load any BERT tokenizer
Tokenize something with a "." in between
Decode these ids, you will find it mismatch
x = tokenizer.encode('AN.C', add_special_tokens=False)
z = tokenizer.decode(x)
It prints:

AN. C
Expected behavior
AN.C
Environment info
transformers version:
Platform: CentOS
Python version: 3.6
PyTorch version (GPU?): GPU
Tensorflow version (GPU?): GPU
Using GPU in script?: NO
Using distributed or parallel set-up in script?: NO

**Comment by nateraw** [comment]
Your use case seems specific, so maybe you should try a custom Tokenizer via the `tokenizers` library. I believe the results you're getting are the intended behavior.

For example, any generic sentence where someone forgets to put a space after the period would end up tokenized incorrectly otherwise:

`I love lamp.No I really love lamp.` would leave you with a token `lamp.No`, which is incorrect, eh?

**Comment by Xunzhuo** [comment]
tks~ it helps a lot ~
