### ISSUE TITLE
Can I save a word embedding from BERT and used again later for computational purpose(as BERT takes much more time). Just like in Glove. If yes then How? and is this good idea to do so?

### ISSUE THREAD

**Issue by shubhamk16** [huggingface/transformers#4716]
# ❓ Questions & Help

## Details

**A link to original question on Stack Overflow**:

**Comment by ritvikshrivastava** [comment]
As per my understanding, you can! 

If you read the BERT paper by Devlin et.al., you can see that two suggested ways to extract said word embeddings would be to concatenate the last four hidden layers (9 to 12), generating a 4*768=3072 sized embedding for each token. Alternatively you can also sum or average out the last 4 layers to generate vectors of size 768.

You can also instead prefer storing sentence embeddings, then the CLS token serves as averaged representation of the sentence embedding (not a very good representation though, unless the model was fine-tuned well on the data or the LM was pretrained on similar data, and even then the sentence embeddings through that CLS token could be substandard). Although, averaging out the second to last hidden layer (i.e. averaging out token embeddings for the sentence at the 11th hidden layer) seems to generate decent sentence embeddings (of size 768, the same as one token, since its averaged and not concatenated). 

Hope this helps!
