### ISSUE TITLE
Onnx converted model has its output shape modified when compared to original (finetuned) model

### ISSUE THREAD

**Issue by pommedeterresautee** [huggingface/transformers#4825]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): `mrm8488/distilroberta-base-finetuned-sentiment` from the hub

Language I am using the model on (English, Chinese ...): `English`

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [X] my own modified scripts: (give details below)

I use the `04-onnx-export.ipynb` Notebook and have only change the model name and the tokenizer:
![image](https://user-images.githubusercontent.com/1029874/83956354-6a799800-a85d-11ea-9b0b-b2febdd8e91a.png)

The issue appeared on all finetuned model I tried, being classification or multichoice questions.

The tasks I am working on is: 
* [ ] my own task or dataset: (give details below)
* [X] an official GLUE/SQUaD task: classification

## To reproduce

Import AutoTokenizer, AutoModelForSequenceClassification and change tokenizer and model name, the section we are interested into:

```python
# ...
!rm -rf onnx/
from transformers.convert_graph_to_onnx import convert

# Handles all the above steps for you
convert(framework="pt", model="mrm8488/distilroberta-base-finetuned-sentiment", output="onnx/bert-base-cased.onnx", opset=11)
# ...

from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("mrm8488/distilroberta-base-finetuned-sentiment")
cpu_model = create_model_for_provider("onnx/bert-base-cased.onnx", "CPUExecutionProvider")

# Inputs are provided through numpy array
model_inputs = tokenizer.encode_plus("My name is Bert", return_tensors="pt")
inputs_onnx = {k: v.cpu().detach().numpy() for k, v in model_inputs.items()}

# Run the model (None = get all the outputs)
sequence, pooled = cpu_model.run(None, inputs_onnx)

# Print information about outputs

print(f"Sequence output: {sequence.shape}, Pooled output: {pooled.shape}")

pytorch_model = AutoModelForSequenceClassification.from_pretrained("mrm8488/distilroberta-base-finetuned-sentiment")
a, = pytorch_model(**model_inputs)
print(f"finetune non onnx pytorch model output: {a.shape}")
# ...
```

## Expected behavior

I was expecting that the onnx output shape would be the same than the non converted model output shape, but that's not the case:
```text
Sequence output: (1, 6, 768), Pooled output: (1, 768)
finetune non onnx pytorch model output: torch.Size([1, 6])
```
It is like the last layer of the model related to the classification task is not taken in onnx.  
Does it make sense? @mfuntowicz 

## Environment info
Google Colab with a GPU

**Comment by manueltonneau** [comment]
Facing the same problem with a BERT model fine-tuned on sequence classification and would love to get an answer :)

**Comment by manueltonneau** [comment]
This seems to be related to [this issue](https://github.com/huggingface/transformers/issues/4788). 

As @hrsmanian points it, it seems that in[ convert_graph_to_onnx.py](https://github.com/huggingface/transformers/blob/master/src/transformers/convert_graph_to_onnx.py), the model is currently converted by default to a 'feature-extraction' version where the classification layer is discarded. Changing the pipeline type (line 108 of the py file) to 'ner' in @hrsmanian's case seems to have worked. 

In the case of binary classification, I tried changing the pipeline type to 'sentiment-analysis' (my model is a binary BertForSequenceClassification) but get a ValueError (ValueError: not enough values to unpack (expected 2, got 1)) when trying to run the session. I used simpletransformers (which is based on this repo) to do binary classification with BERT, followed the instructions for conversion and inference from the [blog post](https://medium.com/microsoftazure/accelerate-your-nlp-pipelines-using-hugging-face-transformers-and-onnx-runtime-2443578f4333). 

Let me know if you see what the problem is @mfuntowicz :)

**Comment by manueltonneau** [comment]
Actually, I managed to make it work.

The problem was that the session.run output shape changed from 2 to 1 and so writing:
`output, pooled = session.run(None, tokens)` was not working anymore. 

When only writing `output = session.run(None, tokens)`, it works and I get the classification scores.

![image](https://user-images.githubusercontent.com/29440170/84197042-879ea880-aaa1-11ea-878d-8e344c04d92c.png)

Hope that helps :)

**Comment by mfuntowicz** [comment]
@manueltonneau You're right, we're currently enforcing the `feature-extraction` because not all our pipelines are compatible with ONNX graph representation. 

I'll have a look asap to identify which pipelines are compatible and which are not, so what we can add the possibility to export other kind of pipeline through the script.

**Comment by pommedeterresautee** [comment]
Tks @manueltonneau , works for me too!
@mfuntowicz would it be possible to have a pipeline for multichoice (and a related onnx converter too)? Not sure why it doesn't exist yet btw as all models I have used support the task.

**Comment by mfuntowicz** [comment]
It might be possible for pipelines such as **token classification** and **sequence classification**. to be exportable out of the box. These pipelines generally just add a projection layer on top of the model followed by a argmax. All of these operators are natively supported by ONNX.

For more complex pipeline such as **qa** or **generation**, ONNX might not support all the operators used in the post-processing steps (i.e. _sampling_, _answer span extraction_) and thus would lead to the impossibility to export the model to ONNX.

**Comment by pommedeterresautee** [comment]
This is a very good news! 
So in theory a multichoice pipeline should work as it s just a projection like classification but with a different shape, am I right? Would it be possible for your team to support this task on the pipeline?

**Comment by pommedeterresautee** [comment]
I have another question, looking at the `convert` code the dumb input look like that (during onnx generation):

```python
    tokens = nlp.tokenizer.encode_plus("This is a sample output", return_tensors=framework)
```
My understanding is that onnx uses torch script and torch script can only guess a fix input length.

@mfuntowicz Does that mean that onnx model truncates all inputs to less than 10 tokens?
@manueltonneau On your model, does onnx predictions the same than pytorch ones? (for the same input)
My model is multichoice and it doesn't work (it compiles but the predictions are wrong). I don't know if it s because some input truncation or not

**Comment by mfuntowicz** [comment]
@pommedeterresautee You're right here about how PyTorch & ONNX interact together. ONNX leverage the tracing provided by PyTorch to construct the ONNX IR. 

However on the input, it should not truncate anything because `convert_graph_to_onnx.py` exports the inputs with the[ sequence axis being dynamic](https://github.com/huggingface/transformers/blob/master/src/transformers/convert_graph_to_onnx.py#L81)

```python
# Generate input names & axes
input_vars = list(tokens.keys())
input_dynamic_axes = {k: build_shape_dict(v, True, seq_len) for k, v in tokens.items()}
```

You can set a breakpoint on [this line](https://github.com/huggingface/transformers/blob/master/src/transformers/convert_graph_to_onnx.py#L97) and see the actual axes being dynamic (input and output). 

If you find any incoherent behaviour we can dig further to understand why dynamic axes are not correctly exported in your case 👍

**Comment by manueltonneau** [comment]
>@manueltonneau On your model, does onnx predictions the same than pytorch ones? (for the same input)
Sorry for the late reply @pommedeterresautee. I did three tests and the predictions are exactly the same for the first test, and almost exactly the same for the two other ones.

**Comment by siddhantwaghjale** [comment]
Hi @pommedeterresautee , @mfuntowicz , @manueltonneau 
I'm working on a Spam detection model using fine-tuned DistilBERT model from huggingface.
In order to improve the time-latency in production I'm exporting the finetuned model using the following reference:
[export transformers to onnx](https://colab.research.google.com/github/huggingface/transformers/blob/master/notebooks/04-onnx-export.ipynb)

And just replacing the models with my finetuned model's saved directory .
But while predicting ,the normal pytorch output and pytorch+onnx output size are not matching.
Here is a small snipet of the code for prediction:
![image](https://user-images.githubusercontent.com/33514203/106426405-8df7ef80-648b-11eb-90d1-a898d32d35c1.png)

And the results obtained are as follows:
Where the tensor results is for pytorch and makes sense for classification of "Not Spam/Spam"
While for onnx I get a big array
![image](https://user-images.githubusercontent.com/33514203/106426522-c3044200-648b-11eb-9e63-0fba686a5eb8.png)

I will be more than thankful if you can help me in any way and clear my doubt

**Comment by swapnil3597** [comment]
Now pipeline option can be provided via arguments to `convert_graph_to_onnx.py` using `--pipeline` argument:

Valid Options (taken from [this](https://github.com/huggingface/transformers/blob/master/src/transformers/pipelines/__init__.py#L287) script)

```
:obj:`"feature-extraction"`: will return a :class:`~transformers.FeatureExtractionPipeline`.
- :obj:`"text-classification"`: will return a :class:`~transformers.TextClassificationPipeline`.
- :obj:`"sentiment-analysis"`: (alias of :obj:`"text-classification") will return a
  :class:`~transformers.TextClassificationPipeline`.
- :obj:`"token-classification"`: will return a :class:`~transformers.TokenClassificationPipeline`.
- :obj:`"ner"` (alias of :obj:`"token-classification"): will return a
  :class:`~transformers.TokenClassificationPipeline`.
- :obj:`"question-answering"`: will return a :class:`~transformers.QuestionAnsweringPipeline`.
- :obj:`"fill-mask"`: will return a :class:`~transformers.FillMaskPipeline`.
- :obj:`"summarization"`: will return a :class:`~transformers.SummarizationPipeline`.
- :obj:`"translation_xx_to_yy"`: will return a :class:`~transformers.TranslationPipeline`.
- :obj:`"text2text-generation"`: will return a :class:`~transformers.Text2TextGenerationPipeline`.
- :obj:`"text-generation"`: will return a :class:`~transformers.TextGenerationPipeline`.
- :obj:`"zero-shot-classification:`: will return a :class:`~transformers.ZeroShotClassificationPipeline`.
- :obj:`"conversational"`: will return a :class:`~transformers.ConversationalPipeline`.
```

**Comment by LeeJiangWei** [comment]
Hi, is there any support for sequence classfication on sentence pairs?

**Comment by pommedeterresautee** [comment]
sentence pairs are managed by the tokenizer, at the end it's just a sequence of tokens... so classic sequence classification pipeline works out of the box

**Comment by debjyoti003** [comment]
I am facing issue while solving for multi-class classification problem.
