### ISSUE TITLE
sentencepiece==0.1.92 causing segmentation fault

### ISSUE THREAD

**Issue by boy2000-007man** [huggingface/transformers#4857]
# 🐛 Bug

## Information

`transformers==2.9.1`
`torch==1.4.0`

Starting from today,
I notice newly released `sentencepiece==0.1.92` causing segmentation fault while calling torch functions.
Downgrade to `sentencepiece==0.1.91` solve it.

**Comment by WencongXiao** [comment]
@boy2000-007man  Hi, folk. Just curious about how do you find this bug? It costs me almost the whole day... Anyway, thank you so much!

**Comment by liesun1994** [comment]
OMG!!! Awesome Advice!!!!

**Comment by hahahawu** [comment]
I spent a whole night to address the dependencies problems and almost lost my mind. This answer saved my life. Appreciate!

**Comment by iamshwin** [comment]
Thanks for this! Also curious how you worked this out - I've spent a whole day trying to figure this out!

**Comment by libing125** [comment]
Thanks so much you saved my day.

**Comment by aychang95** [comment]
I was dreading the thought of having to dive into this issue with faulthandler and meticulously cross referencing dependencies with a working version....but this post just saved my night.  Thanks @boy2000-007man 

This seems like a new pytorch v1.4.0 incompatibility issue with the latest huggingface releases.  I'm assuming this may ahve been missed due to the focus has being on v1.5.0, but it seems like many people cannot make the jump to cuda 10.2/pytorch 1.5.0 currently, so this seems like a pretty big headache that should be addressed.

**Comment by soobidou** [comment]
Seriously, wasted hours hunthing down this bug.. even though I version-pin every dependencies in my jupyter monster. 
To boy2000-007man: thanks !
To dev: version 0.2.5.1 broke overnight because of that sub dependency. is it set to latest version so at the mercy of "sentencepiece" developper?

**Comment by LysandreJik** [comment]
Closing this as solved by #5418

**Comment by ShaneTian** [comment]
You are excellent!

**Comment by zhjunqin** [comment]
same problem when use  sentencepiece==0.1.94

**Comment by jayparks** [comment]
Having the same problem with sentencepiece==0.1.94

**Comment by thomwolf** [comment]
Cf #8199 we will remove the hard dependency on sentencepiece (replaced by the `tokenizers` library) in a coming release, probably end of next week.

**Comment by ShengdingHu** [comment]
Thank you a lot! You saved my day!
