### ISSUE TITLE
BERT Huggingface trainer api: ValueError: expected sequence of length 128 at dim 1 (got 314)

### ISSUE THREAD

**Issue by quest4next** [huggingface/transformers#5460]
# ❓ Questions & Help

## Details

I'm using new trainer api in HuggingFace Transformers to train on a GLUE task (QQP). This error shows up during training.

This is the example I'm using https://colab.research.google.com/github/huggingface/blog/blob/master/notebooks/trainer/01_text_classification.ipynb

Only change I made is the task. In the notebook GLUE task is MNLI which I changed to QQP. While original MNLI task runs without errors, QQP task fails.

ValueError: expected sequence of length 128 at dim 1 (got 314)

Please check my Stackoverflow question for more details
**https://stackoverflow.com/questions/62675482/bert-huggingface-trainer-api-valueerror-expected-sequence-of-length-128-at-dim**:

**Comment by LysandreJik** [comment]
I can reproduce! Thank you for opening an issue, I'm looking into it now.

**Comment by neel04** [comment]
Same error (StackOverflow--> https://stackoverflow.com/questions/67004233/typeerror-zeros-like-argument-input-when-fine-tuning-on-mlm) what was the fix in the end @LysandreJik ?

**Comment by msamogh** [comment]
@LysandreJik Is there any way to fix this (for what I presume is a model pretrained on the old HuggingFace version)?

**Comment by LysandreJik** [comment]
Sorry just seeing this now - @neel04 are you still facing the issue? @msamogh can you open a new issue and fill in the issue template (with full error, environment, code run)? Thanks

**Comment by neel04** [comment]
I don't really remember what I was trying to do :sweat_smile: Sorry, can't help you anymore. I think the problem was some changes in the API, while the example notebooks weren't updated at that time - so the `max_length` argument (which took `int`) didn't work leading to that error. Now, its changed to a `str` whic represents padding strategy - and since it works now with my current problem, I personally don't think the issue remains anymore :hugs:
