### ISSUE TITLE
TypeError: 'BertTokenizer' object is not callable

### ISSUE THREAD

**Issue by axhiao** [huggingface/transformers#5580]
```
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-cased")
sequence_a = "HuggingFace is based in NYC"
sequence_b = "Where is HuggingFace based?"
encoded_dict = tokenizer(sequence_a, sequence_b)
```
This will produce error 'BertTokenizer' object is not callable.  Maybe I should call `tokenizer.tokenize()`? But I think the [doc](https://huggingface.co/transformers/glossary.html#token-type-ids) should also be updated!

**Comment by LysandreJik** [comment]
Hello! It seems you're running on an older `transformers` version. The `__call__` was implemented only in version v3.0.0+. Do you mind pasting your environment information here?

You should have a dropdown in the documentation with the different versions, so that you can select the documentation that works for your version.

**Comment by axhiao** [comment]
yes, you are right. I got the old version because I had the [mmf ](https://github.com/facebookresearch/mmf) framework depending on transformers==2.0.3. So when I run pip install transformers, it just did nothing due to the existence of the old version. Thank you!

**Comment by yang-peilin** [comment]
Thank you a lot!

**Comment by gyandevgupta** [comment]
So we have to update the transformer to the latest version, and it would work? Is that the case
