### ISSUE TITLE
Unable to finetune BERT on own dataset

### ISSUE THREAD

**Issue by noabenefraim** [huggingface/transformers#5721]
# ❓ Questions & Help

## Details
Hello, I am trying to use my own data to finetune transformers for summarization tasks. I have followed the instructions on the README.md by generating a text file with each article to be summarized on its own line. The text file is located in ...\workspace\hug

Below is the command that I ran and it's resulting error. I couldn't find further instructions on the README or in the stackoverflow/current or closed issues. Can you please provide more guidance with examples on how to train on your data set. I would greatly appreciate this. @sshleifer 

Command ran + error:
![image](https://user-images.githubusercontent.com/13383820/87342840-c7bdd480-c500-11ea-8cc7-10751701b519.png)

Finetune.sh
![image](https://user-images.githubusercontent.com/13383820/87343018-12d7e780-c501-11ea-834d-48ed5f4c3b02.png)

Once again, I would really appreciate your help!

**Comment by asears** [comment]
Seems you are using Powershell.  Since this is a bash shell file, you will need to run it outside of Powershell in bash shell.

Here's an example using Google Colab

https://colab.research.google.com/github/interactive-fiction-class/interactive-fiction-class.github.io/blob/master/homeworks/language-model/hw4_transformer.ipynb

Some additional examples
https://github.com/huggingface/transformers/blob/223084e42b57cd0d8e78de38e15a42d5d6b04391/notebooks/README.md
