### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by devJWSong** [huggingface/transformers#5850]
Hi, I tried to install transformers library via `pip install transformers` and I got tokenizer install error.

The error logs are as follows.
```
ERROR: Could not find a version that satisfies the requirement tokenizers==0.8.1.rc1 (from transformers) (from versions: 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.5.2, 0.6.0, 0.7.0, 0.8.0)
ERROR: No matching distribution found for tokenizers==0.8.1.rc1 (from transformers)
```

I googled about it but I couldn't find the way to solve it.
Is there I can do to handle this issue?

Thank you.

**Comment by jstremme** [comment]
@devJWSong, how did you solve this?

**Comment by devJWSong** [comment]
Oh, actually I didn't solve it.
I just installed downgraded version which is 2.11.0. and it worked.
I still don't know the reason but I think it is the problem from my virtual environment setting since when I tried to install the recent version in the different environment, it worked...

**Comment by tteon** [comment]
its error occurs to me too.... could  you give me another solution about that problems? ...

**Comment by ggaemo** [comment]
Any updates on this problem?

**Comment by mnmjh1215** [comment]
Try changing index-url and trusted-host in pip config.
I had same issue with the environment with index-url='http://ftp.daumkakao.com/pypi/simple' and trusted-host='ftp.daumkakao.com', but everything worked well with the environment without such config.

**Comment by devJWSong** [comment]
Thank you! It worked. :)

**Comment by SolsticeProjekt** [comment]
Excuse me for re-opening this. I've used the suggestion by [mnmjh1215](https://github.com/mnmjh1215) and it worked, but for some reason the commandline then spat out ...

`MikeMikeMikeMike, tteon, devjwsong, abigbigsmile, Lagousis, dcahn12, pwr2000, Sara-Rajaee, and khushi-dave reacted with th`

... and I'm wondering if that might be an issue. I'm posting this here, because I got the version-error as well and needed a way to fix it.

![image](https://user-images.githubusercontent.com/23191574/222986151-1d701425-70e5-4737-8cfa-36a56237fec3.png)
