### ISSUE TITLE
Copyright date and owner not filled out in LICENSE file

### ISSUE THREAD

**Issue by Meadosc** [huggingface/transformers#6140]
In transformers/LICENSE the copyright date and owner is not filled out.

https://github.com/huggingface/transformers/blob/master/LICENSE#L179-L190

**Comment by darigovresearch** [comment]
Thanks @Meadosc for raising this, we're not sure if this is a requirement of the license in order to add the copyright date and owner.

We only saw this issue now but think it would be good to reopen the issue (as it was auto-closed by the bot) to be addressed by the repository maintainers if possible!
