### ISSUE TITLE
[t5] Missing requirements in examples/seq2seq

### ISSUE THREAD

**Issue by jeff-da** [huggingface/transformers#6892]
Hi! This is a very small fix. But it seems like some requirements for examples/seq2seq are missing? Namely, rouge-score, gitpython, sacrebleu. Is this intentional (conflicts with other example requirements)? Of course, would be happy to open a PR

## Environment info

- `transformers` version: 8b884dadc6bd70600c98bb35b522beb0005e3f28
- Platform: Linux
- Python version: 3.8
- PyTorch version (GPU?): GPU, '1.6.0+cu101'
- Tensorflow version (GPU?): n/a
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

 Summarization: @sshleifer

## Information

Model I am using (Bert, XLNet ...): T5

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name) CNN Summary
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Create new `conda` env
2. Install requirements.txt in /examples
3. Try running finetune_t5.sh

## Expected behavior

Finetune should run correctly.

**Comment by sgugger** [comment]
Those requirements are all in [here](https://github.com/huggingface/transformers/blob/master/examples/requirements.txt). Are you sure you ran `pip install -r ./examples/requirements.txt` as mentioned in the [README of all examples](https://github.com/huggingface/transformers/tree/master/examples#important-note)?

They are not, and won't be requirements of the main library since they are only used for some specific tasks.

**Comment by jeff-da** [comment]
Huh, probably just a local issue then. Thanks!
