### ISSUE TITLE
OSError: Can't load weights for 'nlptown/bert-base-multilingual-uncased-sentiment'. 

### ISSUE THREAD

**Issue by sansanai** [huggingface/transformers#7138]
## Environment info
- `transformers` version: 3.1.0
- Platform: Linux-5.4.0-47-generic-x86_64-with-debian-buster-sid
- Python version: 3.7.9
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): 2.3.0 (True)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in

Question:

After installing transformers, I followed the Quick tour document.

I typed code as follows:

from transformers import pipeline
classifier = pipeline('sentiment-analysis', model="nlptown/bert-base-multilingual-uncased-sentiment")

After running it, I got this error 

2020-09-15 16:41:21.434156: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/home/a/.conda/envs/tf23hf/lib/python3.7/site-packages/transformers/modeling_tf_utils.py", line 580, in from_pretrained
    raise EnvironmentError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hf_pipetest.py", line 2, in <module>
    classifier = pipeline('sentiment-analysis', model='nlptown/bert-base-multilingual-uncased-sentiment')
  File "/home/a/.conda/envs/tf23hf/lib/python3.7/site-packages/transformers/pipelines.py", line 2629, in pipeline
    model = model_class.from_pretrained(model, config=config, **model_kwargs)
  File "/home/a/.conda/envs/tf23hf/lib/python3.7/site-packages/transformers/modeling_tf_auto.py", line 1515, in from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "/home/a/.conda/envs/tf23hf/lib/python3.7/site-packages/transformers/modeling_tf_utils.py", line 587, in from_pretrained
    raise EnvironmentError(msg)
OSError: Can't load weights for 'nlptown/bert-base-multilingual-uncased-sentiment'. Make sure that:

- 'nlptown/bert-base-multilingual-uncased-sentiment' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'nlptown/bert-base-multilingual-uncased-sentiment' is the correct path to a directory containing a file named one of tf_model.h5, pytorch_model.bin.

Please, let me know how to solve this problem.. 
Thanks in advance

**Comment by LysandreJik** [comment]
Hello! This problem is because the owner of the `nlptown/bert-base-multilingual-uncased-sentiment` model has not uploaded a TensorFlow version. If you're using pipelines, you would only be able to use this model if you have PyTorch installed on your machine.

cc @mfuntowicz for pipelines' next version, it would be great to include the `from_tf` and `from_pt` options as well so that these models may be loaded directly.

**Comment by aychang95** [comment]
Thanks for the info @LysandreJik!

However it seems like the default model pull with the pytorch autoclasses are failing as well.
```
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("nlptown/bert-base-multilingual-uncased-sentiment")
			
model = AutoModelForSequenceClassification.from_pretrained("nlptown/bert-base-multilingual-uncased-sentiment")
```

<details>
  <summary>Full Error Log (I'm assuming the error is from the issues stated above)</summary>
  
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-25-cfac34095092> in <module>
      1 from transformers import AutoTokenizer, AutoModelForSequenceClassification
      2 
----> 3 tokenizer = AutoTokenizer.from_pretrained("nlptown/bert-base-multilingual-uncased-sentiment")
      4 model = AutoModelForSequenceClassification.from_pretrained("nlptown/bert-base-multilingual-uncased-sentiment")

~/Documents/github/adaptnlp/venv-adaptnlp/lib/python3.6/site-packages/transformers/tokenization_auto.py in from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
    218                     return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
    219                 else:
--> 220                     return tokenizer_class_py.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
    221 
    222         raise ValueError(

~/Documents/github/adaptnlp/venv-adaptnlp/lib/python3.6/site-packages/transformers/tokenization_utils_base.py in from_pretrained(cls, *inputs, **kwargs)
   1423 
   1424         """
-> 1425         return cls._from_pretrained(*inputs, **kwargs)
   1426 
   1427     @classmethod

~/Documents/github/adaptnlp/venv-adaptnlp/lib/python3.6/site-packages/transformers/tokenization_utils_base.py in _from_pretrained(cls, pretrained_model_name_or_path, *init_inputs, **kwargs)
   1544         if tokenizer_config_file is not None:
   1545             with open(tokenizer_config_file, encoding="utf-8") as tokenizer_config_handle:
-> 1546                 init_kwargs = json.load(tokenizer_config_handle)
   1547             saved_init_inputs = init_kwargs.pop("init_inputs", ())
   1548             if not init_inputs:

/usr/lib/python3.6/json/__init__.py in load(fp, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    297         cls=cls, object_hook=object_hook,
    298         parse_float=parse_float, parse_int=parse_int,
--> 299         parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
    300 
    301 

/usr/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

/usr/lib/python3.6/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

/usr/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)


</details>


Since there already are TF-specific auto classes, should the default auto classes should still be able pull pytorch models even if there is no TF implementation?
I haven't checked other models in the repo that only have pytorch models, but would it be safe to assume this is the case for all models in the repo that do not have models uploaded for both deep learning frameworks?
