### ISSUE TITLE
Custom preprocessing of text

### ISSUE THREAD

**Issue by datistiquo** [huggingface/transformers#7389]
I feel like this a silly question. But I just thought in using BERT, wait, before working with fasttext for example I had to do preprocessing like word stemming/lemmatization and stopwords. How is the advise for using BERT models?

Does it makes problems if I do stemming or lemmatization before feeding to BERT tokenizer?

questions over questions...

**Comment by coreyfournier** [comment]
It shouldn't be necessary as it performs byte pair encoding (BPE) when a word isn't in it's vocabulary. For example "Gallbladder palpaple". Palpaple isn't in my vocabulary so it breaks the word into many partial words that are in the vocabulary as: ['p', '##al', '##pa', '##ple']. This would match variations that would otherwise need to be stemmed or converted to it's lemma.

This will however be an issue if you are using the model to perform cosine similarly. The results are terrible when you have many words out of vocabulary.
