### ISSUE TITLE
The links to examples on the website don't work

### ISSUE THREAD

**Issue by ekdnam** [huggingface/transformers#7534]
## Environment info

     
I am looking at the examples part of the docs: https://huggingface.co/transformers/v2.2.0/examples.html

The references to all the scripts on the web page don't work. 

for ex: [link to script](https://github.com/huggingface/transformers/blob/master/examples/run_ner.py) referenced [here](https://huggingface.co/transformers/v2.2.0/examples.html#named-entity-recognition)

Thanks in advance!

Here, 
- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by LysandreJik** [comment]
Hello! Indeed, you're right. This is because you're looking at an older version of the docs, and the files have since moved around. When clicking on a link, you should replace `master` with `v2.2.0` to get the correct link. For example:

```
https://github.com/huggingface/transformers/blob/master/examples/run_lm_finetuning.py
```

should become:

```
https://github.com/huggingface/transformers/blob/v2.2.0/examples/run_lm_finetuning.py
```

Sorry for the inconvenience.

I don't think there's much we can do about older versions, but we could freeze the current and future scripts to tag versions cc @sgugger.
