### ISSUE TITLE
Unable to pass encoder_outputs to generate calls

### ISSUE THREAD

**Issue by gabisurita** [huggingface/transformers#7626]
## Environment info

     
- `transformers` version: Github Main branch

### Who can help
 TextGeneration: @TevenLeScao 
 

## Information

Model I am using (Bert, XLNet ...): T5

I'm unable to pass preconputed encoder_outputs to the `.generate()` method.

I've tried defining:

```python
model_kwargs = {"encoder_outputs": encoder_outputs}
output = model.generate(model_kwargs)
```
But I've noticed some validation errors for `input_ids`. Even if I replace input_ids with dummy values, I've noticed the model_kwargs is always replaced here:

https://github.com/huggingface/transformers/blob/master/src/transformers/generation_utils.py#L448

I think it can be fixed (without optimization) by just replacing:

```python
model_kwargs["encoder_outputs"] = encoder_outputs
```

with:

```python
model_kwargs.setdefault("encoder_outputs", encoder_outputs)
```

If you agree I can try to open a PR to fix this.

Best,

**Comment by gabisurita** [comment]
Hi @patrickvonplaten,

I've noticed that your PR refactoring generate was merged. It seems a big improvement. Still, `input_ids` is still required or overridden by an empty tensor. It's still not clear to me how can I use the new API with `encoder_outputs` or `imput_embeds`.

**Comment by patrickvonplaten** [comment]
Hey @gabisurita - if you look at the tests, you can now directly use `beam_search` instead of generate for your use case I think :-). Here the tests: https://github.com/huggingface/transformers/blob/a7d73cfdd497d7bf6c9336452decacf540c46e20/tests/test_generation_utils.py#L295 

From the tests, it should be quite easy to understand how to use `beam_search` directly I think :-) 

Let me know if that helps!

**Comment by qiyue-liang** [comment]
I got a similar error "Make sure that `model_kwargs` include `encoder_outputs` of type `ModelOutput`." This worked for me:

downgrade transformers to 3.0.2
