### ISSUE TITLE
Fine Tuning SciBERT NLI model

### ISSUE THREAD

**Issue by duttaprat** [huggingface/transformers#7708]
# ❓ Questions & Help

## Details

**A link to original question on the forum/Stack Overflow**:

Hi,
I am a novice in the domain of fine-tuning any Transformer models using my own dataset. I want to fine-tune the SciBERT NLI model(https://huggingface.co/gsarti/scibert-nli) using my dataset. The dataset formation is
S1 [SEP] S2 [SEP] Inference

I am not sure how to fine-tune my dataset on the SciBERT NLI model(https://huggingface.co/gsarti/scibert-nli).

I am sorry for asking a very simple question. But any suggestion or link helps me. Thanks in advance.

**Comment by NielsRogge** [comment]
Take a look at the official tutorial on fine-tuning a model on your own dataset here: https://huggingface.co/transformers/custom_datasets.html

What's your dataset about? Is it text classification, question answering?

BTW, please post any questions which are not bugs/new features you would like to see added on the [forum](https://discuss.huggingface.co/) rather than here.

**Comment by duttaprat** [comment]
Thanks @NielsRogge for the reply. 

My dataset contains two clinical sentences (S1, S2) and its corresponding relation ('Entailment'/'Contradiction'/'Neutral'). So it basically contains three columns.

**Comment by NielsRogge** [comment]
Ok so that's sentence pair classification. There's an example notebook on that [here](https://github.com/NadirEM/nlp-notebooks/blob/master/Fine_tune_ALBERT_sentence_pair_classification.ipynb).

**Comment by duttaprat** [comment]
Oh that's really helpful. Thank you again @NielsRogge .
