### ISSUE TITLE
Unicode issue with tokenizer.decode()

### ISSUE THREAD

**Issue by kelvin-jiang** [huggingface/transformers#7751]
## Environment info

- `transformers` version: 3.3.1
- Platform: Ubuntu 18.04.1 LTS
- Python version: 3.6.9
- PyTorch version (GPU?): 1.5.0 (No)
- Tensorflow version (GPU?): 1.14.0 (No)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help

Since the issue regards tokenizers, tagging @mfuntowicz.

## Information

Model I am using (Bert, XLNet ...): T5

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

1. Run this (I'm running in a Python shell, but it's reproducible in a script)

```python
>>> from transformers import T5Tokenizer
>>> tokenizer = T5Tokenizer.from_pretrained('t5-3b')
>>> sent = 'Luis Fonsi. Luis Alfonso Rodríguez López-Cepero, more commonly known by his stage name Luis Fonsi, (born April 15, 1978) is a Puerto Rican singer, songwriter and actor.'
>>> tokenizer.decode(tokenizer.encode(sent))
'Luis Fonsi. Luis Alfonso Rodr ⁇ guez López-Cepero, more commonly known by his stage name Luis Fonsi, (born April 15, 1978) is a Puerto Rican singer, songwriter and actor.'
```

The "í" character turns into "⁇", while other unicode characters like "ó" come out fine.

## Expected behavior

If I use a different set of functions that should end up with the same result, I get the expected:

```python
>>> tokenizer.convert_tokens_to_string(tokenizer.tokenize(sent))
'Luis Fonsi. Luis Alfonso Rodríguez López-Cepero, more commonly known by his stage name Luis Fonsi, (born April 15, 1978) is a Puerto Rican singer, songwriter and actor.'
```

**Comment by LysandreJik** [comment]
This is not a bug, but a lack of vocabulary diversity in T5's tokenizer. T5's tokenizer was not trained on a corpus containing that character, and therefore cannot encode it: it encodes it to an unknown token which is represented by `⁇`. 

You can try using other characters that the tokenizer doesn't know how to process, for example emojis:

```py
from transformers import T5Tokenizer
tokenizer = T5Tokenizer.from_pretrained('t5-3b')
sent = 'Luis 😃 Fonsi. Luis Alfonso Rodríguez López-Cepero, more commonly known by his stage name Luis Fonsi, (born April 15, 1978) is a Puerto Rican singer, songwriter and actor.'
print(tokenizer.decode(tokenizer.encode(sent)))

# Luis  ⁇  Fonsi. Luis Alfonso Rodr ⁇ guez López-Cepero, more commonly known by his stage name Luis Fonsi, (born April 15, 1978) is a Puerto Rican singer, songwriter and actor.
```

You can use the `tokenize` + `convert_tokens_to_string` because the sequence has never been converted to IDs, only to tokens:
```py
print(tokenizer.tokenize(sent))

# ['▁Lu', 'is', '▁', '😃', '▁F', 'on', 's', 'i', '.', '▁Lu', 'is', '▁Al', 'f', 'on', 's', 'o', '▁Rod', 'r', 'í', 'gu', 'ez', '▁L', 'ó', 'p', 'ez', '-', 'C', 'e', 'per', 'o', ',', '▁more', '▁commonly', '▁known', '▁by', '▁his', '▁stage', '▁name', '▁Lu', 'is', '▁F', 'on', 's', 'i', ',', '▁(', 'born', '▁April', '▁15,', '▁1978', ')', '▁is', '▁', 'a', '▁Puerto', '▁Rica', 'n', '▁singer', ',', '▁', 'songwriter', '▁and', '▁actor', '.']
```

If your dataset contains a lot of such characters, you should think about [adding these to the tokenizer's vocabulary.](https://huggingface.co/transformers/internal/tokenization_utils.html#transformers.tokenization_utils_base.SpecialTokensMixin.add_tokens)
