### ISSUE TITLE
Loading a pytorch quantized model

### ISSUE THREAD

**Issue by amanpreet692** [huggingface/transformers#7923]
Hi, I quantized a pre-trained model via **torch.quantization.quantize_dynamic** and saved it using **save_pretrained**.
based on https://colab.research.google.com/github/pytorch/tutorials/blob/gh-pages/_downloads/dynamic_quantization_bert_tutorial.ipynb#scrollTo=foe-dVxHIgOC . 
On reloading it using **from_pretrained** again the model blows up to its original size and the resultant predictions are garbage as well.
Is there a way to properly save the quantized weights and reload them?
Opening an issue because I couldn't find a resolution for the same.
@mfuntowicz @VictorSanh @patrickvonplaten

**Comment by VictorSanh** [comment]
Hello @amanpreet692 
Are you making sure you are reloading the saved (quantized) weights into a quantized model?
A dense checkpoint and its quantized counterpart have two different state dicts and I suspect you are re-initializing random matrices because when loading into from_pretrained it doesn't find the right keys in the state dict.
