### ISSUE TITLE
T5 with allowing model changes 

### ISSUE THREAD

**Issue by rabeehk** [huggingface/transformers#7966]
Hi
I would like to be able to change the model of T5, in addition to training on multiple tasks, I think currently the script can work for summarization only. Do you know possible other scripts allowing training on multiple tasks? 
One more question that in T5 in tensorflow repo, they have a small example for using your repo, does it work for large-scale? Is training on TPU working? could it allow model changes so one can change the model architecture? 
thanks a lot

**Comment by patrickvonplaten** [comment]
Hey @rabeehk - for more specific cases we recommend that you fork master and tweak the model however you would like to so that it fits your purpose. 
I didn't understand 100% what kind of script you are looking for, but here you can browse some of the T5 scripts, we have collected: https://github.com/huggingface/transformers/tree/master/notebooks#-transformers-notebooks

**Comment by rabeehk** [comment]
Hi
thanks for getting back to me. I am looking for a script showing to train
T5 with multiple tasks. this is when they create a T5 registery mixture
dataset in their original code and train one model on a mixture of several
dataset.
Do you know if huggingface version works fine for handling multiple
datasets? and do you know how performance is different from JAX
implementation? is this more or less the same? can one train the base T5
with a mixture of datasets with huggingface code?

thank you very much.
Best
Rabeeh
