### ISSUE TITLE
run_language_modeling crashes with import cannot import name 'DataCollatorForWholeWordMask' from 'transformers'

### ISSUE THREAD

**Issue by spacemanidol** [huggingface/transformers#8103]
## Environment info

     
- `transformers` version: 3.4.0
- Platform: linux
- Python version: 3.8
- PyTorch version (GPU?): 1.5
- Tensorflow version (GPU?):
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: No

## Information
I am trying to run the example for [language modeling](https://github.com/huggingface/transformers/tree/master/examples/language-modeling) but can't get it to start. Import fails
Traceback (most recent call last):
  File "run_language_modeling.py", line 32, in <module>
    from transformers import (
ImportError: cannot import name 'DataCollatorForWholeWordMask' from 'transformers' (/home/spacemanidol/miniconda3/envs/prunetransformer/lib/python3.8/site-packages/transformers/__init__.py)
Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ X] the official example scripts: (give details below)
running the language modeling example script

The tasks I am working on is:
* [ X] an official GLUE/SQUaD task: (give the name)
Language modeling
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Create conda enviorment. install transformers from the source. 
2. Run language modeling example script

## Expected behavior
Example runs.

**Comment by sgugger** [comment]
As explained in the README of the examples, you need an [installation from source](https://huggingface.co/transformers/installation.html#installing-from-source) to run the examples, which you don't have, otherwise you would have this object.

Alternatively, you can run the examples associated to your current version by using the files on the [last release tag](https://github.com/huggingface/transformers/releases/tag/v3.4.0).
