### ISSUE TITLE
Configuration initialized from checkpoint does not keep the checkpoint identifier in its attributes

### ISSUE THREAD

**Issue by LysandreJik** [huggingface/transformers#8187]
Since version v3.4.0, initializing a model using the `from_pretrained` method adds a `name_or_path` attribute to the configuration, referencing the checkpoint used for initialization:

```py
from transformers import BertModel

model = BertModel.from_pretrained(model_name)
print(model.config.name_or_path)
# model_name
```

However, initializing the configuration on its own with the `from_pretrained` method does not yield the same attribute:

```py
from transformers import BertConfig

config = BertConfig.from_pretrained(model_name)
# config has no `name_or_path` attribute
```

This means that the configuration object initialized is not the same in both cases, whereas it probably should be.

**Comment by thomwolf** [comment]
Good point.

Maybe what we could do is:
- initializing the configuration from a checkpoint initialize the `name_or_path` attribute as you mention
- using the configuration in a *model* `from_pretrained` override the `name_or_path` attribute with the one of the model so that it's in priority linked to the weights path.

Another option would be to have two attributes in the configuration:
- `configuration_name_or_path`
- `weights_name_or_path`
respectively populated by the config `from_pretrained` and the model `from_pretrained`. Maybe with a property linking to one in priority.
but I'm wondering if it's worth so many attributes... 🤔

**Comment by LysandreJik** [comment]
I would go for the first version you proposed: having `name_or_path` for the configuration initialized if used alongside `from_pretrained`, which gets overridden by the model `from_pretrained`.
