### ISSUE TITLE
Allow the user to input positional embeddings

### ISSUE THREAD

**Issue by anicolson** [huggingface/transformers#8555]
# 🚀 Feature request

Hi, 

I think that allowing the user to input positional embeddings in the same way that `inputs_embeds` can be fed directly to the Transformer would be greatly appreciated. (If this is already possible, please let me know :) ).

## Motivation

This is important for multimodal approaches, such as **VisualBERT** (https://arxiv.org/pdf/1908.03557.pdf), where each modality requires a separate positional embedding. The user could then use a `torch.nn.Embedding` per modality and concatenate the positional embeddings and feed this to the Transformer along with the concatenated input embeddings of the modalities.

This would also resolve other related issues:

https://github.com/huggingface/transformers/issues/5095
https://github.com/huggingface/transformers/issues/3395

## Your contribution

I can help in any form.

**Comment by patrickvonplaten** [comment]
Hey @anicolson,

I'm really not sure whether such a functionality is general enough to be added to the lib. It would also be very different from our current design of the library in that we would allow `torch.nn.Embedding` types as input, so I'd rather not add it. @LysandreJik what do you think?

**Comment by LysandreJik** [comment]
I think this is specifically where tweaking the library so that it supports your use-case is the way to go. It should be easy enough to modify the files directly in order to do this, but it would add unnecessary complexity to several model files.

Let's keep this issue open, and if other users are interested in this, we'll have a deeper look.
