### ISSUE TITLE
[Improvements] Enable `git push` without requiring login when uploading model

### ISSUE THREAD

**Issue by xhlulu** [huggingface/transformers#8574]
# 🚀 Feature request

Is there a way to allow `git push` a new model version without requiring login? 

`transformers-cli` will auto generate a key for the user. Is there a way to leverage this key?

## Motivation

GitHub allows you to push in VSCode without explicitly login in each time.

**Comment by julien-c** [comment]
Yes. Two ways:

- you can add your credentials when cloning, e.g. `git clone https://username:password@huggingface.co/user/model_id` (you can also use your token instead of your password if you know it).
- but the cleaner way is to have a credential store set-up in git (https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage) which means git will only ask you once. GitHub's doc is good as well (and not specific to GitHub): https://docs.github.com/en/free-pro-team@latest/github/using-git/caching-your-github-credentials-in-git

Let me know if this helps

**Comment by xhlulu** [comment]
Thanks! I'll try this out and reopen this issue if any problem arises!

**Comment by davidgilbertson** [comment]
Is there any documentation for "How to set the credential helper for Hugging Face URLs without changing the helper used for all other repos?"

**Comment by julien-c** [comment]
you can set the helper for a specific repo clone, but I'm not sure if you can set the helper system-wide for specific hosts
