### ISSUE TITLE
TFTrainer & Eager mode

### ISSUE THREAD

**Issue by JulesGM** [huggingface/transformers#8603]
Is eager mode really not supported with TFTrainer? It's telling me that it is using `tf.gradients`, which is not supported with eager mode.
If that's true, then I maybe it could be displayed a lot more prominently in your documentation ... I wasted so much time implementing custom functions, 🤦‍♂️
@sgugger

**Comment by sgugger** [comment]
cc @jplu for TFTrainer.

**Comment by jplu** [comment]
Hello @JulesGM!

Yes, the TF Trainer don't support eager execution, partially because of the usage of `tf.gradients` that we use because sometime when loading a model for a specific task, not all the layers are used and bring some None values when computing the gradients. `tf.gradients` allows to ignore these None values.

I'm really sorry that it is not enough detailed in the documentation, we are currently working on an improved version of the TF Trainer that you can find [here](https://github.com/huggingface/transformers/pull/8264). And it should be much easier anc convenient to use. Sorry once again for the inconvenience you have encountered with the TFTrainer until now.
