### ISSUE TITLE
WNLI benchmark results clarification

### ISSUE THREAD

**Issue by sumanthd17** [huggingface/transformers#8652]
The BERT paper mentions that the accuracy for WNLI is 62.3% [BERT Repository](https://github.com/google-research/bert) but the model card on HuggingFace reports the WNLI accuracy as  45.07%. Is there any particular for the big gap between the 2 models?

**Comment by timpal0l** [comment]
Wondering the same! Is it a typo? Since they report the exact same number for tiny, mini, small & medium. However, one would not expect that to be higher than [bert-base-cased that recieved 45.07%](https://github.com/huggingface/transformers/tree/master/examples/text-classification#run-pytorch-version).
