### ISSUE TITLE
Model can't be downloaded

### ISSUE THREAD

**Issue by moniquebm** [huggingface/transformers#8735]
## Environment info

     
- `transformers` version: 3.1.0
- Platform: Windows-10-10.0.19041-SP0
- Python version: 3.8.5
- PyTorch version (GPU?): 1.6.0 (True)
- Tensorflow version (GPU?): not installed (NA)

### Who can help
@julien-c 
 
## To reproduce

I've recently shared a finetunned model - monilouise/ner_pt_br - and despite its model card is already available at https://github.com/huggingface/transformers/tree/master/model_cards, the following error occurs when I try to download it:

OSError: Can't load config for 'monilouise/ner_pt_br'. Make sure that:

- 'monilouise/ner_pt_br' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'monilouise/ner_pt_br' is the correct path to a directory containing a config.json file

BUT the model has config.json available at https://huggingface.co/monilouise/ner_pt_br/tree/main.

I used the following code to download the model:

```python
from transformers import BertForTokenClassification
model = BertForTokenClassification.from_pretrained('monilouise/ner_pt_br')
```

Is there anything else missing from the recommended sharing procedures?

Thanks in advance.

**Comment by patrickvonplaten** [comment]
Hey @moniquebm, 

I cannot reproduce this error on master.

it looks like you are working with an old version of transformers. Could you try updating `transformers` to `3.5.0` to see if the error persists?

Another reason why this doesn't work might be that you have a directory locally that is also called `monilouise/ner_pt_br`, so that instead of downloading from the model hub `from.pretrained()` tries to load a local model. You can check whether this might  be the problem by running the command from a different directory or checking whether you have a local dir called `monilouise`.

**Comment by julien-c** [comment]
@patrickvonplaten is 100% right on his first guess that it's due to using transformers < `v3.5.x`

We backport new git-based models back to the previous S3 bucket (for models to be usable on previous versions of the library) automatically, however there was a hiccup yesterday that crashed the process (it's currently sync'ing again).

**Comment by moniquebm** [comment]
Hi @patrickvonplaten and @julien-c ,  

I've just updated transformers version and it worked.  

Thanks!
