### ISSUE TITLE
Allow to provide specific params in WandbCallback

### ISSUE THREAD

**Issue by raphael0202** [huggingface/transformers#8754]
# 🚀 Feature request

It would be nice to be able to track additional params in wandb when using the Trainer interface. For example, I need to track down how many layers were frozen in each experiment. I'm currently using a custom WandCallback class to do this.

## Your contribution

I can work on a PR.

**Comment by borisdayma** [comment]
Sorry I just noticed this issue.
You can actually already do it. After your run has been created, you can do `wandb.config['frozen_layers'] = 3`
We need to add a way to let you also create a run first (instead of `Trainer`) and then let `Trainer` adds automatically the extra configuration parameters.
