### ISSUE TITLE
Why Bert-chinese use do_lower_case=False?

### ISSUE THREAD

**Issue by Fei-Wang** [huggingface/transformers#9286]
Some Chinese Text has some English words, for example: "Apples是苹果的复数形式。". I have questions about how to tokenize the text:

1.  why Chinese Bert Case sensitive, but I can't find even 'A' in vocab.txt
2.  Because English words in Chinese vocab.txt is few, should I use wordpiece tokenizer as default, like "['apple', '##s', '是', '苹', ...]"or split to char to tokenize, like "['a', 'p', 'p', 'l', 'e', 's', '是', '苹', ...]"?

**Comment by patrickvonplaten** [comment]
Hmm, I don't really know how to best answer your question here...maybe @JetRunner ?

**Comment by zyberg2091** [comment]
using lowercase=False preserves the information about casing and this information maybe helpful in the context of the some work. such as for sentiment analysis i think casing is not important there but for the task like NER it maybe useful. Again but for many task where we deal with multiple languages is it recommended to use cased model because i think every language has its own grammar and syntax and maybe casing helps in some or the other way?

Could this be the reason why Bert-chinese uses lowercase=False by default?

**Comment by Fei-Wang** [comment]
I think your explanation makes sense. 
But there are no capital letters in the Chinese vocab.txt, so all words contain capitals will be regarded as [unk].

**Comment by JetRunner** [comment]
Well I would say the design of Chinese BERT is not necessarily the best. It makes sense to use only lower cases to resolve the data sparsity since there are not many English sentences in Chinese Wikipedia.
