### ISSUE TITLE
[Marian] Doc says `config.add_bias_logits=True`, but config is has `config.add_bias_logits=False`

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/transformers#9383]
**Question**:

In the docs, it is written that Marian has (contrary to Bart), `config.add_bias_logits=True`: https://huggingface.co/transformers/model_doc/marian.html#implementation-notes. But when looking into the code: 
https://github.com/huggingface/transformers/blob/b01f451ca38695c60175b34d245997ef4d18231d/src/transformers/models/marian/configuration_marian.py#L25 Marian has the exact same default config as Bart and also Marian's config files online have `config.add_bias_logits=False` - see:
https://huggingface.co/Helsinki-NLP/opus-mt-en-de/resolve/main/config.json

@sshleifer @patil-suraj 

Is the documentation not up-to-date anymore? Because all the slow tests are passing....

**Comment by sshleifer** [comment]
I think what's going on is that `config.add_final_bias_logits` is unused.

In modeling_bart.py line 148 we call

```python
self.register_buffer("final_logits_bias", torch.zeros((1, self.model.shared.num_embeddings)))
```
regardless of the config, and then if it's in the state dict it will get loaded by `from_pretrained`.

I do think that `final_bias_logits` is in the marian state dict, as this line would have `KeyError`'d during conversion otherwise: https://github.com/sshleifer/transformers_fork/blob/121ec9dced3d068352078e7c3523ecd66830e39e/src/transformers/models/marian/convert_marian_to_pytorch.py#L461-L461
