### ISSUE TITLE
Multilingual MiniLM

### ISSUE THREAD

**Issue by rodrigoheck** [huggingface/transformers#9573]
Hello everyone! 

I am trying to load this model from Microsoft using the path provided [here](huggingface.co/microsoft/Multilingual-MiniLM-L12-H384). I am applying the same code provided there:

`tokenizer = AutoTokenizer.from_pretrained("microsoft/Multilingual-MiniLM-L12-H384")`

But I am facing this error message:

`stat: path should be string, bytes, os.PathLike or integer, not NoneType`

My intuition says that the model is not correctly stored on the server, but I am not sure.

**Comment by rodrigoheck** [comment]
Alright! I found the solution. For the tokenizer, XLMRobertaTokenizer should be used instead of AutoTokenizer.

**Comment by julien-c** [comment]
Thanks for reporting. Now that we have model versioning, the author(s) of [`"microsoft/Multilingual-MiniLM-L12-H384"`](https://huggingface.co/microsoft/Multilingual-MiniLM-L12-H384) could update the model's config.json to specify a `tokenizer_class` so that AutoTokenizer works out of the box.

@JetRunner @LysandreJik do you remember who the model author(s) are?

**Comment by JetRunner** [comment]
I think I did the uploading. I'll update the config tomorrow!

**Comment by sersoage** [comment]
I believe the config is not yet updated because the error is still there

**Comment by JetRunner** [comment]
@sersoage Re-uploading it now. Thanks for the note!

**Comment by JetRunner** [comment]
Done

**Comment by sersoage** [comment]
@JetRunner  Thank you!
