### ISSUE TITLE
AttributeError: 'Seq2SeqTrainer' object has no attribute '_actual_model'

### ISSUE THREAD

**Issue by caralen** [huggingface/transformers#9672]
_actual_model method is not defined in the Seq2SeqTrainer class, nor in the Trainer class from which is derived 

https://github.com/huggingface/transformers/blob/12c1b5b8f448d652f5e1fa0f069b9569f4540948/examples/seq2seq/seq2seq_trainer.py#L63

**Comment by patil-suraj** [comment]
Hi @caralen 

the `Seq2SeqTrainer` is now integrated with the main lib, now it's under `src/trainer_seq2seq.py`, and the seq2seq_trainer in examples is about to be deprecated, this bug is fixed in the new version, so I would recommend you to use the new`Seq2SeqTrainer` from the lib rather than examples folder,

you could directly import it from transformers using
```python
from transformers import Seq2SeqTrainer
```

**Comment by caralen** [comment]
Hi @patil-suraj, thanks for the quick reply. I will close this issue now.
