### ISSUE TITLE
DeepSpeed: Exits with CUDA runtime error on A100 (requires recompiling DeepSpeed for NVIDIA 8.0 Arch)

### ISSUE THREAD

**Issue by PeterAJansen** [huggingface/transformers#9709]
## Environment info

- `transformers` version: 4.3.0 (unofficial, off current main branch)
- Platform: Linux
- Python version: 3.7
- PyTorch version (GPU?): 1.7.1
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: Yes

## Information

Model I am using (Bert, XLNet ...): T-5

The problem arises when using:
* [ ] the official example scripts: examples/seq2seq/finetune_trainer.py

## Issue

In the hopes this saves others some time since it took a while for me to fix:  When running the new DeepSpeed mode in Transformers 4.3.0 on an A100 GPU, it will exit with a runtime error:

RuntimeError: CUDA error: no kernel image is available for execution on the device

For me, this was due to installing DeepSpeed from pip rather than source.  The A100 architecture appears not to be (as of this writing) installed in the default.  If you install from source as described in this post ( https://www.deepspeed.ai/tutorials/advanced-install/ ), the error goes away.  The post suggests selecting the architecture using the TORCH_CUDA_ARCH_LIST environment variable, but I found just using the install.sh script (which I am assuming auto-detects the architecture of your GPU) worked more successfully.

**Comment by LysandreJik** [comment]
Pinging @stas00

**Comment by stas00** [comment]
Heh, actually I wrote this section: https://www.deepspeed.ai/tutorials/advanced-install/#building-for-the-correct-architectures and the autodetector, since I originally had the same issue. `TORCH_CUDA_ARCH_LIST` is there if you say want to use the binary build on another machine or want to optimize it for whatever reason. e.g. I build it with:
```
time TORCH_CUDA_ARCH_LIST="6.1;8.6" DS_BUILD_OPS=1 pip install --no-cache -v --disable-pip-version-check -e .
```
because I have 1070 and 3090 cards.

Now, this is a purely DeepSpeed issue and has nothing to do with transformers, other than perhaps a documentation issue.

I'm all ears at how perhaps we can improve it. 

1. Probably should recommend to install from source
2. but then when we bail on missing `deepspeed` we say do `pip install deepspeed` - do you think we should change that to:
>  `pip install deepspeed` or if it doesn't work install from source?

The thing is `pip install deepspeed` is installing from source, but I think it perhaps isn't using the same build script? So should we say:
>  `pip install deepspeed` or if it doesn't work install from https://github.com/microsoft/deepspeed? 

or may be easier to just say: 
> install from https://github.com/microsoft/deepspeed?

In any case let's discuss this over at DeepSpeed Issues - @PeterAJansen, would you please open an issue there because only you can report/reproduce the specific error - should they fix the pip build. and tag me?

BTW, fairscale has its own issues with `pip install fairscale` I also have to build from the the repo.

Thank you!
