### ISSUE TITLE
Some model use serve previous version can not do inference in web api.

### ISSUE THREAD

**Issue by svjack** [huggingface/transformers#9850]
the model serve in
https://huggingface.co/wptoux/albert-chinese-large-qa
can not do inference by click “compute” button.
because it use transformers 3.0.2 but can not
properly load in current version.
I think model online server should consider its implement transformer version.

**Comment by LysandreJik** [comment]
The error here seems to be because there's a dissociated tokenizer and model. The tokenizer should be BERT while the model should be ALBERT.

The configuration should reflect this by having a `"tokenizer_class": "BertTokenizer"`.

Pinging @wptoux

An example can be seen with PhoBERT having the model set as RoBERTa and the tokenizer as `PhobertTokenizer`: https://huggingface.co/vinai/phobert-base/blob/main/config.json

**Comment by wptoux** [comment]
> The error here seems to be because there's a dissociated tokenizer and model. The tokenizer should be BERT while the model should be ALBERT.
> 
> The configuration should reflect this by having a `"tokenizer_class": "BertTokenizer"`.
> 
> Pinging @wptoux
> 
> An example can be seen with PhoBERT having the model set as RoBERTa and the tokenizer as `PhobertTokenizer`: https://huggingface.co/vinai/phobert-base/blob/main/config.json

This library has improved a lot since I release this model, I will update it.

**Comment by LysandreJik** [comment]
Glad to hear it @wptoux! Thank you!

**Comment by wptoux** [comment]
I have fixed the problem, and the web api is working now.

Here is an test example

Context: 李白（701年—762年12月） ，字太白，号青莲居士，又号“谪仙人”，唐代伟大的浪漫主义诗人，被后人誉为“诗仙”，与杜甫并称为“李杜”，为了与另两位诗人李商隐与杜牧即“小李杜”区别，杜甫与李白又合称“大李杜”。北京大学教授李志敏评价：“李白之诗呼吸宇宙，出乎道；杜甫之诗德参天地，源于儒，皆至天人合一境界，故能出神入化。

Question: 如何评价李白的诗

Answer: 李白之诗呼吸宇宙，出乎道
